INSERT INTO public.bank_soal (id, kategori, sub_aspek, tipe_soal, level_kognitif, tingkat_kesulitan, indikator_kompetensi, soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, pembahasan, bobot, aktif) VALUES
(
    '87362681-7347-426e-9d47-bb556df92303',
    'Makharijul Huruf',
    'Alif (ا)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Alif (ا)',
    'Murid membaca huruf alif yang berharakat sukun di tengah kata seolah ada hentakan/penekanan tertentu, padahal alif seharusnya mengalir tanpa titik tekan di mulut atau tenggorokan mana pun. Bagaimana guru menjelaskan hal ini?',
    'Minta murid mengucapkan alif dengan menutup sedikit rongga tenggorokan agar bunyinya lebih tegas dan mudah dibedakan dari hamzah',
    'Jelaskan bahwa alif sukun harus selalu diberi tekanan ringan di ujung lidah agar terdengar jelas dan tidak tertukar huruf lain',
    'Jelaskan bahwa alif sukun sebenarnya keluar dari pangkal tenggorokan seperti hamzah, sehingga hentakan tersebut sudah benar dan tidak perlu dikoreksi',
    'Alif termasuk huruf mad yang tidak memiliki titik keluar tertentu di rongga mulut/tenggorokan, bunyinya mengalir bebas lewat rongga, tidak boleh dihentak seperti huruf konsonan lain',
    'D',
    '',
    1,
    true
  ),
(
    'a31fa540-007d-40e4-951d-cdb0501875b5',
    'Sifatul Huruf',
    'Alif vs Hamzah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Alif vs Hamzah',
    'Seorang murid selalu memperlakukan alif seperti hamzah — setiap ada alif, ia mengucapkannya dengan hentakan glotal tegas. Apa penjelasan paling tepat untuk meluruskannya?',
    'Jelaskan bahwa perbedaan alif-hamzah hanya berlaku dalam penulisan, bukan pengucapan, sehingga keduanya boleh dibaca sama',
    'Jelaskan bahwa alif dan hamzah adalah huruf yang sama persis, sehingga cara membaca murid tersebut sudah benar',
    'Alif dan hamzah memang berbeda huruf, hamzah punya makhraj tegas di pangkal tenggorokan dengan hentakan, sedangkan alif murni huruf mad yang mengalir tanpa hentakan sama sekali',
    'Minta murid berhenti membedakan alif dan hamzah karena topik ini terlalu rumit untuk tahap belajar saat ini, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '5107be44-6466-47fc-8553-df9ab31290f4',
    'Makharijul Huruf',
    'Ba (ب)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ba (ب)',
    'Murid mengucapkan ba dengan menyentuhkan bibir bawah ke gigi atas (posisi fa), bukan mempertemukan dua bibir. Bunyinya jadi samar antara ba dan fa. Koreksinya?',
    'Contohkan posisi benar: pertemukan kedua bibir hingga rapat, lepas dengan hentakan untuk bunyi ba, bandingkan dengan posisi fa yang pakai gigi',
    'Biarkan saja, selama bunyi akhirnya masih terdengar mirip ba, posisi bibir tidak terlalu berpengaruh pada makna',
    'Suruh murid mengucapkan ba lebih keras tanpa mengoreksi posisi bibirnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti huruf ba dengan mim untuk sementara karena keduanya dari bibir dan dianggap lebih mudah dibedakan dari fa',
    'A',
    '',
    1,
    true
  ),
(
    'e001ddfb-1a84-48ac-9161-0349dc7215fb',
    'Sifatul Huruf',
    'Ba (ب) - Qalqalah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ba (ب) - Qalqalah',
    'Murid membaca kata berakhiran ba mati saat waqaf, tapi dibaca datar tanpa pantulan sama sekali. Koreksinya?',
    'Minta murid mengulang dengan suara lebih keras agar pantulannya muncul otomatis, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, pantulan hanya berlaku untuk qaf dan tha, bukan ba yang tergolong huruf bibir, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ba termasuk salah satu dari lima huruf qalqalah (bersama qaf, tha, jim, dal), sehingga saat mati harus dibaca dengan pantulan ringan',
    'Jelaskan bahwa pantulan pada ba hanya berlaku di awal kata, bukan saat di akhir kata ketika waqaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '4f36cad4-0840-434e-8ffd-f36fd88a317a',
    'Sifatul Huruf',
    'Ta (ت)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ta (ت)',
    'Murid mengucapkan ta dengan bunyi sangat tertahan dan berat, mendekati tha, padahal ta seharusnya berhembus ringan. Koreksinya?',
    'Suruh murid menahan napas sepenuhnya saat mengucapkan ta agar terdengar lebih tegas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, ta dan tha sama persis dalam ketebalan bunyi, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ta termasuk huruf hams, hembusan napas ikut keluar, tidak boleh ditekan berat seperti tha yang tebal. contohkan bunyi ta yang ringan berhembus',
    'Ganti huruf ta dengan dal karena makhrajnya sama dan dianggap lebih mudah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '87124f96-101d-40fb-9bf3-e0411ffcfb6a',
    'Sifatul Huruf',
    'Ta (ت) bukan Qalqalah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ta (ت) bukan Qalqalah',
    'Guru baru menduga ta termasuk huruf qalqalah karena sering dengar muridnya memantulkan ta mati. Penjelasan tepat?',
    'Ta termasuk qalqalah hanya jika di akhir kata, tidak jika di tengah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Benar, ta termasuk qalqalah karena posisinya berdekatan dengan dal dan tha, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ta bukan huruf qalqalah. hanya lima huruf tertentu (ba-jim-dal-tha-qaf) yang dipantulkan, sehingga kebiasaan memantulkan ta mati perlu dikoreksi jadi bacaan datar',
    'Semua huruf dari ujung lidah termasuk qalqalah, termasuk ta, dal, dan tha, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '8db037bb-5432-43bf-8921-850ea059b8b7',
    'Makharijul Huruf',
    'Tsa (ث)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tsa (ث)',
    'Murid menempelkan ujung lidah rapat ke gigi seri (bukan menyentuh ringan) saat mengucapkan tsa, sehingga bunyinya tertahan seperti ta. Koreksinya?',
    'Ganti huruf tsa dengan sin karena bunyi desisnya mirip dan dianggap lebih mudah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Tsa termasuk huruf rakhawah (mengalir, tidak tertahan) sehingga ujung lidah cukup disentuhkan ringan ke gigi seri atas, membiarkan udara tetap mengalir',
    'Biarkan saja, tsa dan ta boleh dibaca sama selama maknanya masih bisa dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid menekan lidahnya lebih kuat lagi ke gigi seri agar bunyi tsa lebih jelas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    '07c5ffc6-0cf6-4864-9915-2216ec1e83a3',
    'Sifatul Huruf',
    'Tsa (ث)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tsa (ث)',
    'Guru ingin menjelaskan mengapa tsa terdengar berhembus khas dibanding huruf berdekatan seperti dal/ta. Penjelasan tepat?',
    'Karena tsa punya tanda baca khusus di mushaf yang mewajibkan hembusan tambahan sebagai simbol kehati-hatian, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Karena tsa adalah huruf tersulit di antara semua huruf hijaiyah sehingga otomatis berhembus, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Karena tsa berasal dari makhraj yang sama dengan kha yang juga berhembus akibat posisi di tenggorokan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Karena tsa termasuk huruf hams, sehingga pita suara tidak tertahan penuh dan udara ikut keluar bersama bunyinya',
    'D',
    '',
    1,
    true
  ),
(
    '46d7eec3-1633-4149-b509-255e594a95ac',
    'Makharijul Huruf',
    'Jim (ج)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Jim (ج)',
    'Murid mengucapkan jim dengan posisi lidah terlalu maju ke depan, mendekati dal, sehingga bunyinya kurang jelas sebagai jim. Koreksinya?',
    'Biarkan saja, jim dan dal cukup mirip dan tidak terlalu berpengaruh pada makna, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti huruf jim dengan ya karena sama-sama dari tengah lidah dan dianggap lebih mudah dibedakan dari dal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Jim keluar dari tengah lidah menyentuh langit-langit tengah (bukan ujung lidah ke gigi seperti dal), contohkan posisi mengangkat bagian tengah lidah',
    'Minta murid mengucapkan jim lebih keras tanpa mengubah posisi lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'C',
    '',
    1,
    true
  ),
(
    '6a26017b-8a2e-43d6-9c59-44daf2a3ad27',
    'Sifatul Huruf',
    'Jim (ج) Syiddah+Qalqalah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Jim (ج) Syiddah+Qalqalah',
    'Murid membaca kata berakhiran jim mati saat waqaf dengan bunyi sangat datar dan lembek, tanpa ketegasan maupun pantulan. Koreksinya, mengingat jim punya dua sifat sekaligus?',
    'Biarkan saja, jim yang dibaca lembek dan datar masih bisa diterima selama murid tahu artinya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti bacaan jim mati tersebut dengan bunyi ya agar lebih mudah diucapkan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Jim adalah huruf syiddah (tertahan penuh) sekaligus huruf qalqalah, sehingga saat mati harus dibaca dengan ketegasan tertahan disertai pantulan ringan',
    'Jelaskan bahwa jim hanya perlu dibaca tegas tanpa pantulan, karena sifat qalqalah tidak berlaku untuk huruf tengah lidah',
    'C',
    '',
    1,
    true
  ),
(
    '250bbef3-62bf-4db6-8e9d-ee9929787b13',
    'Makharijul Huruf',
    'Ha kecil (ح)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha kecil (ح)',
    'Murid mengucapkan ha (ح) dengan posisi terlalu dalam di tenggorokan, mendekati kha, sehingga terdengar lebih kasar. Koreksinya?',
    'Minta murid menekan tenggorokannya lebih dalam lagi agar bunyi ha lebih tegas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, ha dan kha boleh dibaca sama selama maknanya masih bisa dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti huruf ha dengan hamzah karena sama-sama dari tenggorokan dan dianggap lebih mudah dibedakan dari kha, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Ha (ح) keluar dari tengah tenggorokan dengan hembusan halus dan lembut, beda dari kha yang lebih dekat ke mulut dengan bunyi berdesir kasar',
    'D',
    '',
    1,
    true
  ),
(
    '32500e4a-1a17-4c2e-9c1e-2d48ed14e04c',
    'Sifatul Huruf',
    'Ha kecil (ح)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha kecil (ح)',
    'Guru ingin menjelaskan mengapa ha (ح) tidak boleh dibaca tertahan penuh seperti jim, meski posisinya berdekatan. Penjelasan tepat?',
    'Karena ha (ح) sebenarnya termasuk huruf syiddah sama seperti jim, sehingga seharusnya juga dibaca tertahan penuh',
    'Karena ha (ح) termasuk huruf hams dan rakhawah, bunyinya mengalir disertai hembusan napas, tidak tertahan penuh seperti jim yang syiddah',
    'Karena ha (ح) tidak memiliki sifat khusus apa pun, boleh dibaca dengan cara apa saja, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Karena ha (ح) hanya digunakan pada kata-kata jarang muncul, sifatnya tak perlu terlalu diperhatikan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    '5ec36ad5-975a-4fc8-a7e2-d05031568246',
    'Makharijul Huruf',
    'Kha (خ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kha (خ)',
    'Murid mengucapkan kha dengan posisi terlalu maju ke arah ha (ح), sehingga bunyi hembusan kasarnya hilang. Koreksinya?',
    'Biarkan saja, kha dan ha (ح) boleh dibaca sama karena sama-sama dari tenggorokan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan kha lebih pelan tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti kha dengan ghain karena keduanya dianggap sama persis dari segi makhraj dan sifat, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Kha keluar dari pangkal lidah bagian belakang mendekati anak tekak, berbeda dari ha (ح) yang lebih dalam dan halus. contohkan hembusan kasar berdesir',
    'D',
    '',
    1,
    true
  ),
(
    '341a6f19-9ed2-495d-92bd-bfe1a5c2d2b8',
    'Sifatul Huruf',
    'Kha (خ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kha (خ)',
    'Guru menjelaskan mengapa kha selalu terdengar ''berdesir'' dibanding huruf tenggorokan lain. Penjelasan tepat?',
    'Karena kha adalah huruf paling berat dalam bahasa Arab sehingga otomatis berdesir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Karena kha termasuk huruf hams dan rakhawah, sehingga udara ikut mengalir keluar bersama bunyinya, menghasilkan desiran khas. beda dari huruf syiddah yang tertahan',
    'Karena kha memiliki tanda baca khusus yang mewajibkan desiran tambahan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Karena kha termasuk huruf qalqalah yang selalu dipantulkan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'B',
    '',
    1,
    true
  ),
(
    '5beadba3-2cf1-441f-bfa3-e88d03cd97e1',
    'Makharijul Huruf',
    'Dal (د)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dal (د)',
    'Murid mengucapkan dal dengan lidah terlalu ke belakang, mendekati posisi ta/tha. Koreksinya?',
    'Dal keluar dari ujung lidah menyentuh pangkal gigi seri atas (sama seperti ta/tho tapi beda sifat), harus ditekan tegas lalu dilepas',
    'Ganti dal dengan tha karena keduanya dianggap sama persis, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, dal boleh dibaca dari posisi mana saja selama bunyi akhirnya mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid membaca dal lebih pelan tanpa mengoreksi posisi lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'A',
    '',
    1,
    true
  ),
(
    '404524ab-ccb2-4b14-869f-18f9d4e98c9d',
    'Sifatul Huruf',
    'Dal (د)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dal (د)',
    'Guru menjelaskan sifat jahr pada dal dibanding ta yang hams. Penjelasan tepat?',
    'Dal bersifat qalqalah sekaligus hams, sehingga harus dipantulkan dengan hembusan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Dal bersifat jahr, pita suara bergetar penuh saat diucapkan, beda dari ta yang hams (berhembus, pita suara tidak bergetar penuh)',
    'Perbedaan dal dan ta hanya soal ketebalan tafkhim-tarqiq, bukan getaran pita suara, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Dal dan ta sama-sama hams sehingga tidak ada perbedaan getaran pita suara, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'B',
    '',
    1,
    true
  ),
(
    '647b0f51-9996-4e39-9895-5ee7fccd6923',
    'Makharijul Huruf',
    'Dzal (ذ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dzal (ذ)',
    'Murid mengucapkan dzal tanpa menjulurkan ujung lidah ke gigi, hanya dari dalam mulut. Koreksinya?',
    'Ganti dzal dengan za karena keduanya dianggap sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Dzal (bersama tsa dan zho) mengharuskan ujung lidah keluar sedikit menyentuh ujung gigi seri atas. jika lidah tidak keluar, bunyi dzal berubah mendekati za/da',
    'Minta murid mengucapkan dzal lebih keras tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, dzal boleh diucapkan tanpa menjulurkan lidah selama bunyi akhirnya masih mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'B',
    '',
    1,
    true
  ),
(
    'f7f6d8ac-d256-45be-897c-d73b32319593',
    'Sifatul Huruf',
    'Dzal (ذ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dzal (ذ)',
    'Guru menjelaskan kenapa dzal ringan dibanding zho yang tebal, meski posisi mirip. Penjelasan tepat?',
    'Karena dzal hanya muncul di kata-kata pendek sehingga terdengar ringan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Karena dzal dan zho sebenarnya sama tebalnya, hanya beda penulisan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Karena dzal termasuk huruf qalqalah sehingga otomatis ringan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Dzal bersifat istifal (tipis) karena lidah belakang tetap datar, beda dari zho yang lidah belakangnya terangkat membentuk gelombang sehingga tebal (isti''la)',
    'D',
    '',
    1,
    true
  ),
(
    'ef6c60a1-02ce-45c0-9c89-75f502b4943c',
    'Makharijul Huruf',
    'Ra (ر)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ra (ر)',
    'Murid mengucapkan ra tanpa getaran sama sekali, terdengar seperti lam. Koreksinya?',
    'Minta murid mengucapkan ra lebih pelan tanpa menambahkan getaran, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ra keluar dari ujung lidah dekat gusi atas dengan getaran ringan satu-dua kali. kalau getaran hilang sama sekali, bunyinya berubah mendekati lam yang jernih tanpa getar',
    'Biarkan saja, ra dan lam memang boleh dibaca sama dalam kondisi tertentu, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti ra dengan lam karena keduanya dianggap memiliki makhraj yang identik, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    '0b10e4ee-fa20-4f0d-a917-c689173cb993',
    'Sifatul Huruf',
    'Ra (ر) - Takrir',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ra (ر) - Takrir',
    'Guru menjelaskan sifat takrir (getaran/pengulangan) pada ra yang unik dibanding huruf lain. Penjelasan tepat?',
    'Sifat takrir berarti ra harus diulang pengucapannya dua kali secara terpisah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat takrir sama dengan sifat qalqalah yang dimiliki huruf ba dan qaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Sifat takrir hanya berlaku jika ra berada di awal kata, bukan di tengah atau akhir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ra memiliki sifat takrir, yaitu getaran ringan pada ujung lidah. namun getaran ini tidak boleh berlebihan (digulung panjang) karena akan terdengar dibuat-buat',
    'D',
    '',
    1,
    true
  ),
(
    'd2ed3adc-a5a7-4956-833c-fa610d50e7f1',
    'Sifatul Huruf',
    'Zai (ز)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zai (ز)',
    'Murid mengucapkan zai tanpa getaran pita suara, terdengar seperti sin. Koreksinya?',
    'Biarkan saja, zai dan sin boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan zai lebih keras tanpa mengoreksi getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Zai keluar dari posisi yang sama dengan sin (ujung lidah dekat gigi bawah), tapi zai bersifat jahr (bergetar) sedangkan sin hams (berhembus tanpa getar). pastikan pita suara ikut bergetar',
    'Ganti zai dengan shad karena dianggap lebih mudah dibedakan dari sin, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '11ab3925-ff9b-4527-807e-d2b9ad4869bd',
    'Sifatul Huruf',
    'Zai (ز)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zai (ز)',
    'Guru menjelaskan ketebalan relatif zai dibanding shad. Penjelasan tepat?',
    'Zai dan shad sama-sama tebal karena keduanya bersifat shafir, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Zai lebih tebal dari shad karena posisinya lebih dekat ke gigi bawah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Zai termasuk huruf istifal (tipis/ringan), berbeda dari shad yang isti''la (tebal), meski keduanya sama-sama huruf desis (shafir)',
    'Ketebalan zai bergantung pada harakat sebelumnya, sama seperti ra, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '06aaf07a-81dc-42db-9649-f87af7a56972',
    'Makharijul Huruf',
    'Sin (س)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Sin (س)',
    'Murid mengucapkan sin dengan ujung lidah menyentuh gigi (bukan mendekat saja), sehingga bunyi desisnya hilang. Koreksinya?',
    'Sin keluar dari ujung lidah yang didekatkan (bukan ditempelkan penuh) ke gigi seri bawah, menghasilkan celah kecil untuk desisan. jika ditempel penuh, desisan hilang dan berubah mendekati ta/tsa',
    'Ganti sin dengan tsa karena keduanya dianggap sama posisi keluarnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Biarkan saja, sin boleh diucapkan dengan lidah menempel penuh selama bunyi akhirnya masih terdengar mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan sin lebih keras tanpa mengubah jarak lidah dan gigi, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    'ed891dd0-1f1e-4741-afe4-477750d03763',
    'Sifatul Huruf',
    'Sin (س) - Shafir',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Sin (س) - Shafir',
    'Guru menjelaskan sifat shafir (desis) pada sin dibanding huruf lain yang mirip posisi. Penjelasan tepat?',
    'Sin memiliki sifat shafir (bunyi desis tajam seperti siulan kecil) bersama zai dan shad. desis ini muncul karena celah sempit antara lidah dan gigi yang dilewati udara',
    'Sifat shafir sama dengan sifat qalqalah yang menghasilkan pantulan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Sifat shafir hanya dimiliki sin seorang diri di antara semua huruf hijaiyah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat shafir muncul karena sin selalu berharakat kasrah dalam Al-Qur''an, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'A',
    '',
    1,
    true
  ),
(
    'caf22fa9-3b7c-4a4e-9323-f03e6249ed08',
    'Makharijul Huruf',
    'Syin (ش)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Syin (ش)',
    'Murid mengucapkan syin dengan desis sempit seperti sin, bukan desis lebar. Koreksinya?',
    'Minta murid mengucapkan syin lebih pelan tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Syin keluar dari tengah lidah menyentuh langit-langit tengah dengan desis yang menyebar lebar (tafasysyi), beda dari sin yang desisnya sempit dan tajam dari ujung lidah',
    'Biarkan saja, syin dan sin boleh dibaca sama karena sama-sama huruf desis, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti syin dengan jim karena keduanya dari tengah lidah dan dianggap sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    '2a2e7f52-3f17-4e88-9050-a3a38a6f7dfd',
    'Sifatul Huruf',
    'Syin (ش) - Tafasysyi',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Syin (ش) - Tafasysyi',
    'Guru menjelaskan sifat tafasysyi (menyebar) yang khas dimiliki syin. Penjelasan tepat?',
    'Syin memiliki sifat tafasysyi, yaitu udara menyebar luas di rongga mulut saat diucapkan, menghasilkan desis yang lebih lebar dibanding huruf desis lainnya seperti sin dan shad',
    'Sifat tafasysyi sama dengan sifat ghunnah yang dimiliki nun dan mim, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Sifat tafasysyi berarti syin harus diucapkan dua kali berturut-turut, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat tafasysyi hanya muncul jika syin berada di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    'ff9fa3d3-c7a6-42e6-aa18-810f2b0a7686',
    'Sifatul Huruf',
    'Shad (ص)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Shad (ص)',
    'Murid mengucapkan shad dengan bunyi tipis seperti sin, tidak menggembung. Koreksinya?',
    'Shad dari posisi yang sama dengan sin (ujung lidah dekat gigi bawah), tapi shad bersifat isti''la (tebal) sehingga lidah belakang terangkat dan rongga mulut terasa menggembung, beda dari sin yang tipis',
    'Biarkan saja, shad dan sin boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti shad dengan dhad karena keduanya dianggap sama-sama huruf tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Minta murid mengucapkan shad lebih keras tanpa mengangkat lidah belakang, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    '6f645ac9-052f-47f9-9fc3-6027fa1ab3b2',
    'Sifatul Huruf',
    'Shad (ص) - Ithbaq',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Shad (ص) - Ithbaq',
    'Guru menjelaskan mengapa shad memiliki sifat ithbaq selain isti''la. Penjelasan tepat?',
    'Sifat ithbaq berarti shad harus diucapkan dengan mulut tertutup rapat sepenuhnya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat ithbaq hanya berlaku untuk shad seorang diri di antara semua huruf isti''la, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Shad memiliki sifat ithbaq, yaitu bagian tengah lidah menempel rapat ke langit-langit atas (bersama dhad, tho, zho), menghasilkan bunyi yang lebih tebal dan penuh dibanding huruf isti''la lain yang tidak ithbaq seperti qaf, kha, ghain',
    'Sifat ithbaq sama dengan sifat qalqalah pada huruf ba dan qaf, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'C',
    '',
    1,
    true
  ),
(
    '8fd1a6f0-ad9b-40e0-bf5f-e15bdad543e6',
    'Makharijul Huruf',
    'Dhad (ض)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dhad (ض)',
    'Murid mengucapkan dhad dari ujung lidah, bukan tepi lidah. Koreksinya?',
    'Minta murid mengucapkan dhad lebih keras tanpa mengoreksi posisi tepi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti dhad dengan dal karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Biarkan saja, dhad boleh diucapkan dari ujung lidah selama terdengar berat, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Dhad keluar dari salah satu atau kedua tepi lidah yang menyentuh gigi geraham atas, posisi paling unik di antara semua huruf, contohkan langsung sambil murid merasakan tepi lidahnya sendiri',
    'D',
    '',
    1,
    true
  ),
(
    '18389330-4e42-4718-875d-5f166a356d2e',
    'Sifatul Huruf',
    'Dhad (ض) - Kombinasi Sifat',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dhad (ض) - Kombinasi Sifat',
    'Guru menjelaskan mengapa dhad dianggap huruf tersulit sifatnya di antara huruf hijaiyah. Penjelasan tepat?',
    'Dhad sulit karena termasuk huruf hams yang jarang dilatih, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Dhad menggabungkan banyak sifat sekaligus (isti''la, ithbaq, jahr, dan istithalah/memanjang di tepi lidah), sehingga kombinasi sifat inilah yang membuatnya sulit dan unik',
    'Dhad sulit karena hanya muncul satu kali dalam seluruh Al-Qur''an, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Dhad sulit hanya karena bentuk tulisannya rumit, bukan karena sifat pengucapannya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    'fb9ea2d3-0952-46f0-82e3-12d73ded6476',
    'Makharijul Huruf',
    'Tho (ط)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tho (ط)',
    'Murid mengucapkan tho tanpa penekanan, terdengar seperti ta. Koreksinya?',
    'Ganti tho dengan dal karena keduanya dianggap sama-sama jahr, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Minta murid mengucapkan tho lebih cepat tanpa menambah tekanan lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, tho dan ta boleh dibaca sama selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Tho dari posisi sama dengan ta (ujung lidah ke pangkal gigi seri atas), tapi tho bersifat isti''la dan ithbaq sehingga ditekan lebih kuat dan rongga mulut terasa membulat',
    'D',
    '',
    1,
    true
  ),
(
    '2351c1f6-61d6-46e5-a98b-9ff14a09903d',
    'Sifatul Huruf',
    'Tho (ط) - Empat Sifat',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tho (ط) - Empat Sifat',
    'Guru menjelaskan kombinasi sifat pada tho (isti''la + ithbaq + jahr + qalqalah). Penjelasan tepat?',
    'Tho hanya memiliki sifat isti''la saja, sifat lain miliknya sama seperti ta biasa, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Tho adalah satu-satunya huruf yang punya empat sifat sekaligus (isti''la, ithbaq, jahr, dan qalqalah), sehingga bunyinya tebal, menggembung, bergetar, dan memantul saat mati',
    'Tho bersifat hams seperti ta, sehingga tidak ada getaran pita suara, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Tho tidak termasuk huruf qalqalah karena posisi keluarnya sama dengan ta, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    '7b2cafbf-f0aa-4ad5-a633-cdecdc7c7428',
    'Makharijul Huruf',
    'Zho (ظ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zho (ظ)',
    'Murid mengucapkan zho tanpa mengangkat lidah belakang, terdengar seperti dza. Koreksinya?',
    'Zho dari posisi sama dengan dza (ujung lidah digigit ringan di gigi depan), tapi lidah belakang harus naik membentuk gelombang agar bunyi tebal, beda dari dza yang lidah belakangnya tetap datar',
    'Ganti zho dengan tho karena keduanya dianggap sama-sama tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Minta murid menggigit lidahnya lebih keras tanpa mengangkat lidah belakang, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, zho dan dza boleh dibaca sama karena posisi gigitannya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'A',
    '',
    1,
    true
  ),
(
    '46dd0fe5-f544-4cf8-a0e2-f46dea972b43',
    'Sifatul Huruf',
    'Zho (ظ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zho (ظ)',
    'Guru menjelaskan kombinasi sifat zho (isti''la + ithbaq + jahr) dibanding dza. Penjelasan tepat?',
    'Zho bersifat hams seperti tsa, sehingga tidak ada getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Zho termasuk huruf qalqalah bersama dza dan tsa, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Zho memiliki sifat isti''la dan ithbaq (tebal dan menggembung) serta jahr (bergetar), sedangkan dza hanya istifal (tipis) meski keduanya sama-sama jahr dan posisi gigitannya sama',
    'Zho dan dza memiliki sifat yang identik, hanya beda pada penulisan hurufnya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'C',
    '',
    1,
    true
  ),
(
    '321dec3d-dd16-4bbb-b274-7c61a65f8a1e',
    'Makharijul Huruf',
    '''Ain (ع)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf ''Ain (ع)',
    'Murid mengucapkan ''ain seperti hamzah, tanpa tekanan di tengah tenggorokan. Koreksinya?',
    'Minta murid mengucapkan ''ain lebih pelan tanpa menambah tekanan di tengah leher, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, ''ain dan hamzah boleh dibaca sama karena sama-sama dari tenggorokan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    '''ain keluar dari tengah tenggorokan dengan tekanan yang khas (seperti menahan sesuatu di leher lalu melepaskannya), beda dari hamzah yang dari pangkal tenggorokan dengan hentakan singkat',
    'Ganti ''ain dengan ha (ح) karena keduanya dianggap sama posisi keluarnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'C',
    '',
    1,
    true
  ),
(
    '5375d578-8704-45c0-a226-2fd762d0521f',
    'Sifatul Huruf',
    '''Ain (ع) - Tawassuth',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf ''Ain (ع) - Tawassuth',
    'Guru menjelaskan sifat jahr dan tawassuth pada ''ain. Penjelasan tepat?',
    '''Ain bersifat hams seperti ha (ح), sehingga tidak ada getaran pita suara, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    '''Ain bersifat jahr (bergetar) dan tawassuth (pertengahan antara tertahan penuh dan mengalir bebas), sehingga bunyinya tidak sekasar kha/ghain maupun sehalus ha/hamzah',
    'Sifat tawassuth pada ''ain berarti huruf ini boleh dibaca dengan cara apa saja, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    '''Ain termasuk huruf qalqalah karena posisinya di tenggorokan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    'edff44f9-44df-44b7-9308-07ad02cfed5a',
    'Makharijul Huruf',
    'Ghain (غ)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ghain (غ)',
    'Murid mengucapkan ghain tanpa getaran, terdengar seperti kha. Koreksinya?',
    'Biarkan saja, ghain dan kha boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan ghain lebih keras tanpa menambah getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti ghain dengan qaf karena keduanya dianggap sama-sama tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Ghain dari posisi sama dengan kha (pangkal lidah dekat tenggorokan atas), tapi ghain bersifat jahr (bergetar, mirip berkumur ringan) sedangkan kha hams (berhembus tanpa getar)',
    'D',
    '',
    1,
    true
  ),
(
    'd59ef03e-fbb3-4afa-b4f6-3cebe017d2b0',
    'Sifatul Huruf',
    'Ghain (غ) - Isti''la',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ghain (غ) - Isti''la',
    'Guru menjelaskan sifat isti''la pada ghain meski posisinya di tenggorokan (bukan lidah seperti huruf tebal lain). Penjelasan tepat?',
    'Sifat tebal pada ghain hanya muncul jika didahului harakat fathah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ghain termasuk huruf isti''la (tebal) meski keluar dari tenggorokan, karena pangkal lidah tetap terangkat tinggi saat mengucapkannya, mirip mekanisme huruf tebal lain seperti qaf',
    'Ghain bersifat istifal (tipis) karena letaknya di tenggorokan, bukan di lidah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ghain tidak memiliki sifat isti''la maupun istifal karena posisinya unik di tenggorokan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    '49f10cb1-22cd-4a5c-aec8-e404c4544e4e',
    'Makharijul Huruf',
    'Fa (ف)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Fa (ف)',
    'Murid mengucapkan fa dengan dua bibir rapat (posisi ba), bukan bibir bawah ke gigi atas. Koreksinya?',
    'Fa keluar dari bibir bawah bagian dalam yang menyentuh ujung gigi seri atas, bukan dari pertemuan dua bibir seperti ba. contohkan dan membandingkan langsung posisi keduanya',
    'Biarkan saja, fa boleh diucapkan dari dua bibir rapat selama bunyi akhirnya masih terdengar mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan fa lebih keras tanpa mengoreksi posisi bibir dan gigi, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti fa dengan wau karena keduanya dianggap dari posisi bibir yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'A',
    '',
    1,
    true
  ),
(
    '6b8110fc-6aa8-43c2-95ee-528c29c3715a',
    'Sifatul Huruf',
    'Fa (ف) - Hams Rakhawah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Fa (ف) - Hams Rakhawah',
    'Guru menjelaskan sifat hams dan rakhawah pada fa. Penjelasan tepat?',
    'Sifat hams pada fa hanya berlaku jika berharakat sukun, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Fa bersifat hams (berhembus) dan rakhawah (mengalir), sehingga bunyinya lembut berhembus, tidak tertahan penuh seperti huruf syiddah',
    'Fa bersifat jahr dan syiddah, sehingga bunyinya harus tertahan penuh dan bergetar, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Fa termasuk huruf qalqalah bersama ba karena sama-sama dari area bibir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    'c622f989-efc8-4363-9d5a-36ca4a5c49e7',
    'Makharijul Huruf',
    'Qaf (ق)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Qaf (ق)',
    'Murid mengucapkan qaf seperti kaf, kurang mundur ke belakang. Koreksinya?',
    'Minta murid mengucapkan qaf lebih pelan tanpa mendorong lidah lebih mundur, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, qaf dan kaf boleh dibaca sama karena sama-sama dari pangkal lidah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ganti qaf dengan ghain karena keduanya dianggap sama-sama tebal dan berat, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Qaf dari pangkal lidah paling belakang menempel langit-langit lunak paling dalam, lebih mundur dari kaf. latih dengan mendorong bunyi ''ka'' semakin ke belakang sampai terasa lebih berat',
    'D',
    '',
    1,
    true
  ),
(
    '3fe1d021-d9dc-422b-a3c4-7052e00aa1bd',
    'Sifatul Huruf',
    'Qaf (ق) - Isti''la+Qalqalah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Qaf (ق) - Isti''la+Qalqalah',
    'Guru menjelaskan sifat isti''la dan qalqalah pada qaf. Penjelasan tepat?',
    'Qaf memiliki sifat isti''la (tebal) sekaligus qalqalah (memantul saat mati), sehingga saat berharakat sukun harus dibaca tebal dan disertai pantulan ringan',
    'Qaf hanya bersifat isti''la, tidak termasuk salah satu huruf qalqalah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat qalqalah pada qaf hanya berlaku jika berada di awal kata, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Qaf bersifat istifal (tipis) karena posisinya paling belakang di antara huruf lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    '989320d6-dd0a-4f81-9f93-5dd070946743',
    'Makharijul Huruf',
    'Kaf (ك)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kaf (ك)',
    'Murid mengucapkan kaf terlalu mundur ke belakang, mendekati qaf. Koreksinya?',
    'Biarkan saja, kaf boleh diucapkan semundur qaf selama masih bisa dibedakan dari huruf lain, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Kaf dari pangkal lidah yang sedikit lebih maju dibanding qaf, sehingga bunyinya lebih ringan. jika terlalu mundur, bunyi kaf berubah menjadi berat seperti qaf',
    'Ganti kaf dengan ghain karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Minta murid mengucapkan kaf lebih keras tanpa mengoreksi posisi lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    'f0f147cc-5ca9-41fb-bd7c-1ffee7bb9c9f',
    'Sifatul Huruf',
    'Kaf (ك) vs Qaf',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kaf (ك) vs Qaf',
    'Guru menjelaskan sifat hams dan istifal pada kaf dibanding qaf yang jahr dan isti''la. Penjelasan tepat?',
    'Kaf termasuk huruf qalqalah bersama qaf karena posisinya berdekatan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Kaf bersifat hams (berhembus, tidak bergetar) dan istifal (tipis), berbeda dari qaf yang jahr (bergetar) dan isti''la (tebal), meski posisi keduanya berdekatan',
    'Kaf dan qaf memiliki sifat yang identik, hanya beda posisi keluarnya sedikit, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Kaf bersifat jahr seperti qaf, sehingga pita suara ikut bergetar penuh, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'B',
    '',
    1,
    true
  ),
(
    'e7b59c15-5ad7-4b39-97a8-6793f3e0d7b6',
    'Makharijul Huruf',
    'Lam (ل)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Lam (ل)',
    'Murid mengucapkan lam dengan getaran seperti ra. Koreksinya?',
    'Minta murid mengucapkan lam lebih pelan tanpa menghilangkan getarannya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti lam dengan nun karena keduanya dianggap sama-sama dari ujung lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Biarkan saja, lam dan ra boleh dibaca sama karena posisinya berdekatan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Lam keluar dari tepi lidah bagian depan menyentuh langit-langit dekat gigi atas, bunyinya harus jernih tanpa getaran, beda dari ra yang dari ujung lidah dengan getaran ringan',
    'D',
    '',
    1,
    true
  ),
(
    '5643d364-e5a9-403a-b7ae-fa39badf9b2e',
    'Sifatul Huruf',
    'Lam (ل) - Lafzul Jalalah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Lam (ل) - Lafzul Jalalah',
    'Guru menjelaskan mengapa lam pada lafzul jalalah bisa berubah tebal, padahal lam umumnya istifal. Penjelasan tepat?',
    'Lam pada dasarnya bersifat istifal (tipis) di semua kata, kecuali pengecualian khusus pada lafzul jalalah (lafaz Allah) yang didahului fathah atau dhommah, di mana ia dibaca tafkhim (tebal)',
    'Lam selalu bersifat isti''la (tebal) di semua kata tanpa terkecuali, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat tafkhim pada lam hanya berlaku untuk huruf lam yang bertasydid, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Lam berubah tebal jika berada di akhir ayat, bukan karena lafzul jalalah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    'afecb1c8-86e5-4fc8-a9e3-71c74d96a772',
    'Makharijul Huruf',
    'Mim (م)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Mim (م)',
    'Murid mengucapkan mim seperti ba, tanpa dengung dari hidung. Koreksinya?',
    'Minta murid mengucapkan mim lebih keras tanpa menambahkan dengung hidung, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti mim dengan wau karena keduanya dianggap dari posisi bibir yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Biarkan saja, mim dan ba boleh dibaca sama karena posisi bibirnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Mim keluar dari pertemuan dua bibir sama seperti ba, tapi bunyinya harus keluar dengan dengung melalui rongga hidung, beda dari ba yang bunyinya lepas dari mulut dengan hentakan',
    'D',
    '',
    1,
    true
  ),
(
    '8dd41ab9-80bf-477b-a31c-a160db1d7bea',
    'Sifatul Huruf',
    'Mim (م) - Ghunnah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Mim (م) - Ghunnah',
    'Guru menjelaskan sifat ghunnah yang menyertai mim dalam berbagai kondisi. Penjelasan tepat?',
    'Sifat ghunnah pada mim sama dengan sifat qalqalah pada huruf ba dan qaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Sifat ghunnah pada mim hanya muncul jika mim berada di awal kata, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Mim tidak memiliki sifat ghunnah, hanya nun yang memilikinya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Mim memiliki sifat ghunnah (dengung asli) yang selalu menyertainya, terutama menguat saat bertasydid atau bertemu huruf tertentu (seperti ikhfa syafawi dan idgham mimi)',
    'D',
    '',
    1,
    true
  ),
(
    'c606c49a-8e80-4ee2-b763-78c803663003',
    'Makharijul Huruf',
    'Nun (ن)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Nun (ن)',
    'Murid mengucapkan nun tanpa dengung, terdengar seperti lam. Koreksinya?',
    'Nun keluar dari ujung lidah menyentuh langit-langit dekat gigi atas (posisi mirip lam), tapi nun harus disertai dengung khas dari hidung, beda dari lam yang jernih tanpa dengung',
    'Ganti nun dengan ra karena keduanya dianggap sama-sama dari ujung lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Minta murid mengucapkan nun lebih keras tanpa menambahkan dengung, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Biarkan saja, nun dan lam boleh dibaca sama karena posisinya berdekatan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'A',
    '',
    1,
    true
  ),
(
    '21654fb9-49da-4894-95b2-e3b0c651e122',
    'Sifatul Huruf',
    'Nun (ن) - Ghunnah Bervariasi',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Nun (ن) - Ghunnah Bervariasi',
    'Guru menjelaskan sifat ghunnah pada nun yang berubah-ubah kadarnya tergantung hukum bacaan. Penjelasan tepat?',
    'Ghunnah pada nun kadarnya berbeda-beda tergantung hukum yang menyertainya, paling kuat saat idgham bighunnah dan ikhfa, sedang saat izhar hampir tidak ada dengung sama sekali karena dibaca jelas',
    'Ghunnah pada nun selalu sama kadarnya di semua kondisi tanpa terkecuali, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ghunnah pada nun hanya muncul jika nun berharakat sukun di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Nun tidak memiliki sifat ghunnah sama sekali, hanya mim yang memilikinya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'A',
    '',
    1,
    true
  ),
(
    '9e6f20cc-5508-4833-b031-a571a2f6b489',
    'Makharijul Huruf',
    'Wau (و)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Wau (و)',
    'Murid mengucapkan wau konsonan (berharakat) seperti fa, menyentuhkan bibir ke gigi. Koreksinya?',
    'Minta murid mengucapkan wau lebih keras tanpa mengoreksi posisi bibirnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti wau dengan mim karena keduanya dianggap sama-sama dari dua bibir, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Wau konsonan keluar dari dua bibir yang dibulatkan/dimonyongkan (bukan bibir ke gigi seperti fa). guru perlu membedakan wau konsonan (berharakat) dari wau sukun (huruf mad)',
    'Biarkan saja, wau boleh diucapkan dengan bibir ke gigi seperti fa selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'C',
    '',
    1,
    true
  ),
(
    'ffc10ca9-68a4-4a2d-944d-cad46e945b0a',
    'Sifatul Huruf',
    'Wau (و) - Dua Peran',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Wau (و) - Dua Peran',
    'Guru menjelaskan dua peran wau: sebagai huruf mad dan sebagai huruf konsonan (syafawi). Penjelasan tepat?',
    'Wau hanya berperan sebagai huruf konsonan, tidak pernah menjadi huruf mad, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Peran wau sebagai mad atau konsonan ditentukan oleh letaknya dalam kalimat, bukan oleh harakat atau sukunnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Wau punya dua peran berbeda, sebagai huruf mad ketika sukun didahului dhommah (mengalir tanpa titik tekan), dan sebagai huruf konsonan (syafawi) ketika berharakat dengan posisi bibir dibulatkan',
    'Wau hanya berperan sebagai huruf mad dalam segala kondisi, tidak pernah menjadi konsonan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'C',
    '',
    1,
    true
  ),
(
    'f6e7b222-8f73-4a54-9db3-251eac9eaed7',
    'Makharijul Huruf',
    'Ha besar (ه)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha besar (ه)',
    'Murid mengucapkan ha di akhir kata dengan sangat lemah, hampir tak terdengar. Koreksinya?',
    'Ha keluar dari pangkal tenggorokan paling dalam dengan hembusan napas yang jelas. meski berada di akhir kata, hembusannya tetap harus terdengar tegas, tidak boleh dilemahkan',
    'Ganti ha dengan hamzah karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Biarkan saja, ha di akhir kata memang boleh sangat lemah hampir tak terdengar, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Minta murid mengucapkan ha lebih cepat tanpa menambah hembusan napas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'A',
    '',
    1,
    true
  ),
(
    '389532a0-6de2-4ec4-acb3-aaa933749058',
    'Sifatul Huruf',
    'Ha besar (ه) - Hams Rakhawah',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha besar (ه) - Hams Rakhawah',
    'Guru menjelaskan sifat hams dan rakhawah pada ha yang membuatnya mudah lemah jika tak dilatih. Penjelasan tepat?',
    'Ha bersifat jahr dan syiddah, sehingga seharusnya mudah terdengar tegas tanpa perlu dilatih, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ha termasuk huruf qalqalah sehingga otomatis memantul saat berada di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Sifat lemahnya ha hanya terjadi jika didahului harakat dhommah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Ha bersifat hams (berhembus, tidak bergetar) dan rakhawah (mengalir), sehingga tanpa penekanan yang cukup, bunyinya sangat mudah melemah dan nyaris hilang terutama di akhir kata',
    'D',
    '',
    1,
    true
  ),
(
    '863b5176-6f10-425d-a55b-e551e05d04a5',
    'Makharijul Huruf',
    'Hamzah (ء)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Hamzah (ء)',
    'Murid mengucapkan hamzah dengan sangat halus, tanpa hentakan. Koreksinya?',
    'Minta murid mengucapkan hamzah lebih panjang tanpa menambah hentakan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti hamzah dengan alif karena keduanya dianggap huruf yang sama persis, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Hamzah keluar dari pangkal tenggorokan paling dalam dengan hentakan tegas (seperti bunyi ''terkejut''), berbeda dari alif yang mengalir tanpa hentakan sama sekali',
    'Biarkan saja, hamzah boleh diucapkan halus tanpa hentakan selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'C',
    '',
    1,
    true
  ),
(
    'f0630ad5-471f-4817-a899-739e415d0925',
    'Sifatul Huruf',
    'Hamzah (ء) - Syiddah Jahr',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Hamzah (ء) - Syiddah Jahr',
    'Guru menjelaskan sifat syiddah dan jahr pada hamzah. Penjelasan tepat?',
    'Hamzah bersifat syiddah (tertahan penuh sesaat sebelum dilepas) dan jahr (bergetar), menghasilkan hentakan tegas yang khas di pangkal tenggorokan',
    'Hamzah bersifat hams (berhembus tanpa getar), sehingga bunyinya seharusnya lembut, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Hamzah bersifat rakhawah (mengalir) sama seperti alif, sehingga tidak perlu hentakan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Sifat syiddah pada hamzah hanya berlaku jika berharakat kasrah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'A',
    '',
    1,
    true
  ),
(
    '794e7b44-1ff5-43bb-952e-1bfe975c11d1',
    'Makharijul Huruf',
    'Ya (ي)',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ya (ي)',
    'Murid mengucapkan ya konsonan (berharakat) seperti jim, ditekan di tengah lidah. Koreksinya?',
    'Biarkan saja, ya konsonan boleh diucapkan seperti jim selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'Ya konsonan keluar dari tengah lidah menyentuh langit-langit tengah (posisi mirip jim), tapi ya harus ringan mengalir, tidak ditekan tertahan seperti jim yang bersifat syiddah',
    'Minta murid mengucapkan ya lebih keras tanpa mengoreksi tekanan lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ganti ya dengan syin karena keduanya dianggap sama-sama dari tengah lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'B',
    '',
    1,
    true
  ),
(
    '304b7486-cf85-4cef-8439-fb19c1c22d12',
    'Sifatul Huruf',
    'Ya (ي) - Dua Peran',
    'Kasus',
    'C4',
    'Sedang',
    'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ya (ي) - Dua Peran',
    'Guru menjelaskan dua peran ya: sebagai huruf mad dan sebagai huruf konsonan. Penjelasan tepat?',
    'Ya punya dua peran berbeda, sebagai huruf mad ketika sukun didahului kasrah (mengalir tanpa tekanan), dan sebagai huruf konsonan ketika berharakat dengan tekanan ringan di tengah lidah',
    'Peran ya sebagai mad atau konsonan ditentukan oleh urutannya dalam kata, bukan oleh harakat atau sukunnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
    'Ya hanya berperan sebagai huruf konsonan, tidak pernah menjadi huruf mad, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
    'Ya hanya berperan sebagai huruf mad dalam segala kondisi, tidak pernah menjadi konsonan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
    'A',
    '',
    1,
    true
  );