INSERT INTO public.bank_soal (id, kategori, sub_aspek, tipe_soal, level_kognitif, tingkat_kesulitan, indikator_kompetensi, soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, pembahasan, bobot, aktif) VALUES
(
      '5643d364-e5a9-403a-b7ae-fa39badf9b2e',
      'Sifatul Huruf',
      'Lam (ل) - Lafzul Jalalah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Lam (ل) - Lafzul Jalalah',
      'Guru menjelaskan mengapa lam pada lafzul jalalah bisa berubah tebal, padahal lam umumnya istifal. Penjelasan tepat?',
      'Lam pada dasarnya bersifat istifal (tipis) di semua kata, kecuali pengecualian khusus pada lafzul jalalah (lafaz Allah) yang didahului fathah atau dhommah, di mana ia dibaca tafkhim (tebal)',
      'Lam selalu bersifat isti''la (tebal) di semua kata tanpa terkecuali, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat tafkhim pada lam hanya berlaku untuk huruf lam yang bertasydid, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Lam berubah tebal jika berada di akhir ayat, bukan karena lafzul jalalah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      'afecb1c8-86e5-4fc8-a9e3-71c74d96a772',
      'Makharijul Huruf',
      'Mim (م)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Mim (م)',
      'Murid mengucapkan mim seperti ba, tanpa dengung dari hidung. Koreksinya?',
      'Minta murid mengucapkan mim lebih keras tanpa menambahkan dengung hidung, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti mim dengan wau karena keduanya dianggap dari posisi bibir yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Biarkan saja, mim dan ba boleh dibaca sama karena posisi bibirnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Mim keluar dari pertemuan dua bibir sama seperti ba, tapi bunyinya harus keluar dengan dengung melalui rongga hidung, beda dari ba yang bunyinya lepas dari mulut dengan hentakan',
      'D',
      '',
      1,
      true
    ),
(
      '8dd41ab9-80bf-477b-a31c-a160db1d7bea',
      'Sifatul Huruf',
      'Mim (م) - Ghunnah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Mim (م) - Ghunnah',
      'Guru menjelaskan sifat ghunnah yang menyertai mim dalam berbagai kondisi. Penjelasan tepat?',
      'Sifat ghunnah pada mim sama dengan sifat qalqalah pada huruf ba dan qaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Sifat ghunnah pada mim hanya muncul jika mim berada di awal kata, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Mim tidak memiliki sifat ghunnah, hanya nun yang memilikinya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Mim memiliki sifat ghunnah (dengung asli) yang selalu menyertainya, terutama menguat saat bertasydid atau bertemu huruf tertentu (seperti ikhfa syafawi dan idgham mimi)',
      'D',
      '',
      1,
      true
    ),
(
      'c606c49a-8e80-4ee2-b763-78c803663003',
      'Makharijul Huruf',
      'Nun (ن)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Nun (ن)',
      'Murid mengucapkan nun tanpa dengung, terdengar seperti lam. Koreksinya?',
      'Nun keluar dari ujung lidah menyentuh langit-langit dekat gigi atas (posisi mirip lam), tapi nun harus disertai dengung khas dari hidung, beda dari lam yang jernih tanpa dengung',
      'Ganti nun dengan ra karena keduanya dianggap sama-sama dari ujung lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Minta murid mengucapkan nun lebih keras tanpa menambahkan dengung, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, nun dan lam boleh dibaca sama karena posisinya berdekatan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'A',
      '',
      1,
      true
    ),
(
      '21654fb9-49da-4894-95b2-e3b0c651e122',
      'Sifatul Huruf',
      'Nun (ن) - Ghunnah Bervariasi',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Nun (ن) - Ghunnah Bervariasi',
      'Guru menjelaskan sifat ghunnah pada nun yang berubah-ubah kadarnya tergantung hukum bacaan. Penjelasan tepat?',
      'Ghunnah pada nun kadarnya berbeda-beda tergantung hukum yang menyertainya, paling kuat saat idgham bighunnah dan ikhfa, sedang saat izhar hampir tidak ada dengung sama sekali karena dibaca jelas',
      'Ghunnah pada nun selalu sama kadarnya di semua kondisi tanpa terkecuali, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ghunnah pada nun hanya muncul jika nun berharakat sukun di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Nun tidak memiliki sifat ghunnah sama sekali, hanya mim yang memilikinya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'A',
      '',
      1,
      true
    ),
(
      '9e6f20cc-5508-4833-b031-a571a2f6b489',
      'Makharijul Huruf',
      'Wau (و)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Wau (و)',
      'Murid mengucapkan wau konsonan (berharakat) seperti fa, menyentuhkan bibir ke gigi. Koreksinya?',
      'Minta murid mengucapkan wau lebih keras tanpa mengoreksi posisi bibirnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti wau dengan mim karena keduanya dianggap sama-sama dari dua bibir, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Wau konsonan keluar dari dua bibir yang dibulatkan/dimonyongkan (bukan bibir ke gigi seperti fa). guru perlu membedakan wau konsonan (berharakat) dari wau sukun (huruf mad)',
      'Biarkan saja, wau boleh diucapkan dengan bibir ke gigi seperti fa selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'C',
      '',
      1,
      true
    ),
(
      'ffc10ca9-68a4-4a2d-944d-cad46e945b0a',
      'Sifatul Huruf',
      'Wau (و) - Dua Peran',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Wau (و) - Dua Peran',
      'Guru menjelaskan dua peran wau: sebagai huruf mad dan sebagai huruf konsonan (syafawi). Penjelasan tepat?',
      'Wau hanya berperan sebagai huruf konsonan, tidak pernah menjadi huruf mad, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Peran wau sebagai mad atau konsonan ditentukan oleh letaknya dalam kalimat, bukan oleh harakat atau sukunnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Wau punya dua peran berbeda, sebagai huruf mad ketika sukun didahului dhommah (mengalir tanpa titik tekan), dan sebagai huruf konsonan (syafawi) ketika berharakat dengan posisi bibir dibulatkan',
      'Wau hanya berperan sebagai huruf mad dalam segala kondisi, tidak pernah menjadi konsonan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'C',
      '',
      1,
      true
    ),
(
      'f6e7b222-8f73-4a54-9db3-251eac9eaed7',
      'Makharijul Huruf',
      'Ha besar (ه)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha besar (ه)',
      'Murid mengucapkan ha di akhir kata dengan sangat lemah, hampir tak terdengar. Koreksinya?',
      'Ha keluar dari pangkal tenggorokan paling dalam dengan hembusan napas yang jelas. meski berada di akhir kata, hembusannya tetap harus terdengar tegas, tidak boleh dilemahkan',
      'Ganti ha dengan hamzah karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Biarkan saja, ha di akhir kata memang boleh sangat lemah hampir tak terdengar, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan ha lebih cepat tanpa menambah hembusan napas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      '389532a0-6de2-4ec4-acb3-aaa933749058',
      'Sifatul Huruf',
      'Ha besar (ه) - Hams Rakhawah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha besar (ه) - Hams Rakhawah',
      'Guru menjelaskan sifat hams dan rakhawah pada ha yang membuatnya mudah lemah jika tak dilatih. Penjelasan tepat?',
      'Ha bersifat jahr dan syiddah, sehingga seharusnya mudah terdengar tegas tanpa perlu dilatih, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ha termasuk huruf qalqalah sehingga otomatis memantul saat berada di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Sifat lemahnya ha hanya terjadi jika didahului harakat dhommah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Ha bersifat hams (berhembus, tidak bergetar) dan rakhawah (mengalir), sehingga tanpa penekanan yang cukup, bunyinya sangat mudah melemah dan nyaris hilang terutama di akhir kata',
      'D',
      '',
      1,
      true
    ),
(
      '863b5176-6f10-425d-a55b-e551e05d04a5',
      'Makharijul Huruf',
      'Hamzah (ء)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Hamzah (ء)',
      'Murid mengucapkan hamzah dengan sangat halus, tanpa hentakan. Koreksinya?',
      'Minta murid mengucapkan hamzah lebih panjang tanpa menambah hentakan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti hamzah dengan alif karena keduanya dianggap huruf yang sama persis, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Hamzah keluar dari pangkal tenggorokan paling dalam dengan hentakan tegas (seperti bunyi ''terkejut''), berbeda dari alif yang mengalir tanpa hentakan sama sekali',
      'Biarkan saja, hamzah boleh diucapkan halus tanpa hentakan selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'C',
      '',
      1,
      true
    ),
(
      'f0630ad5-471f-4817-a899-739e415d0925',
      'Sifatul Huruf',
      'Hamzah (ء) - Syiddah Jahr',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Hamzah (ء) - Syiddah Jahr',
      'Guru menjelaskan sifat syiddah dan jahr pada hamzah. Penjelasan tepat?',
      'Hamzah bersifat syiddah (tertahan penuh sesaat sebelum dilepas) dan jahr (bergetar), menghasilkan hentakan tegas yang khas di pangkal tenggorokan',
      'Hamzah bersifat hams (berhembus tanpa getar), sehingga bunyinya seharusnya lembut, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Hamzah bersifat rakhawah (mengalir) sama seperti alif, sehingga tidak perlu hentakan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat syiddah pada hamzah hanya berlaku jika berharakat kasrah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'A',
      '',
      1,
      true
    ),
(
      '794e7b44-1ff5-43bb-952e-1bfe975c11d1',
      'Makharijul Huruf',
      'Ya (ي)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ya (ي)',
      'Murid mengucapkan ya konsonan (berharakat) seperti jim, ditekan di tengah lidah. Koreksinya?',
      'Biarkan saja, ya konsonan boleh diucapkan seperti jim selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ya konsonan keluar dari tengah lidah menyentuh langit-langit tengah (posisi mirip jim), tapi ya harus ringan mengalir, tidak ditekan tertahan seperti jim yang bersifat syiddah',
      'Minta murid mengucapkan ya lebih keras tanpa mengoreksi tekanan lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti ya dengan syin karena keduanya dianggap sama-sama dari tengah lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    ),
(
      '304b7486-cf85-4cef-8439-fb19c1c22d12',
      'Sifatul Huruf',
      'Ya (ي) - Dua Peran',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ya (ي) - Dua Peran',
      'Guru menjelaskan dua peran ya: sebagai huruf mad dan sebagai huruf konsonan. Penjelasan tepat?',
      'Ya punya dua peran berbeda, sebagai huruf mad ketika sukun didahului kasrah (mengalir tanpa tekanan), dan sebagai huruf konsonan ketika berharakat dengan tekanan ringan di tengah lidah',
      'Peran ya sebagai mad atau konsonan ditentukan oleh urutannya dalam kata, bukan oleh harakat atau sukunnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Ya hanya berperan sebagai huruf konsonan, tidak pernah menjadi huruf mad, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ya hanya berperan sebagai huruf mad dalam segala kondisi, tidak pernah menjadi konsonan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'A',
      '',
      1,
      true
    );