INSERT INTO public.bank_soal (id, kategori, sub_aspek, tipe_soal, level_kognitif, tingkat_kesulitan, indikator_kompetensi, soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, pembahasan, bobot, aktif) VALUES
(
      '87362681-7347-426e-9d47-bb556df92303',
      'Makharijul Huruf',
      'Alif (ا)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Alif (ا)',
      'Murid membaca huruf alif yang berharakat sukun di tengah kata seolah ada hentakan/penekanan tertentu, padahal alif seharusnya mengalir tanpa titik tekan di mulut atau tenggorokan mana pun. Bagaimana guru menjelaskan hal ini?',
      'Minta murid mengucapkan alif dengan menutup sedikit rongga tenggorokan agar bunyinya lebih tegas dan mudah dibedakan dari hamzah',
      'Jelaskan bahwa alif sukun harus selalu diberi tekanan ringan di ujung lidah agar terdengar jelas dan tidak tertukar huruf lain',
      'Jelaskan bahwa alif sukun sebenarnya keluar dari pangkal tenggorokan seperti hamzah, sehingga hentakan tersebut sudah benar dan tidak perlu dikoreksi',
      'Alif termasuk huruf mad yang tidak memiliki titik keluar tertentu di rongga mulut/tenggorokan, bunyinya mengalir bebas lewat rongga, tidak boleh dihentak seperti huruf konsonan lain',
      'D',
      '',
      1,
      true
    ),
(
      'a31fa540-007d-40e4-951d-cdb0501875b5',
      'Sifatul Huruf',
      'Alif vs Hamzah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Alif vs Hamzah',
      'Seorang murid selalu memperlakukan alif seperti hamzah — setiap ada alif, ia mengucapkannya dengan hentakan glotal tegas. Apa penjelasan paling tepat untuk meluruskannya?',
      'Jelaskan bahwa perbedaan alif-hamzah hanya berlaku dalam penulisan, bukan pengucapan, sehingga keduanya boleh dibaca sama',
      'Jelaskan bahwa alif dan hamzah adalah huruf yang sama persis, sehingga cara membaca murid tersebut sudah benar',
      'Alif dan hamzah memang berbeda huruf, hamzah punya makhraj tegas di pangkal tenggorokan dengan hentakan, sedangkan alif murni huruf mad yang mengalir tanpa hentakan sama sekali',
      'Minta murid berhenti membedakan alif dan hamzah karena topik ini terlalu rumit untuk tahap belajar saat ini, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '5107be44-6466-47fc-8553-df9ab31290f4',
      'Makharijul Huruf',
      'Ba (ب)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ba (ب)',
      'Murid mengucapkan ba dengan menyentuhkan bibir bawah ke gigi atas (posisi fa), bukan mempertemukan dua bibir. Bunyinya jadi samar antara ba dan fa. Koreksinya?',
      'Contohkan posisi benar: pertemukan kedua bibir hingga rapat, lepas dengan hentakan untuk bunyi ba, bandingkan dengan posisi fa yang pakai gigi',
      'Biarkan saja, selama bunyi akhirnya masih terdengar mirip ba, posisi bibir tidak terlalu berpengaruh pada makna',
      'Suruh murid mengucapkan ba lebih keras tanpa mengoreksi posisi bibirnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti huruf ba dengan mim untuk sementara karena keduanya dari bibir dan dianggap lebih mudah dibedakan dari fa',
      'A',
      '',
      1,
      true
    ),
(
      'e001ddfb-1a84-48ac-9161-0349dc7215fb',
      'Sifatul Huruf',
      'Ba (ب) - Qalqalah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ba (ب) - Qalqalah',
      'Murid membaca kata berakhiran ba mati saat waqaf, tapi dibaca datar tanpa pantulan sama sekali. Koreksinya?',
      'Minta murid mengulang dengan suara lebih keras agar pantulannya muncul otomatis, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, pantulan hanya berlaku untuk qaf dan tha, bukan ba yang tergolong huruf bibir, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ba termasuk salah satu dari lima huruf qalqalah (bersama qaf, tha, jim, dal), sehingga saat mati harus dibaca dengan pantulan ringan',
      'Jelaskan bahwa pantulan pada ba hanya berlaku di awal kata, bukan saat di akhir kata ketika waqaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '4f36cad4-0840-434e-8ffd-f36fd88a317a',
      'Sifatul Huruf',
      'Ta (ت)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ta (ت)',
      'Murid mengucapkan ta dengan bunyi sangat tertahan dan berat, mendekati tha, padahal ta seharusnya berhembus ringan. Koreksinya?',
      'Suruh murid menahan napas sepenuhnya saat mengucapkan ta agar terdengar lebih tegas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, ta dan tha sama persis dalam ketebalan bunyi, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ta termasuk huruf hams, hembusan napas ikut keluar, tidak boleh ditekan berat seperti tha yang tebal. contohkan bunyi ta yang ringan berhembus',
      'Ganti huruf ta dengan dal karena makhrajnya sama dan dianggap lebih mudah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '87124f96-101d-40fb-9bf3-e0411ffcfb6a',
      'Sifatul Huruf',
      'Ta (ت) bukan Qalqalah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ta (ت) bukan Qalqalah',
      'Guru baru menduga ta termasuk huruf qalqalah karena sering dengar muridnya memantulkan ta mati. Penjelasan tepat?',
      'Ta termasuk qalqalah hanya jika di akhir kata, tidak jika di tengah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Benar, ta termasuk qalqalah karena posisinya berdekatan dengan dal dan tha, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ta bukan huruf qalqalah. hanya lima huruf tertentu (ba-jim-dal-tha-qaf) yang dipantulkan, sehingga kebiasaan memantulkan ta mati perlu dikoreksi jadi bacaan datar',
      'Semua huruf dari ujung lidah termasuk qalqalah, termasuk ta, dal, dan tha, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '8db037bb-5432-43bf-8921-850ea059b8b7',
      'Makharijul Huruf',
      'Tsa (ث)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tsa (ث)',
      'Murid menempelkan ujung lidah rapat ke gigi seri (bukan menyentuh ringan) saat mengucapkan tsa, sehingga bunyinya tertahan seperti ta. Koreksinya?',
      'Ganti huruf tsa dengan sin karena bunyi desisnya mirip dan dianggap lebih mudah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Tsa termasuk huruf rakhawah (mengalir, tidak tertahan) sehingga ujung lidah cukup disentuhkan ringan ke gigi seri atas, membiarkan udara tetap mengalir',
      'Biarkan saja, tsa dan ta boleh dibaca sama selama maknanya masih bisa dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid menekan lidahnya lebih kuat lagi ke gigi seri agar bunyi tsa lebih jelas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      '07c5ffc6-0cf6-4864-9915-2216ec1e83a3',
      'Sifatul Huruf',
      'Tsa (ث)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tsa (ث)',
      'Guru ingin menjelaskan mengapa tsa terdengar berhembus khas dibanding huruf berdekatan seperti dal/ta. Penjelasan tepat?',
      'Karena tsa punya tanda baca khusus di mushaf yang mewajibkan hembusan tambahan sebagai simbol kehati-hatian, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Karena tsa adalah huruf tersulit di antara semua huruf hijaiyah sehingga otomatis berhembus, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Karena tsa berasal dari makhraj yang sama dengan kha yang juga berhembus akibat posisi di tenggorokan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Karena tsa termasuk huruf hams, sehingga pita suara tidak tertahan penuh dan udara ikut keluar bersama bunyinya',
      'D',
      '',
      1,
      true
    ),
(
      '46d7eec3-1633-4149-b509-255e594a95ac',
      'Makharijul Huruf',
      'Jim (ج)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Jim (ج)',
      'Murid mengucapkan jim dengan posisi lidah terlalu maju ke depan, mendekati dal, sehingga bunyinya kurang jelas sebagai jim. Koreksinya?',
      'Biarkan saja, jim dan dal cukup mirip dan tidak terlalu berpengaruh pada makna, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti huruf jim dengan ya karena sama-sama dari tengah lidah dan dianggap lebih mudah dibedakan dari dal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Jim keluar dari tengah lidah menyentuh langit-langit tengah (bukan ujung lidah ke gigi seperti dal), contohkan posisi mengangkat bagian tengah lidah',
      'Minta murid mengucapkan jim lebih keras tanpa mengubah posisi lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'C',
      '',
      1,
      true
    ),
(
      '6a26017b-8a2e-43d6-9c59-44daf2a3ad27',
      'Sifatul Huruf',
      'Jim (ج) Syiddah+Qalqalah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Jim (ج) Syiddah+Qalqalah',
      'Murid membaca kata berakhiran jim mati saat waqaf dengan bunyi sangat datar dan lembek, tanpa ketegasan maupun pantulan. Koreksinya, mengingat jim punya dua sifat sekaligus?',
      'Biarkan saja, jim yang dibaca lembek dan datar masih bisa diterima selama murid tahu artinya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti bacaan jim mati tersebut dengan bunyi ya agar lebih mudah diucapkan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Jim adalah huruf syiddah (tertahan penuh) sekaligus huruf qalqalah, sehingga saat mati harus dibaca dengan ketegasan tertahan disertai pantulan ringan',
      'Jelaskan bahwa jim hanya perlu dibaca tegas tanpa pantulan, karena sifat qalqalah tidak berlaku untuk huruf tengah lidah',
      'C',
      '',
      1,
      true
    ),
(
      '250bbef3-62bf-4db6-8e9d-ee9929787b13',
      'Makharijul Huruf',
      'Ha kecil (ح)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha kecil (ح)',
      'Murid mengucapkan ha (ح) dengan posisi terlalu dalam di tenggorokan, mendekati kha, sehingga terdengar lebih kasar. Koreksinya?',
      'Minta murid menekan tenggorokannya lebih dalam lagi agar bunyi ha lebih tegas, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, ha dan kha boleh dibaca sama selama maknanya masih bisa dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti huruf ha dengan hamzah karena sama-sama dari tenggorokan dan dianggap lebih mudah dibedakan dari kha, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Ha (ح) keluar dari tengah tenggorokan dengan hembusan halus dan lembut, beda dari kha yang lebih dekat ke mulut dengan bunyi berdesir kasar',
      'D',
      '',
      1,
      true
    ),
(
      '32500e4a-1a17-4c2e-9c1e-2d48ed14e04c',
      'Sifatul Huruf',
      'Ha kecil (ح)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ha kecil (ح)',
      'Guru ingin menjelaskan mengapa ha (ح) tidak boleh dibaca tertahan penuh seperti jim, meski posisinya berdekatan. Penjelasan tepat?',
      'Karena ha (ح) sebenarnya termasuk huruf syiddah sama seperti jim, sehingga seharusnya juga dibaca tertahan penuh',
      'Karena ha (ح) termasuk huruf hams dan rakhawah, bunyinya mengalir disertai hembusan napas, tidak tertahan penuh seperti jim yang syiddah',
      'Karena ha (ح) tidak memiliki sifat khusus apa pun, boleh dibaca dengan cara apa saja, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Karena ha (ح) hanya digunakan pada kata-kata jarang muncul, sifatnya tak perlu terlalu diperhatikan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    ),
(
      '5ec36ad5-975a-4fc8-a7e2-d05031568246',
      'Makharijul Huruf',
      'Kha (خ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kha (خ)',
      'Murid mengucapkan kha dengan posisi terlalu maju ke arah ha (ح), sehingga bunyi hembusan kasarnya hilang. Koreksinya?',
      'Biarkan saja, kha dan ha (ح) boleh dibaca sama karena sama-sama dari tenggorokan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan kha lebih pelan tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti kha dengan ghain karena keduanya dianggap sama persis dari segi makhraj dan sifat, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Kha keluar dari pangkal lidah bagian belakang mendekati anak tekak, berbeda dari ha (ح) yang lebih dalam dan halus. contohkan hembusan kasar berdesir',
      'D',
      '',
      1,
      true
    ),
(
      '341a6f19-9ed2-495d-92bd-bfe1a5c2d2b8',
      'Sifatul Huruf',
      'Kha (خ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kha (خ)',
      'Guru menjelaskan mengapa kha selalu terdengar ''berdesir'' dibanding huruf tenggorokan lain. Penjelasan tepat?',
      'Karena kha adalah huruf paling berat dalam bahasa Arab sehingga otomatis berdesir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Karena kha termasuk huruf hams dan rakhawah, sehingga udara ikut mengalir keluar bersama bunyinya, menghasilkan desiran khas. beda dari huruf syiddah yang tertahan',
      'Karena kha memiliki tanda baca khusus yang mewajibkan desiran tambahan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Karena kha termasuk huruf qalqalah yang selalu dipantulkan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'B',
      '',
      1,
      true
    ),
(
      '5beadba3-2cf1-441f-bfa3-e88d03cd97e1',
      'Makharijul Huruf',
      'Dal (د)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dal (د)',
      'Murid mengucapkan dal dengan lidah terlalu ke belakang, mendekati posisi ta/tha. Koreksinya?',
      'Dal keluar dari ujung lidah menyentuh pangkal gigi seri atas (sama seperti ta/tho tapi beda sifat), harus ditekan tegas lalu dilepas',
      'Ganti dal dengan tha karena keduanya dianggap sama persis, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, dal boleh dibaca dari posisi mana saja selama bunyi akhirnya mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid membaca dal lebih pelan tanpa mengoreksi posisi lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'A',
      '',
      1,
      true
    );