BEGIN;

INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ABDURROHMAN AL-FATIH', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ADNAN ARDHANI GINTING', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ADSKHAN SYAFIQ', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ADZRIEL ALFAKHRI POHAN', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AFIF MAKARIM', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('GAISHAN RAFFASYA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HAMZAH', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('IRSYAD ZAVIYAR', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('IZZAN SYAH SYAZWAN SIANIPAR', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KHAIRIL ALFATH AMIQ', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KHALID BIN KHAIRIL', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('M. GILANG ARSYA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('M.SHAKIEL EVANO MEKKA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MALIK TAMCHLIS ZEN', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MHD ATHA SHAHEER NASUTION', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MHD REZKY MAULANA SITEPU', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUDZAKKIR ALKAHFI', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD AL-HAFIDZH NST', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NAQEEB ATHALLAH NARAYA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NAUFAL ALIF AL MIRZHA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RAFASYA AL FARIQ', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RAFFASYA AQIL GHAISAN', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RAFIQ SHAHDAN', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SHADIQ AULIA TARIGAN', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SHAFIQ AMMAR BATUBARA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('UKASYAH WIYANDHA', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('UWAIS AHMAD SYAUQI', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('YAHYA AL MUFLIH', 1, 'A', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AHMAD ABIDZAR ALFARIZKI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AHMAD AL HABIB', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ALBANI PANDIA', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ALHANAN ZADA UUSRIZAL', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AMMAR IBRAHIM RAMADHAN', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ANAS AL-BARRA HIDAYAT', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ARSYAD AL MUQAFFI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('FARHAN MUFLIH QODFI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HABIB MUHAMMAD FATIH AL-HAKIM', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HAMZAH MUSTAQIM SIREGAR', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('IBRAHIM EL HAZIQ', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('IHSAN TSANI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD AZKA XAVIER', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD FAROOQ RIZKI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD FARUQ NUFAIL', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD FATIH KARIM', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD KHABIB', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUHAMMAD UKKASYAH', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NU''MAN SYAKIR PANJAITAN', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('QEANU ARRAFIQ AKBAR', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RISYAD ALFARIZI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RUNAKO ARSENIO MUBARAK SIAGIAN', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SYAFIQ HANIF BUKHARI LUBIS', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('TSAQIF AYYASY AWWABIN', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('UWAIS NAL MAIDANY', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('UWAIS SYEHAN AL-QARNI', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ZHAFRAN HAMIZAN', 1, 'B', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ABIDAH HANIYAH KHOIRUNNISA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('Aisyah Abdul Azis', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ALLETA KHAWLA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ALMEERA RATIFAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ALMIRA HUMAIRA BATRISYA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AMEERA CHAIRUNISA TSABITA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('DEANDRA ADILLA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ELIF KHAULAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HAFSHAH NAZHIFA KHANSA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HAFSYAH MUJAHIDAH ALHANAN', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HAMNA LUTHFIA SYAM', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HANA HUMAIRAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('JIHAN SYAFIQAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KABSYAH HIBATILLAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KEYSHA FARA USYAN', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MAHDEYA SARAGIH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MARYAM YUNEDI', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MARZIA RAMADHANI', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NABILA SYAKIRA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NAILAH SHAFIYYAH LUBIS', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('PUTRI ARISHA JULIANTI', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SAJIDAH YUMNA', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SALWA MALAIKA SANI', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SARAH LUMBAN TOBING', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('UMAYZA ALMIRA MATONDANG', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('YASMIN ALLIFIYAH', 1, 'C', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ANINDYA MISHA SIREGAR', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ARSYILLA NUR MAFAZA HASIBUAN', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ASIYAH QURROTA A''YUN SEMBIRING', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AYRA RAFIZAH RIZQY', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('AZZAHRA ASYILA RAHMA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('FAHIRA HAURO JANNAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('GHAYDA NAFEEZA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HANIN SYAHIRA RAIHANA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HANNAH SYAFIQAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HASANAH INARAH ANWARI', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('HUMAIRAH PUTRI ALVIA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KHADIJAH AKBAR', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('KHODIJAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('LULU HUMAIRAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MAHIRAH AL-FALISHA BR BANGUN', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MIKAYLA ARYA HAFIQAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUTHI''AH AZZAHRA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('MUTIAH SHALEHA NASUTION', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NASHIFA TISA AFSEEN', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('NUWAIRAH KHANZAIRA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('RAIQA ZAFIRA ALEA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SHAFIYYAH SUBHI', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SHAFIYYAH SYAHIDAH', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('SYAURAH AGHINA BAHIRA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ZAHIRA PURNAMA BATUBARA', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');
INSERT INTO public.students (nama, kelas, rombel, level, halaman_terakhir, status_bacaan, status_siswa) VALUES ('ZIYANNISA HANIAH ABDURRAHIM', 1, 'D', 'Iqro 1', 0, 'Lancar', 'aktif');

COMMIT;
