INSERT INTO public.bank_soal (id, kategori, sub_aspek, tipe_soal, level_kognitif, tingkat_kesulitan, indikator_kompetensi, soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, pembahasan, bobot, aktif) VALUES
(
      '404524ab-ccb2-4b14-869f-18f9d4e98c9d',
      'Sifatul Huruf',
      'Dal (د)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dal (د)',
      'Guru menjelaskan sifat jahr pada dal dibanding ta yang hams. Penjelasan tepat?',
      'Dal bersifat qalqalah sekaligus hams, sehingga harus dipantulkan dengan hembusan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Dal bersifat jahr, pita suara bergetar penuh saat diucapkan, beda dari ta yang hams (berhembus, pita suara tidak bergetar penuh)',
      'Perbedaan dal dan ta hanya soal ketebalan tafkhim-tarqiq, bukan getaran pita suara, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Dal dan ta sama-sama hams sehingga tidak ada perbedaan getaran pita suara, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'B',
      '',
      1,
      true
    ),
(
      '647b0f51-9996-4e39-9895-5ee7fccd6923',
      'Makharijul Huruf',
      'Dzal (ذ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dzal (ذ)',
      'Murid mengucapkan dzal tanpa menjulurkan ujung lidah ke gigi, hanya dari dalam mulut. Koreksinya?',
      'Ganti dzal dengan za karena keduanya dianggap sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Dzal (bersama tsa dan zho) mengharuskan ujung lidah keluar sedikit menyentuh ujung gigi seri atas. jika lidah tidak keluar, bunyi dzal berubah mendekati za/da',
      'Minta murid mengucapkan dzal lebih keras tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, dzal boleh diucapkan tanpa menjulurkan lidah selama bunyi akhirnya masih mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'B',
      '',
      1,
      true
    ),
(
      'f7f6d8ac-d256-45be-897c-d73b32319593',
      'Sifatul Huruf',
      'Dzal (ذ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dzal (ذ)',
      'Guru menjelaskan kenapa dzal ringan dibanding zho yang tebal, meski posisi mirip. Penjelasan tepat?',
      'Karena dzal hanya muncul di kata-kata pendek sehingga terdengar ringan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Karena dzal dan zho sebenarnya sama tebalnya, hanya beda penulisan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Karena dzal termasuk huruf qalqalah sehingga otomatis ringan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Dzal bersifat istifal (tipis) karena lidah belakang tetap datar, beda dari zho yang lidah belakangnya terangkat membentuk gelombang sehingga tebal (isti''la)',
      'D',
      '',
      1,
      true
    ),
(
      'ef6c60a1-02ce-45c0-9c89-75f502b4943c',
      'Makharijul Huruf',
      'Ra (ر)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ra (ر)',
      'Murid mengucapkan ra tanpa getaran sama sekali, terdengar seperti lam. Koreksinya?',
      'Minta murid mengucapkan ra lebih pelan tanpa menambahkan getaran, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ra keluar dari ujung lidah dekat gusi atas dengan getaran ringan satu-dua kali. kalau getaran hilang sama sekali, bunyinya berubah mendekati lam yang jernih tanpa getar',
      'Biarkan saja, ra dan lam memang boleh dibaca sama dalam kondisi tertentu, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti ra dengan lam karena keduanya dianggap memiliki makhraj yang identik, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    ),
(
      '0b10e4ee-fa20-4f0d-a917-c689173cb993',
      'Sifatul Huruf',
      'Ra (ر) - Takrir',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ra (ر) - Takrir',
      'Guru menjelaskan sifat takrir (getaran/pengulangan) pada ra yang unik dibanding huruf lain. Penjelasan tepat?',
      'Sifat takrir berarti ra harus diulang pengucapannya dua kali secara terpisah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat takrir sama dengan sifat qalqalah yang dimiliki huruf ba dan qaf, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Sifat takrir hanya berlaku jika ra berada di awal kata, bukan di tengah atau akhir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ra memiliki sifat takrir, yaitu getaran ringan pada ujung lidah. namun getaran ini tidak boleh berlebihan (digulung panjang) karena akan terdengar dibuat-buat',
      'D',
      '',
      1,
      true
    ),
(
      'd2ed3adc-a5a7-4956-833c-fa610d50e7f1',
      'Sifatul Huruf',
      'Zai (ز)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zai (ز)',
      'Murid mengucapkan zai tanpa getaran pita suara, terdengar seperti sin. Koreksinya?',
      'Biarkan saja, zai dan sin boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan zai lebih keras tanpa mengoreksi getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Zai keluar dari posisi yang sama dengan sin (ujung lidah dekat gigi bawah), tapi zai bersifat jahr (bergetar) sedangkan sin hams (berhembus tanpa getar). pastikan pita suara ikut bergetar',
      'Ganti zai dengan shad karena dianggap lebih mudah dibedakan dari sin, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '11ab3925-ff9b-4527-807e-d2b9ad4869bd',
      'Sifatul Huruf',
      'Zai (ز)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zai (ز)',
      'Guru menjelaskan ketebalan relatif zai dibanding shad. Penjelasan tepat?',
      'Zai dan shad sama-sama tebal karena keduanya bersifat shafir, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Zai lebih tebal dari shad karena posisinya lebih dekat ke gigi bawah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Zai termasuk huruf istifal (tipis/ringan), berbeda dari shad yang isti''la (tebal), meski keduanya sama-sama huruf desis (shafir)',
      'Ketebalan zai bergantung pada harakat sebelumnya, sama seperti ra, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '06aaf07a-81dc-42db-9649-f87af7a56972',
      'Makharijul Huruf',
      'Sin (س)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Sin (س)',
      'Murid mengucapkan sin dengan ujung lidah menyentuh gigi (bukan mendekat saja), sehingga bunyi desisnya hilang. Koreksinya?',
      'Sin keluar dari ujung lidah yang didekatkan (bukan ditempelkan penuh) ke gigi seri bawah, menghasilkan celah kecil untuk desisan. jika ditempel penuh, desisan hilang dan berubah mendekati ta/tsa',
      'Ganti sin dengan tsa karena keduanya dianggap sama posisi keluarnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Biarkan saja, sin boleh diucapkan dengan lidah menempel penuh selama bunyi akhirnya masih terdengar mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan sin lebih keras tanpa mengubah jarak lidah dan gigi, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      'ed891dd0-1f1e-4741-afe4-477750d03763',
      'Sifatul Huruf',
      'Sin (س) - Shafir',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Sin (س) - Shafir',
      'Guru menjelaskan sifat shafir (desis) pada sin dibanding huruf lain yang mirip posisi. Penjelasan tepat?',
      'Sin memiliki sifat shafir (bunyi desis tajam seperti siulan kecil) bersama zai dan shad. desis ini muncul karena celah sempit antara lidah dan gigi yang dilewati udara',
      'Sifat shafir sama dengan sifat qalqalah yang menghasilkan pantulan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Sifat shafir hanya dimiliki sin seorang diri di antara semua huruf hijaiyah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat shafir muncul karena sin selalu berharakat kasrah dalam Al-Qur''an, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'A',
      '',
      1,
      true
    ),
(
      'caf22fa9-3b7c-4a4e-9323-f03e6249ed08',
      'Makharijul Huruf',
      'Syin (ش)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Syin (ش)',
      'Murid mengucapkan syin dengan desis sempit seperti sin, bukan desis lebar. Koreksinya?',
      'Minta murid mengucapkan syin lebih pelan tanpa mengubah posisi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Syin keluar dari tengah lidah menyentuh langit-langit tengah dengan desis yang menyebar lebar (tafasysyi), beda dari sin yang desisnya sempit dan tajam dari ujung lidah',
      'Biarkan saja, syin dan sin boleh dibaca sama karena sama-sama huruf desis, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti syin dengan jim karena keduanya dari tengah lidah dan dianggap sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    ),
(
      '2a2e7f52-3f17-4e88-9050-a3a38a6f7dfd',
      'Sifatul Huruf',
      'Syin (ش) - Tafasysyi',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Syin (ش) - Tafasysyi',
      'Guru menjelaskan sifat tafasysyi (menyebar) yang khas dimiliki syin. Penjelasan tepat?',
      'Syin memiliki sifat tafasysyi, yaitu udara menyebar luas di rongga mulut saat diucapkan, menghasilkan desis yang lebih lebar dibanding huruf desis lainnya seperti sin dan shad',
      'Sifat tafasysyi sama dengan sifat ghunnah yang dimiliki nun dan mim, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Sifat tafasysyi berarti syin harus diucapkan dua kali berturut-turut, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat tafasysyi hanya muncul jika syin berada di akhir kata, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      'ff9fa3d3-c7a6-42e6-aa18-810f2b0a7686',
      'Sifatul Huruf',
      'Shad (ص)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Shad (ص)',
      'Murid mengucapkan shad dengan bunyi tipis seperti sin, tidak menggembung. Koreksinya?',
      'Shad dari posisi yang sama dengan sin (ujung lidah dekat gigi bawah), tapi shad bersifat isti''la (tebal) sehingga lidah belakang terangkat dan rongga mulut terasa menggembung, beda dari sin yang tipis',
      'Biarkan saja, shad dan sin boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti shad dengan dhad karena keduanya dianggap sama-sama huruf tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Minta murid mengucapkan shad lebih keras tanpa mengangkat lidah belakang, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      '6f645ac9-052f-47f9-9fc3-6027fa1ab3b2',
      'Sifatul Huruf',
      'Shad (ص) - Ithbaq',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Shad (ص) - Ithbaq',
      'Guru menjelaskan mengapa shad memiliki sifat ithbaq selain isti''la. Penjelasan tepat?',
      'Sifat ithbaq berarti shad harus diucapkan dengan mulut tertutup rapat sepenuhnya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat ithbaq hanya berlaku untuk shad seorang diri di antara semua huruf isti''la, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Shad memiliki sifat ithbaq, yaitu bagian tengah lidah menempel rapat ke langit-langit atas (bersama dhad, tho, zho), menghasilkan bunyi yang lebih tebal dan penuh dibanding huruf isti''la lain yang tidak ithbaq seperti qaf, kha, ghain',
      'Sifat ithbaq sama dengan sifat qalqalah pada huruf ba dan qaf, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'C',
      '',
      1,
      true
    ),
(
      '8fd1a6f0-ad9b-40e0-bf5f-e15bdad543e6',
      'Makharijul Huruf',
      'Dhad (ض)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dhad (ض)',
      'Murid mengucapkan dhad dari ujung lidah, bukan tepi lidah. Koreksinya?',
      'Minta murid mengucapkan dhad lebih keras tanpa mengoreksi posisi tepi lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti dhad dengan dal karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Biarkan saja, dhad boleh diucapkan dari ujung lidah selama terdengar berat, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Dhad keluar dari salah satu atau kedua tepi lidah yang menyentuh gigi geraham atas, posisi paling unik di antara semua huruf, contohkan langsung sambil murid merasakan tepi lidahnya sendiri',
      'D',
      '',
      1,
      true
    ),
(
      '18389330-4e42-4718-875d-5f166a356d2e',
      'Sifatul Huruf',
      'Dhad (ض) - Kombinasi Sifat',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Dhad (ض) - Kombinasi Sifat',
      'Guru menjelaskan mengapa dhad dianggap huruf tersulit sifatnya di antara huruf hijaiyah. Penjelasan tepat?',
      'Dhad sulit karena termasuk huruf hams yang jarang dilatih, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Dhad menggabungkan banyak sifat sekaligus (isti''la, ithbaq, jahr, dan istithalah/memanjang di tepi lidah), sehingga kombinasi sifat inilah yang membuatnya sulit dan unik',
      'Dhad sulit karena hanya muncul satu kali dalam seluruh Al-Qur''an, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Dhad sulit hanya karena bentuk tulisannya rumit, bukan karena sifat pengucapannya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    );