INSERT INTO public.bank_soal (id, kategori, sub_aspek, tipe_soal, level_kognitif, tingkat_kesulitan, indikator_kompetensi, soal, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar, pembahasan, bobot, aktif) VALUES
(
      'fb9ea2d3-0952-46f0-82e3-12d73ded6476',
      'Makharijul Huruf',
      'Tho (ط)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tho (ط)',
      'Murid mengucapkan tho tanpa penekanan, terdengar seperti ta. Koreksinya?',
      'Ganti tho dengan dal karena keduanya dianggap sama-sama jahr, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Minta murid mengucapkan tho lebih cepat tanpa menambah tekanan lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, tho dan ta boleh dibaca sama selama maknanya dipahami, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Tho dari posisi sama dengan ta (ujung lidah ke pangkal gigi seri atas), tapi tho bersifat isti''la dan ithbaq sehingga ditekan lebih kuat dan rongga mulut terasa membulat',
      'D',
      '',
      1,
      true
    ),
(
      '2351c1f6-61d6-46e5-a98b-9ff14a09903d',
      'Sifatul Huruf',
      'Tho (ط) - Empat Sifat',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Tho (ط) - Empat Sifat',
      'Guru menjelaskan kombinasi sifat pada tho (isti''la + ithbaq + jahr + qalqalah). Penjelasan tepat?',
      'Tho hanya memiliki sifat isti''la saja, sifat lain miliknya sama seperti ta biasa, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Tho adalah satu-satunya huruf yang punya empat sifat sekaligus (isti''la, ithbaq, jahr, dan qalqalah), sehingga bunyinya tebal, menggembung, bergetar, dan memantul saat mati',
      'Tho bersifat hams seperti ta, sehingga tidak ada getaran pita suara, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Tho tidak termasuk huruf qalqalah karena posisi keluarnya sama dengan ta, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      '7b2cafbf-f0aa-4ad5-a633-cdecdc7c7428',
      'Makharijul Huruf',
      'Zho (ظ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zho (ظ)',
      'Murid mengucapkan zho tanpa mengangkat lidah belakang, terdengar seperti dza. Koreksinya?',
      'Zho dari posisi sama dengan dza (ujung lidah digigit ringan di gigi depan), tapi lidah belakang harus naik membentuk gelombang agar bunyi tebal, beda dari dza yang lidah belakangnya tetap datar',
      'Ganti zho dengan tho karena keduanya dianggap sama-sama tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Minta murid menggigit lidahnya lebih keras tanpa mengangkat lidah belakang, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, zho dan dza boleh dibaca sama karena posisi gigitannya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'A',
      '',
      1,
      true
    ),
(
      '46dd0fe5-f544-4cf8-a0e2-f46dea972b43',
      'Sifatul Huruf',
      'Zho (ظ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Zho (ظ)',
      'Guru menjelaskan kombinasi sifat zho (isti''la + ithbaq + jahr) dibanding dza. Penjelasan tepat?',
      'Zho bersifat hams seperti tsa, sehingga tidak ada getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Zho termasuk huruf qalqalah bersama dza dan tsa, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Zho memiliki sifat isti''la dan ithbaq (tebal dan menggembung) serta jahr (bergetar), sedangkan dza hanya istifal (tipis) meski keduanya sama-sama jahr dan posisi gigitannya sama',
      'Zho dan dza memiliki sifat yang identik, hanya beda pada penulisan hurufnya, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'C',
      '',
      1,
      true
    ),
(
      '321dec3d-dd16-4bbb-b274-7c61a65f8a1e',
      'Makharijul Huruf',
      '''Ain (ع)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf ''Ain (ع)',
      'Murid mengucapkan ''ain seperti hamzah, tanpa tekanan di tengah tenggorokan. Koreksinya?',
      'Minta murid mengucapkan ''ain lebih pelan tanpa menambah tekanan di tengah leher, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, ''ain dan hamzah boleh dibaca sama karena sama-sama dari tenggorokan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      '''ain keluar dari tengah tenggorokan dengan tekanan yang khas (seperti menahan sesuatu di leher lalu melepaskannya), beda dari hamzah yang dari pangkal tenggorokan dengan hentakan singkat',
      'Ganti ''ain dengan ha (ح) karena keduanya dianggap sama posisi keluarnya, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'C',
      '',
      1,
      true
    ),
(
      '5375d578-8704-45c0-a226-2fd762d0521f',
      'Sifatul Huruf',
      '''Ain (ع) - Tawassuth',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf ''Ain (ع) - Tawassuth',
      'Guru menjelaskan sifat jahr dan tawassuth pada ''ain. Penjelasan tepat?',
      '''Ain bersifat hams seperti ha (ح), sehingga tidak ada getaran pita suara, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      '''Ain bersifat jahr (bergetar) dan tawassuth (pertengahan antara tertahan penuh dan mengalir bebas), sehingga bunyinya tidak sekasar kha/ghain maupun sehalus ha/hamzah',
      'Sifat tawassuth pada ''ain berarti huruf ini boleh dibaca dengan cara apa saja, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      '''Ain termasuk huruf qalqalah karena posisinya di tenggorokan, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      'edff44f9-44df-44b7-9308-07ad02cfed5a',
      'Makharijul Huruf',
      'Ghain (غ)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ghain (غ)',
      'Murid mengucapkan ghain tanpa getaran, terdengar seperti kha. Koreksinya?',
      'Biarkan saja, ghain dan kha boleh dibaca sama karena posisi keluarnya identik, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan ghain lebih keras tanpa menambah getaran pita suara, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti ghain dengan qaf karena keduanya dianggap sama-sama tebal, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Ghain dari posisi sama dengan kha (pangkal lidah dekat tenggorokan atas), tapi ghain bersifat jahr (bergetar, mirip berkumur ringan) sedangkan kha hams (berhembus tanpa getar)',
      'D',
      '',
      1,
      true
    ),
(
      'd59ef03e-fbb3-4afa-b4f6-3cebe017d2b0',
      'Sifatul Huruf',
      'Ghain (غ) - Isti''la',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Ghain (غ) - Isti''la',
      'Guru menjelaskan sifat isti''la pada ghain meski posisinya di tenggorokan (bukan lidah seperti huruf tebal lain). Penjelasan tepat?',
      'Sifat tebal pada ghain hanya muncul jika didahului harakat fathah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ghain termasuk huruf isti''la (tebal) meski keluar dari tenggorokan, karena pangkal lidah tetap terangkat tinggi saat mengucapkannya, mirip mekanisme huruf tebal lain seperti qaf',
      'Ghain bersifat istifal (tipis) karena letaknya di tenggorokan, bukan di lidah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ghain tidak memiliki sifat isti''la maupun istifal karena posisinya unik di tenggorokan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'B',
      '',
      1,
      true
    ),
(
      '49f10cb1-22cd-4a5c-aec8-e404c4544e4e',
      'Makharijul Huruf',
      'Fa (ف)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Fa (ف)',
      'Murid mengucapkan fa dengan dua bibir rapat (posisi ba), bukan bibir bawah ke gigi atas. Koreksinya?',
      'Fa keluar dari bibir bawah bagian dalam yang menyentuh ujung gigi seri atas, bukan dari pertemuan dua bibir seperti ba. contohkan dan membandingkan langsung posisi keduanya',
      'Biarkan saja, fa boleh diucapkan dari dua bibir rapat selama bunyi akhirnya masih terdengar mirip, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Minta murid mengucapkan fa lebih keras tanpa mengoreksi posisi bibir dan gigi, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti fa dengan wau karena keduanya dianggap dari posisi bibir yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'A',
      '',
      1,
      true
    ),
(
      '6b8110fc-6aa8-43c2-95ee-528c29c3715a',
      'Sifatul Huruf',
      'Fa (ف) - Hams Rakhawah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Fa (ف) - Hams Rakhawah',
      'Guru menjelaskan sifat hams dan rakhawah pada fa. Penjelasan tepat?',
      'Sifat hams pada fa hanya berlaku jika berharakat sukun, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Fa bersifat hams (berhembus) dan rakhawah (mengalir), sehingga bunyinya lembut berhembus, tidak tertahan penuh seperti huruf syiddah',
      'Fa bersifat jahr dan syiddah, sehingga bunyinya harus tertahan penuh dan bergetar, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Fa termasuk huruf qalqalah bersama ba karena sama-sama dari area bibir, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      'c622f989-efc8-4363-9d5a-36ca4a5c49e7',
      'Makharijul Huruf',
      'Qaf (ق)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Qaf (ق)',
      'Murid mengucapkan qaf seperti kaf, kurang mundur ke belakang. Koreksinya?',
      'Minta murid mengucapkan qaf lebih pelan tanpa mendorong lidah lebih mundur, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Biarkan saja, qaf dan kaf boleh dibaca sama karena sama-sama dari pangkal lidah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Ganti qaf dengan ghain karena keduanya dianggap sama-sama tebal dan berat, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Qaf dari pangkal lidah paling belakang menempel langit-langit lunak paling dalam, lebih mundur dari kaf. latih dengan mendorong bunyi ''ka'' semakin ke belakang sampai terasa lebih berat',
      'D',
      '',
      1,
      true
    ),
(
      '3fe1d021-d9dc-422b-a3c4-7052e00aa1bd',
      'Sifatul Huruf',
      'Qaf (ق) - Isti''la+Qalqalah',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Qaf (ق) - Isti''la+Qalqalah',
      'Guru menjelaskan sifat isti''la dan qalqalah pada qaf. Penjelasan tepat?',
      'Qaf memiliki sifat isti''la (tebal) sekaligus qalqalah (memantul saat mati), sehingga saat berharakat sukun harus dibaca tebal dan disertai pantulan ringan',
      'Qaf hanya bersifat isti''la, tidak termasuk salah satu huruf qalqalah, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Sifat qalqalah pada qaf hanya berlaku jika berada di awal kata, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Qaf bersifat istifal (tipis) karena posisinya paling belakang di antara huruf lidah, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'A',
      '',
      1,
      true
    ),
(
      '989320d6-dd0a-4f81-9f93-5dd070946743',
      'Makharijul Huruf',
      'Kaf (ك)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kaf (ك)',
      'Murid mengucapkan kaf terlalu mundur ke belakang, mendekati qaf. Koreksinya?',
      'Biarkan saja, kaf boleh diucapkan semundur qaf selama masih bisa dibedakan dari huruf lain, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Kaf dari pangkal lidah yang sedikit lebih maju dibanding qaf, sehingga bunyinya lebih ringan. jika terlalu mundur, bunyi kaf berubah menjadi berat seperti qaf',
      'Ganti kaf dengan ghain karena keduanya dianggap dari posisi yang sama, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Minta murid mengucapkan kaf lebih keras tanpa mengoreksi posisi lidahnya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      'f0f147cc-5ca9-41fb-bd7c-1ffee7bb9c9f',
      'Sifatul Huruf',
      'Kaf (ك) vs Qaf',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Kaf (ك) vs Qaf',
      'Guru menjelaskan sifat hams dan istifal pada kaf dibanding qaf yang jahr dan isti''la. Penjelasan tepat?',
      'Kaf termasuk huruf qalqalah bersama qaf karena posisinya berdekatan, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Kaf bersifat hams (berhembus, tidak bergetar) dan istifal (tipis), berbeda dari qaf yang jahr (bergetar) dan isti''la (tebal), meski posisi keduanya berdekatan',
      'Kaf dan qaf memiliki sifat yang identik, hanya beda posisi keluarnya sedikit, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Kaf bersifat jahr seperti qaf, sehingga pita suara ikut bergetar penuh, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'B',
      '',
      1,
      true
    ),
(
      'e7b59c15-5ad7-4b39-97a8-6793f3e0d7b6',
      'Makharijul Huruf',
      'Lam (ل)',
      'Kasus',
      'C4',
      'Sedang',
      'Guru mampu mendeteksi dan mengoreksi makhraj/sifat huruf Lam (ل)',
      'Murid mengucapkan lam dengan getaran seperti ra. Koreksinya?',
      'Minta murid mengucapkan lam lebih pelan tanpa menghilangkan getarannya, dengan harapan seiring berjalannya waktu pengucapannya akan membaik secara alamiah melalui pembiasaan.',
      'Ganti lam dengan nun karena keduanya dianggap sama-sama dari ujung lidah, sebagai metode alternatif sementara demi menjaga kelancaran setoran hafalan harian tanpa hambatan berarti.',
      'Biarkan saja, lam dan ra boleh dibaca sama karena posisinya berdekatan, karena pendekatan ini dianggap lebih mudah diterima oleh murid pemula tanpa membebani mereka.',
      'Lam keluar dari tepi lidah bagian depan menyentuh langit-langit dekat gigi atas, bunyinya harus jernih tanpa getaran, beda dari ra yang dari ujung lidah dengan getaran ringan',
      'D',
      '',
      1,
      true
    );