-- Restore missing April 2026 monthly_reports from old PDF backup.
-- Source PDF: C:\Users\ASUS\Downloads\Rekap_Laporan_April_2026.pdf
-- Extracted rows: 594
-- Safety: this inserts only missing rows. Existing April 2026 rows are NOT overwritten.

BEGIN;

CREATE TEMP TABLE _restore_april_2026_reports (
  kelas integer NOT NULL,
  rombel text NOT NULL,
  nama text NOT NULL,
  program_type text NOT NULL,
  iqra_level text,
  end_iqra_level text,
  start_page integer NOT NULL,
  end_page integer NOT NULL,
  pages_read integer NOT NULL,
  target_pages integer NOT NULL,
  achievement_status text NOT NULL,
  notes text
) ON COMMIT DROP;

INSERT INTO _restore_april_2026_reports
(kelas, rombel, nama, program_type, iqra_level, end_iqra_level, start_page, end_page, pages_read, target_pages, achievement_status, notes)
VALUES
  (1, 'A', 'Abdullah Azzubair', 'iqra', 'Iqro 6', 'Iqro 6', 9, 18, 9, 15, 'not_achieved', 'Bang Zubair tetap dibaca pr iqra-nya dirumah sama ummi dan abi agar tambah lancar Baarakallahu Fiik'),
  (1, 'A', 'Alfarezi Khavindra Ligantara', 'iqra', 'Iqro 3', 'Iqro 3', 4, 12, 8, 15, 'not_achieved', 'Masih memerlukan bimbingan lebih mendalam pada penerapan bacaan Mad (Ya'' sukun)'),
  (1, 'A', 'Althaf Maulana Habibi', 'iqra', 'Iqro 5', 'Iqro 5', 8, 22, 14, 15, 'not_achieved', 'pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Amar Mufid Al-Husein', 'iqra', 'Iqro 5', 'Iqro 5', 13, 19, 6, 15, 'not_achieved', 'Melatih penyempurnaan pada sevagian Makhraj dan meyambung bacaan (membaca tidak secara putus-putus)'),
  (1, 'A', 'Arkhan Nur Alrasyid', 'iqra', 'Iqro 4', 'Iqro 4', 16, 25, 9, 15, 'not_achieved', 'Melancarkan Makhrah Huruf dan melancarkan bacaan Mad'),
  (1, 'A', 'Ayyas uwais Alqarny', 'iqra', 'Iqro 3', 'Iqro 4', 32, 14, 12, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Hafizd Al Abbad', 'iqra', 'Iqro 4', 'Iqro 5', 25, 16, 21, 15, 'achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Hamzah Asadullah', 'iqra', 'Iqro 5', 'Iqro 5', 14, 22, 8, 15, 'not_achieved', 'Latihan membaca secara bersambung tanpa terputus-putus'),
  (1, 'A', 'Ibrahim Ar Rayyan', 'iqra', 'Iqro 2', 'Iqro 2', 25, 30, 5, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang harus fokus ketika membaca jangan kebanyakan thawaf ya bang Baarakallahu Fiik'),
  (1, 'A', 'Ikhwan Ma''ruf Yafie', 'iqra', 'Iqro 3', 'Iqro 3', 15, 25, 10, 15, 'not_achieved', 'Melancarkan bacaan Mad dan penyempurnaan makhraj'),
  (1, 'A', 'Kahfi Arka Rachmad', 'iqra', 'Iqro 5', 'Iqro 5', 7, 13, 6, 15, 'not_achieved', 'Latihan bacaan bersambung tanpa terputus putus pada iqro'' 5'),
  (1, 'A', 'Misyari Abdullah Nasution', 'iqra', 'Iqro 3', 'Iqro 3', 9, 14, 5, 15, 'not_achieved', 'Melancarkan bacaan mad dan huruf'),
  (1, 'A', 'Muhammad Abimanyu tarigan', 'iqra', 'Iqro 1', 'Iqro 1', 11, 11, 0, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Muhammad Abyan Tama', 'iqra', 'Iqro 3', 'Iqro 3', 5, 13, 8, 15, 'not_achieved', 'penurunan halaman pada jilid 3 guna melancarkan Mad yang belum sempurna'),
  (1, 'A', 'Muhammad Al-Fatih', 'iqra', 'Iqro 2', 'Iqro 2', 24, 31, 7, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang banyak mengingat huruf þÁ þ þ¥ þ¹ Baarakallahu Fiik'),
  (1, 'A', 'Muhammad Haziq', 'iqra', 'Iqro 3', 'Iqro 4', 30, 10, 10, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Muhammad Ibrahim', 'iqra', 'Iqro 3', 'Iqro 3', 8, 11, 3, 15, 'not_achieved', 'Terus semangat membaca dan belajarnya'),
  (1, 'A', 'Muhammad Khadafi Alfarizi', 'iqra', 'Iqro 3', 'Iqro 4', 30, 6, 0, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Muhammad Ukasya Hanjuni', 'iqra', 'Iqro 4', 'Iqro 4', 17, 25, 8, 15, 'not_achieved', 'Melatih fokus ketika membaca Iqro'''),
  (1, 'A', 'Muhammad Wildan', 'iqra', 'Iqro 4', 'Iqro 4', 17, 21, 4, 15, 'not_achieved', 'Melancarkan Bacaan tanpa terputus purus ketika membaca'),
  (1, 'A', 'Razka Andari Siregar', 'iqra', 'Iqro 6', 'Iqro 6', 4, 14, 10, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'A', 'Ubay Al Ushaim Abdullah', 'iqra', 'Iqro 4', 'Iqro 4', 11, 22, 11, 15, 'not_achieved', 'Perbaikan bacaan panjang pendek'),
  (1, 'A', 'Zegeist Nufail Harahap', 'iqra', 'Iqro 5', 'Iqro 5', 5, 10, 5, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya bang Baarakallahu Fiik'),
  (1, 'B', 'Abid Ubaydullah', 'iqra', 'Iqro 3', 'Iqro 3', 11, 12, 1, 15, 'not_achieved', 'Latihan terus dirumah untuk mengingat huruf dan baris serta makhroj yang tepat ya nak..'),
  (1, 'B', 'Afnan Rafasya', 'iqra', 'Iqro 2', 'Iqro 3', 31, 5, 4, 15, 'not_achieved', 'Abi dan Umi mohon bantu Ananda membaca PR Iqro''nya.'),
  (1, 'B', 'Ahmad Ubaidillah Harahap', 'iqra', 'Iqro 2', 'Iqro 2', 22, 28, 6, 15, 'not_achieved', 'Ummi dan Abi tolong bantuannya untuk membantu ananda Ubai menegerjakan PR membaca Iqro'' nya, agar ketika setoran bacaan Iqro'' di sekolah lancar.'),
  (1, 'B', 'Alrazi Akmal Prasityo', 'iqra', 'Iqro 3', 'Iqro 3', 8, 15, 7, 15, 'not_achieved', 'Abi dan Ummi mohon melengkapi buku Iqro'' Ananda, agar memudahkan Ananda untuk mengulang atau membaca PR Iqro'' nya di rumah.'),
  (1, 'B', 'Atha Alfarezi Kabeakan', 'iqra', 'Iqro 4', 'Iqro 4', 8, 12, 4, 15, 'not_achieved', '"Bacaan atha sudah lancar, tapi harus lebih teliti dan fokus lagi membedakan mana yang harus dibaca panjang dan mana yang pendek ya nak.."'),
  (1, 'B', 'Azka Afif Hamdani', 'iqra', 'Iqro 4', 'Iqro 5', 27, 9, 12, 15, 'not_achieved', '"Alhamdulillah bacaan ananda semakin lancar..tinggal dipercepat sedikit temponya agar lebih mengalir."'),
  (1, 'B', 'Dzakiandra Hasan', 'iqra', 'Iqro 3', 'Iqro 3', 10, 14, 4, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah mulai bagus tapi harus lebih teliti lagi membedakan mana yang harus dibaca panjang dan mana yang pendek ya nak"'),
  (1, 'B', 'Fajar Izzat Tama', 'iqra', 'Iqro 3', 'Iqro 3', 5, 12, 7, 15, 'not_achieved', 'Abi dan Ummi mohon untuk selalu membantu Ananda membaca PR Iqro''nya.'),
  (1, 'B', 'Fawwaz Khuzaimah Praja', 'iqra', 'Iqro 2', 'Iqro 2', 11, 17, 6, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah semakin lancar, akan tetapi lebih berlatih lagi untuk pengucapan huruf þµ þ™ þ« þ¯ þ­"'),
  (1, 'B', 'Fuiraz Achmad Syauqi Aderin', 'iqra', 'Iqro 1', 'Iqro 1', 19, 19, 0, 15, 'not_achieved', '"Jangan menyerah..Tetap semangat mengingat huruf hijaiyahnya ya nak"'),
  (1, 'B', 'Ghifari Al ''Izza', 'iqra', 'Iqro 2', 'Iqro 3', 31, 4, 0, 15, 'not_achieved', 'Abi dan Ummi mohon untuk membantu Ananda membaca PR Iqro'' nya.'),
  (1, 'B', 'Muhammad Alif Hafizh Nasution', 'iqra', 'Iqro 4', 'Iqro 4', 4, 17, 13, 15, 'not_achieved', 'Alhamdulillah Ananda baik dalam membaca Iqro''.'),
  (1, 'B', 'Muhammad Aska Ramadhan Nasution', 'iqra', 'Iqro 5', 'Iqro 5', 21, 29, 8, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah lancar akantetapi untuk mad dan tempo dalam membaca nya lebih dilatih lagi agar semakin baik ya nak"'),
  (1, 'B', 'Muhammad Azka Amzari', 'iqra', 'Iqro 3', 'Iqro 3', 13, 18, 5, 15, 'not_achieved', 'Abi dan Umi mohon bantu Ananda untuk membaca PR Iqro''nya.'),
  (1, 'B', 'Muhammad Fatih Abdul Rahman', 'iqra', 'Iqro 2', 'Iqro 2', 18, 19, 1, 15, 'not_achieved', '"Semangat terus belajarnya ya nak.. Lebih teliti lagi membedakan mana yang harus dibaca panjang dan mana yang pendek ya"'),
  (1, 'B', 'Muhammad Gibran Al-Husayn', 'iqra', 'Iqro 4', 'Iqro 5', 28, 10, 12, 15, 'not_achieved', 'Alhamdulillah Ananda baik dalam membaca Iqro''.'),
  (1, 'B', 'Muhammad Naufal Ar Rasyid', 'iqra', 'Iqro 4', 'Iqro 5', 29, 6, 7, 15, 'not_achieved', '"Bacaan ananda sudah bagus, tinggal dipercepat sedikit temponya agar lebih mengalir."'),
  (1, 'B', 'Nafiz Al-Atta Hamdan', 'iqra', 'Iqro 3', 'Iqro 3', 12, 18, 6, 15, 'not_achieved', 'Abi dan Ummi mohon untuk selalu membantu Ananda membaca PR Iqro''nya.'),
  (1, 'B', 'Raffi Artha', 'iqra', 'Iqro 3', 'Iqro 4', 29, 4, 5, 15, 'not_achieved', 'Abi dan Umi mohon bantu Ananda membaca PR Iqro''nya.'),
  (1, 'B', 'Umar Alfarouq Yanglera', 'iqra', 'Iqro 6', 'Iqro 6', 15, 17, 2, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah bagus, tinggal dipercepat sedikit temponya agar lebih mengalir."'),
  (1, 'B', 'Uwais Al Qorni', 'iqra', 'Iqro 2', 'Iqro 2', 1, 1, 0, 15, 'not_achieved', 'Ananda tidak pernah masuk sekolah.'),
  (1, 'B', 'Yazid', 'iqra', 'Iqro 5', 'Iqro 5', 7, 11, 4, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah mulai bagus...akantetapi untuk mad dan tempo bacaan nya diperhatikan lagi ya nak"'),
  (1, 'B', 'Yusuf Oziel Zamzami', 'iqra', 'Iqro 3', 'Iqro 3', 17, 18, 1, 15, 'not_achieved', '"Semangat terus belajar nya ya nak.. Harus lebih teliti untuk membedakan huruf dengan baris serta panjang pendek nya"'),
  (1, 'B', 'Zaigham Al Hamizan', 'iqra', 'Iqro 3', 'Iqro 4', 30, 5, 5, 15, 'not_achieved', 'Abi dan Umi mohon bantu Ananda membaca PR Iqro''nya.'),
  (1, 'C', 'Afifah lubis', 'iqra', 'Iqro 5', 'Iqro 5', 14, 29, 15, 15, 'achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Aisyah azmina ar-ramsyi', 'iqra', 'Iqro 4', 'Iqro 5', 26, 5, 9, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Alifa Hibatillah', 'iqra', 'Iqro 6', 'Iqro 6', 7, 14, 7, 15, 'not_achieved', NULL),
  (1, 'C', 'Alifia Salsabila', 'iqra', 'Iqro 4', 'Iqro 4', 6, 13, 7, 15, 'not_achieved', NULL),
  (1, 'C', 'Annisa Azkadina Pohan', 'iqra', 'Iqro 2', 'Iqro 2', 8, 16, 8, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Athirah Jasmine Malika', 'iqra', 'Iqro 5', 'Iqro 5', 15, 23, 8, 15, 'not_achieved', NULL),
  (1, 'C', 'Faiqah Muthia Novianto', 'iqra', 'Iqro 4', 'Iqro 4', 7, 16, 9, 15, 'not_achieved', NULL),
  (1, 'C', 'Hanifah Nur Jannah', 'iqra', 'Iqro 5', 'Iqro 5', 6, 15, 9, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Hanin Aulia Mafaza', 'iqra', 'Iqro 3', 'Iqro 4', 31, 8, 7, 15, 'not_achieved', NULL),
  (1, 'C', 'Khadijah Iffatul Azizah', 'iqra', 'Iqro 4', 'Iqro 4', 19, 25, 6, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Maryam Tabiya Eshal', 'iqra', 'Iqro 6', 'Iqro 6', 18, 28, 10, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Naqiyah Nur Iffah Br Sinukaban', 'iqra', 'Iqro 6', 'Iqro 6', 5, 12, 7, 15, 'not_achieved', NULL),
  (1, 'C', 'Nasyita Ghita Syahla', 'iqra', 'Iqro 4', 'Iqro 4', 12, 15, 3, 15, 'not_achieved', NULL),
  (1, 'C', 'Nisrin Naziha', 'iqra', 'Iqro 5', 'Iqro 6', 23, 8, 15, 15, 'achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Qienayha Setia Rahfa', 'iqra', 'Iqro 2', 'Iqro 2', 22, 26, 4, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Rania Azzura Andara', 'iqra', 'Iqro 3', 'Iqro 3', 1, 5, 2, 15, 'not_achieved', NULL),
  (1, 'C', 'Safiyyah Inayah Humaira', 'iqra', 'Iqro 4', 'Iqro 5', 28, 5, 7, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Salsabila Zahra', 'iqra', 'Iqro 5', 'Iqro 5', 7, 10, 3, 15, 'not_achieved', NULL),
  (1, 'C', 'Salwa Putri Rasya', 'iqra', 'Iqro 4', 'Iqro 4', 19, 24, 5, 15, 'not_achieved', NULL),
  (1, 'C', 'Shezan Hanayaka', 'iqra', 'Iqro 4', 'Iqro 5', 29, 8, 9, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Syafiyya jannah', 'iqra', 'Iqro 2', 'Iqro 2', 19, 21, 2, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'C', 'Tanzeela Nada Ramadhani', 'iqra', 'Iqro 5', 'Iqro 5', 15, 25, 10, 15, 'not_achieved', NULL),
  (1, 'C', 'Zalfa Hanya ketaren', 'iqra', 'Iqro 3', 'Iqro 3', 20, 27, 7, 15, 'not_achieved', 'Maulina Sitorus -'),
  (1, 'D', 'Adhiya Bakhdan Faatika', 'iqra', 'Iqro 5', 'Iqro 5', 7, 12, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Ainaya Chaira Dzahin P', 'iqra', 'Iqro 5', 'Iqro 5', 13, 20, 7, 15, 'not_achieved', 'Perhatikan huruf, dan panjang pendek'),
  (1, 'D', 'Asheeqa Hijaba Taqiya', 'iqra', 'Iqro 3', 'Iqro 3', 24, 31, 7, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' (terutama bacaan panjang-pendek) dan hafalan di rumah'),
  (1, 'D', 'Ayasha Shaqueena Shareen', 'iqra', 'Iqro 4', 'Iqro 4', 20, 30, 10, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Cut Qanita Azzahra', 'iqra', 'Iqro 3', 'Iqro 3', 14, 19, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Farhana Abdillah', 'iqra', 'Iqro 2', 'Iqro 2', 10, 14, 4, 15, 'not_achieved', 'Masih banyak harus latihan membaca di rumah'),
  (1, 'D', 'Haura Jazilah', 'iqra', 'Iqro 4', 'Iqro 5', 25, 1, 0, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Kahiratun Najihah', 'iqra', 'Iqro 1', 'Iqro 1', 15, 16, 1, 15, 'not_achieved', 'Masih sangat butuh bantuan orang tua di rumah'),
  (1, 'D', 'Kansa Anindya', 'iqra', 'Iqro 6', 'Iqro 6', 8, 17, 9, 15, 'not_achieved', 'Cukup Lancar'),
  (1, 'D', 'Khanza Nayla Cholia', 'iqra', 'Iqro 5', 'Iqro 5', 1, 9, 6, 15, 'not_achieved', 'Perhatikan huruf2 nya ketika membaca'),
  (1, 'D', 'Layla Andridy Harahap', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 41, 50, 9, 100, 'not_achieved', 'Cukup Bagus'),
  (1, 'D', 'Maryam Aisha Almahyra Lubis', 'iqra', 'Iqro 5', 'Iqro 5', 1, 9, 6, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Mecca Almadina Ikhawan', 'iqra', 'Iqro 3', 'Iqro 3', 1, 4, 1, 15, 'not_achieved', 'Dalam bulan ini membaca Iqro'' 2 (Hal 29-32) dan iqro'' 3 (Hal 3-4)'),
  (1, 'D', 'Naisah Ratu Cantika', 'iqra', 'Iqro 3', 'Iqro 3', 10, 15, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Numa Shabira', 'iqra', 'Iqro 6', 'Iqro 6', 7, 14, 7, 15, 'not_achieved', 'Perhatikan bacaan dengung dan panjang pendek'),
  (1, 'D', 'Raisya Nabila Kurniawan', 'iqra', 'Iqro 3', 'Iqro 3', 24, 27, 3, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' (terutama bacaan panjang pendeknya) di rumah'),
  (1, 'D', 'Rumaysha Hafizhah', 'iqra', 'Iqro 5', 'Iqro 5', 4, 8, 4, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Shafiyah Nailah Nst', 'iqra', 'Iqro 3', 'Iqro 3', 25, 31, 6, 15, 'not_achieved', 'Perhatikan Huruf, dan panjang pendek'),
  (1, 'D', 'Shafyyah Yumna', 'iqra', 'Iqro 5', 'Iqro 5', 7, 13, 6, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (1, 'D', 'Shaqilla Almahira', 'iqra', 'Iqro 3', 'Iqro 3', 7, 11, 4, 15, 'not_achieved', 'Perhatikan Huruf, dan panjang pendek'),
  (1, 'D', 'Syarah Alisya Sidabutar', 'iqra', 'Iqro 3', 'Iqro 3', 8, 10, 2, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda supaya banyak mengulang bacaan pr iqro'' di rumah'),
  (1, 'D', 'Zalfa Nadhif Firmansyah', 'iqra', 'Iqro 3', 'Iqro 3', 1, 6, 3, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda supaya banyak mengulang pr iqro'' di rumah dan juga perhatikan bacaan panjang-pendeknya'),
  (1, 'D', 'Zunayrah Ashfiya', 'iqra', 'Iqro 3', 'Iqro 3', 20, 31, 11, 15, 'not_achieved', 'Cukup Bagus'),
  (2, 'A', 'Abdurrahman Hanif As Shiddiq', 'iqra', 'Iqro 4', 'Iqro 4', 6, 18, 12, 15, 'not_achieved', '-'),
  (2, 'A', 'Abrizam Abdhe Habibie', 'iqra', 'Iqro 3', 'Iqro 3', 1, 5, 2, 15, 'not_achieved', 'mad dan makharijul huruf belum tepat'),
  (2, 'A', 'Ahmad Rayyan Ritonga', 'iqra', 'Iqro 3', 'Iqro 4', 29, 9, 10, 15, 'not_achieved', '-'),
  (2, 'A', 'Alfarizi Ramadhan', 'iqra', 'Iqro 4', 'Iqro 4', 7, 18, 11, 15, 'not_achieved', '-'),
  (2, 'A', 'Ar Raffi Malikal Mulki', 'iqra', 'Iqro 5', 'Iqro 5', 1, 11, 8, 15, 'not_achieved', 'panjang pendek perlu diperbaiki'),
  (2, 'A', 'Azzam Khalif', 'iqra', 'Iqro 3', 'Iqro 3', 24, 28, 4, 15, 'not_achieved', '-'),
  (2, 'A', 'Fatir Akaria', 'iqra', 'Iqro 5', 'Iqro 5', 1, 15, 12, 15, 'not_achieved', 'mad nya belum tepat'),
  (2, 'A', 'Firaz Nadeem Abdillah', 'iqra', 'Iqro 2', 'Iqro 2', 8, 16, 8, 15, 'not_achieved', '-'),
  (2, 'A', 'Gio Zafran Siddin', 'iqra', 'Iqro 2', 'Iqro 2', 1, 6, 3, 15, 'not_achieved', 'Makharijul huruf perlu perbaikan'),
  (2, 'A', 'Khalif Firzatullah Iswandi', 'iqra', 'Iqro 5', 'Iqro 5', 1, 19, 16, 15, 'achieved', 'Tajwid perlu diperbaikan'),
  (2, 'A', 'M. Gibran El syarif', 'iqra', 'Iqro 3', 'Iqro 3', 12, 15, 3, 15, 'not_achieved', '-'),
  (2, 'A', 'M. Khalif Alfarizqi', 'iqra', 'Iqro 4', 'Iqro 4', 9, 19, 10, 15, 'not_achieved', '-'),
  (2, 'A', 'M. Yusuf Alfatih', 'iqra', 'Iqro 3', 'Iqro 3', 7, 14, 7, 15, 'not_achieved', 'Panjang pendek, makharijul huruf sering tertukar'),
  (2, 'A', 'MHD. Al Faiz Harahap', 'iqra', 'Iqro 4', 'Iqro 4', 17, 28, 11, 15, 'not_achieved', '-'),
  (2, 'A', 'Muhammad Ammar Syafiq', 'iqra', 'Iqro 4', 'Iqro 4', 7, 11, 4, 15, 'not_achieved', 'Panjang pendek,pengaturan nafas masih terputus-putus'),
  (2, 'A', 'Muhammad Falih Aqmar', 'iqra', 'Iqro 4', 'Iqro 5', 28, 8, 10, 15, 'not_achieved', '-'),
  (2, 'A', 'Muhammad Khalid Afzam', 'iqra', 'Iqro 2', 'Iqro 2', 14, 16, 2, 15, 'not_achieved', 'Makharijul huruf masih belum lancar'),
  (2, 'A', 'Muhammad Luqman Hakim', 'iqra', 'Iqro 4', 'Iqro 4', 14, 21, 7, 15, 'not_achieved', '-'),
  (2, 'A', 'Muhammad Zidan Azhari', 'iqra', 'Iqro 2', 'Iqro 2', 1, 7, 4, 15, 'not_achieved', 'makharijul huruf perlu perbaikan'),
  (2, 'A', 'Rafka Zahid Al ikhwan', 'iqra', 'Iqro 4', 'Iqro 4', 11, 23, 12, 15, 'not_achieved', '-'),
  (2, 'A', 'Razzan Rizqi Kurniawan', 'iqra', 'Iqro 4', 'Iqro 4', 5, 11, 6, 15, 'not_achieved', 'Harakat masih perlu perbaikan'),
  (2, 'A', 'Rizky Maulana Hartono', 'iqra', 'Iqro 2', 'Iqro 2', 1, 5, 2, 15, 'not_achieved', 'Makharijul Huruf,panjang pendek perlu perbaikan'),
  (2, 'A', 'Rohim Arfan Azhari', 'iqra', 'Iqro 5', 'Iqro 5', 16, 28, 12, 15, 'not_achieved', '-'),
  (2, 'A', 'Tito Ravli Baskoro', 'iqra', 'Iqro 5', 'Iqro 5', 1, 19, 16, 15, 'achieved', 'ikhfa dan idzhar sering tertukar'),
  (2, 'A', 'Utsman Ibnu Affan', 'iqra', 'Iqro 5', 'Iqro 5', 4, 11, 7, 15, 'not_achieved', '-'),
  (2, 'A', 'Uwais Al Qarni', 'iqra', 'Iqro 2', 'Iqro 2', 1, 7, 4, 15, 'not_achieved', 'Makharijul huruf dan panjang pendek belum tepat'),
  (2, 'A', 'Wildan Abdurrahman', 'iqra', 'Iqro 6', 'Iqro 6', 10, 27, 17, 15, 'achieved', 'tanda waqaf perlu perbaikan'),
  (2, 'A', 'Zafran Umar Maulana', 'iqra', 'Iqro 2', 'Iqro 2', 26, 31, 5, 15, 'not_achieved', '-'),
  (2, 'B', 'Adzkia Salsabila Darma', 'iqra', 'Iqro 6', 'Iqro 6', 17, 22, 5, 15, 'not_achieved', '-'),
  (2, 'B', 'Afiza Azzahra', 'iqra', 'Iqro 4', 'Iqro 4', 24, 26, 2, 15, 'not_achieved', 'Kesulitan menyambungkan bacaan, panjang pendek dan juga sering tidak hadir'),
  (2, 'B', 'Aisyah Al Syafiyyah', 'iqra', 'Iqro 5', 'Iqro 5', 9, 25, 16, 15, 'achieved', 'Alhamdulillah... Bacaan Aisyah lancar,yg perlu di perbaiki Makhraj dan Tajwidnya.'),
  (2, 'B', 'Aisyah Br Pandia', 'iqra', 'Iqro 6', 'Iqro 6', 21, 27, 6, 15, 'not_achieved', 'Belum bisa membedakan waqof'),
  (2, 'B', 'Alesha Alfara Pohan', 'iqra', 'Iqro 5', 'Iqro 5', 9, 14, 5, 15, 'not_achieved', 'Masih perlu banyak belajar, untuk perbaikan Makhraj,Tetap semangat y kk Alesha!!!'),
  (2, 'B', 'Asma Mujahidah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 14, 20, 6, 15, 'not_achieved', 'Kesulitan mendengungkan ghunnah'),
  (2, 'B', 'Athiyah Husna Panjaitan', 'iqra', 'Iqro 6', 'Iqro 6', 13, 22, 9, 15, 'not_achieved', 'Membacanya masih terputus-putus'),
  (2, 'B', 'Beby Arisha Br Sitepu', 'iqra', 'Iqro 3', 'Iqro 4', 29, 10, 11, 15, 'not_achieved', 'Tetap semangat dalam belajar membaca Al-Qur’an, meskipun bertahap insyaAllah dengan kesungguhan akan mencapai kelancaran dan keberkahan. Barakallah fiiki.'),
  (2, 'B', 'Cut Aja Alisha', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 16, 20, 4, 15, 'not_achieved', 'Sering tidak hadir, dan panjang pendeknya masih kurang tepat'),
  (2, 'B', 'Farosha Nazneen Qiyyama', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 1, 0, 100, 'not_achieved', 'Alhamdulillah... bacaan sdh bagus,namun masih perlu perbaikan tajwid. tetap semangat kk farosha!!!!'),
  (2, 'B', 'Humaira Izzatunisa', 'iqra', 'Iqro 2', 'Iqro 2', 14, 21, 7, 15, 'not_achieved', 'Masih bingung hutuf þ¦ þ£ þŸ jika bersambung'),
  (2, 'B', 'Kamilatul Afiyah', 'iqra', 'Iqro 5', 'Iqro 5', 15, 22, 7, 15, 'not_achieved', 'Panjang pendek masih serung salah'),
  (2, 'B', 'Khadijah', 'iqra', 'Iqro 3', 'Iqro 3', 23, 27, 4, 15, 'not_achieved', 'Alhamdulillah... Bacaan lancar,yg perlu di perhatikan Makhraj dan Tajwidnya. Tetap semangat y kk Khadijah !!!!'),
  (2, 'B', 'Khumaira Altafunnisa', 'iqra', 'Iqro 6', 'Iqro 6', 11, 25, 14, 15, 'not_achieved', 'Alhamdulillah.... Bacaan lancar,yg perlu di perhatikan Makhraj dan Tajwidnya. tetap semangat kk Khumaira!!!!!'),
  (2, 'B', 'Miftahul Jannah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 24, 29, 5, 15, 'not_achieved', 'Masih sering melebihkan mad yang 2 harakat, membaca ayat masih terputus dan masih memperbaiki huruf þ±'),
  (2, 'B', 'Mikayla Almahyra Bancin', 'iqra', 'Iqro 5', 'Iqro 5', 4, 8, 4, 15, 'not_achieved', '-'),
  (2, 'B', 'Nadya Carissa Pane', 'iqra', 'Iqro 4', 'Iqro 4', 23, 29, 6, 15, 'not_achieved', 'Bacaan kurang lancar,masih banyak yg perlu di perbaiki, Makhraj dan Tajwidnya, semoga kk lebih semangat lagi belajar nya y...'),
  (2, 'B', 'Naura Chairunnisa', 'iqra', 'Iqro 4', 'Iqro 5', 27, 4, 7, 15, 'not_achieved', 'Membaca masih terputus putus'),
  (2, 'B', 'Nusaibah Humairoh', 'iqra', 'Iqro 4', 'Iqro 4', 5, 10, 5, 15, 'not_achieved', 'Alhamdulillah... bacaan kk lancar,yg harus di perbaiki Makhraj dan Tajwidnya, Ustadzah harap tolong kehadiran di perhatikan!!!!'),
  (2, 'B', 'Qalesya Nafiah Lubis', 'iqra', 'Iqro 4', 'Iqro 4', 5, 18, 13, 15, 'not_achieved', 'Masih perlu banyak belajar, Untuk perbaikan Makhraj dan Tajwidnya Tetap semangat y kk Qslesya!!!!!!'),
  (2, 'B', 'Queenre Nabila Alfatih', 'iqra', 'Iqro 5', 'Iqro 5', 18, 25, 7, 15, 'not_achieved', 'Masih sulit menyambung bacaan bertasydid dan panjang pendek'),
  (2, 'B', 'Rahil Mafaza', 'iqra', 'Iqro 5', 'Iqro 5', 13, 24, 11, 15, 'not_achieved', 'Cukup baik'),
  (2, 'B', 'Rizqia Hasna Malaika', 'iqra', 'Iqro 5', 'Iqro 5', 8, 9, 1, 15, 'not_achieved', 'Alhamdulillah... bacaan sdh lancar,tapi masih perlu banyak belajar, untuk perbaikan Makhraj dan Tajwidnya.Tetap semangat kk Rizqia !!!!!!'),
  (2, 'B', 'Rizqia Zivana Alea', 'iqra', 'Iqro 5', 'Iqro 5', 1, 11, 8, 15, 'not_achieved', 'Masih sulit menyambung bacaan tasydid'),
  (2, 'B', 'Rumaysa Hafsah Kirana Saleh', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 27, 34, 7, 15, 'not_achieved', 'Alhamdulillah... bacaan sdh lancar dan bagus,dan Tajwidnya baik,tapi masih perlu di ingat ketika mau berhenti ( tanda waqaf ).'),
  (2, 'B', 'Safira Najiha Aljannah', 'iqra', 'Iqro 6', 'Iqro 6', 7, 11, 4, 15, 'not_achieved', 'Alhamdulillah..... Bacaan lancar,yg harus di perbaiki Makhraj dan Tajwidnya. Tetap semangat kk Safira !!!'),
  (2, 'B', 'Shakilla Azzahra Munawir', 'iqra', 'Iqro 5', 'Iqro 6', 25, 5, 10, 15, 'not_achieved', 'Cukup baik'),
  (2, 'B', 'Vierra Qisya Yuan Surbakti', 'iqra', 'Iqro 5', 'Iqro 5', 14, 20, 6, 15, 'not_achieved', 'Jarang hadir dan pa jang pendek masih kurang tepat'),
  (2, 'C', 'Abdul Hanif', 'iqra', 'Iqro 5', 'Iqro 5', 15, 27, 12, 15, 'not_achieved', '-'),
  (2, 'C', 'Abdullah Abrar Taqiy Al Sudar', 'iqra', 'Iqro 4', 'Iqro 4', 10, 18, 8, 15, 'not_achieved', 'Fashiha Billa Banyak baca iqra dan perhatikan panjang pendek nya'),
  (2, 'C', 'Adiba Kayla', 'iqra', 'Iqro 5', 'Iqro 5', 23, 30, 7, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Aiza Ufairah Wibowo', 'iqra', 'Iqro 3', 'Iqro 3', 6, 8, 2, 15, 'not_achieved', 'Fashiha Billa Banyak baca iqra dan perhatikan panjang pendek dan huruf yang dibaca'),
  (2, 'C', 'Al Rashid Adnan Habibie', 'iqra', 'Iqro 3', 'Iqro 3', 17, 21, 4, 15, 'not_achieved', '-'),
  (2, 'C', 'Alzafran Rafasya prastio', 'iqra', 'Iqro 5', 'Iqro 5', 16, 23, 7, 15, 'not_achieved', '-'),
  (2, 'C', 'Amira Wulandari Br Bancin', 'iqra', 'Iqro 4', 'Iqro 4', 22, 24, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Arelya Shandra', 'iqra', 'Iqro 4', 'Iqro 5', 30, 5, 5, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Assyifa Rubina', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 21, 26, 5, 15, 'not_achieved', '-'),
  (2, 'C', 'Azzam Azzubair Manik', 'iqra', 'Iqro 5', 'Iqro 5', 4, 10, 6, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Chairul Azidan Maulan', 'iqra', 'Iqro 5', 'Iqro 5', 17, 22, 5, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Elfira Arsyila Az-zahra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 2, 4, 2, 15, 'not_achieved', '-'),
  (2, 'C', 'Elifia Sylvani Putri', 'iqra', 'Iqro 3', 'Iqro 3', 15, 20, 5, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Hanan Abiyyu Harahap', 'iqra', 'Iqro 3', 'Iqro 3', 17, 24, 7, 15, 'not_achieved', '-'),
  (2, 'C', 'Jefry Abdillah Tarigan', 'iqra', 'Iqro 3', 'Iqro 3', 30, 32, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Mafaza Khairunnisa', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 20, 27, 7, 15, 'not_achieved', '-'),
  (2, 'C', 'Muhammad Al-Fatih Bangun', 'iqra', 'Iqro 4', 'Iqro 4', 13, 25, 12, 15, 'not_achieved', '-'),
  (2, 'C', 'Muhammad AlFatih Purba', 'iqra', 'Iqro 3', 'Iqro 3', 11, 18, 7, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Muhammad irham Atalah', 'iqra', 'Iqro 2', 'Iqro 2', 25, 30, 5, 15, 'not_achieved', '-'),
  (2, 'C', 'Nabil Fajar Assyauqi', 'iqra', 'Iqro 4', 'Iqro 4', 11, 19, 8, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Nazia Afrira', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 17, 21, 4, 15, 'not_achieved', '-'),
  (2, 'C', 'Nuqman Firdaus', 'iqra', 'Iqro 3', 'Iqro 3', 23, 25, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Nur Ainun F', 'iqra', 'Iqro 6', 'Iqro 6', 15, 16, 1, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Nur Hanifah Hafsah Hafiman', 'iqra', 'Iqro 4', 'Iqro 4', 8, 10, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (2, 'C', 'Rayga Prasetiyo', 'iqra', 'Iqro 3', 'Iqro 3', 22, 28, 6, 15, 'not_achieved', '-'),
  (2, 'C', 'Razania Almashyra Surbakti', 'iqra', 'Iqro 4', 'Iqro 5', 30, 12, 12, 15, 'not_achieved', '-'),
  (2, 'C', 'Risa Ramadhaniza', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 8, 3, 15, 'not_achieved', '-'),
  (2, 'C', 'Syafira Adreena', 'iqra', 'Iqro 6', 'Iqro 6', 18, 22, 4, 15, 'not_achieved', '-'),
  (3, 'A', 'Ahmad Alfath Cholia', 'iqra', 'Iqro 4', 'Iqro 4', 1, 19, 16, 15, 'achieved', 'panjang dan pendek perlu perbaikan'),
  (3, 'A', 'Al Khalifi Dzikri', 'iqra', 'Iqro 6', 'Iqro 6', 1, 19, 16, 15, 'achieved', 'Ikhfa dan Idzhar belum tepat'),
  (3, 'A', 'Aryo Wicaksono', 'iqra', 'Iqro 6', 'Iqro 6', 7, 14, 7, 15, 'not_achieved', NULL),
  (3, 'A', 'Hilmi Arsyad', 'iqra', 'Iqro 2', 'Iqro 2', 1, 12, 9, 15, 'not_achieved', 'makharijul huruf belum tepat'),
  (3, 'A', 'Luthfie Sakhi Zaidhan', 'iqra', 'Iqro 5', 'Iqro 5', 13, 16, 3, 15, 'not_achieved', NULL),
  (3, 'A', 'M.Alfarizqi Shaquille', 'iqra', 'Iqro 4', 'Iqro 4', 10, 15, 5, 15, 'not_achieved', NULL),
  (3, 'A', 'Mahesa Arya Wiguna', 'iqra', 'Iqro 2', 'Iqro 2', 1, 4, 1, 15, 'not_achieved', 'makharijul huruf, lama idzin pulang kampung'),
  (3, 'A', 'Muhammad Syathir Rayyan', 'iqra', 'Iqro 6', 'Iqro 6', 10, 14, 4, 15, 'not_achieved', NULL),
  (3, 'A', 'Qayyum Shidqi Wahyu', 'iqra', 'Iqro 3', 'Iqro 3', 24, 29, 5, 15, 'not_achieved', 'Makharijul huruf beserta harakat belum tepat'),
  (3, 'A', 'Radja Maulana Nasution', 'iqra', 'Iqro 3', 'Iqro 3', 20, 23, 3, 15, 'not_achieved', NULL),
  (3, 'A', 'Rakha Al Rasyid Sirait', 'iqra', 'Iqro 5', 'Iqro 5', 26, 28, 2, 15, 'not_achieved', NULL),
  (3, 'A', 'Rizieq Bahrirasyidi', 'iqra', 'Iqro 5', 'Iqro 5', 4, 19, 15, 15, 'achieved', 'tajwid perlu perbaikan'),
  (3, 'A', 'Sa''id Abdullah Pinem', 'iqra', 'Iqro 6', 'Iqro 6', 11, 14, 3, 15, 'not_achieved', NULL),
  (3, 'A', 'Shafiq Adam Batubara Siregar', 'iqra', 'Iqro 4', 'Iqro 4', 8, 18, 10, 15, 'not_achieved', 'Makharijul huruf perlu perbaikan'),
  (3, 'A', 'Uwais', 'iqra', 'Iqro 5', 'Iqro 5', 1, 19, 16, 15, 'achieved', 'Tajwid serta nafas yang masih terputus-putus'),
  (3, 'A', 'Uwais Rashano Lubis', 'iqra', 'Iqro 5', 'Iqro 5', 1, 13, 10, 15, 'not_achieved', 'panjang pendek perlu perbaikan'),
  (3, 'B', 'ABYAN MAUZA ANANTA', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 14, 13, 100, 'not_achieved', '-'),
  (3, 'B', 'Al Baihaqi', 'iqra', 'Iqro 6', 'Iqro 6', 1, 13, 10, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'Alwi Syahreza', 'iqra', 'Iqro 6', 'Iqro 6', 9, 18, 9, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'DIAZ AHMAD AZZAM', 'iqra', 'Iqro 6', 'Iqro 6', 21, 30, 9, 15, 'not_achieved', '-'),
  (3, 'B', 'Ehsan Muhammad', 'tahfizh', 'Juz 29', 'Juz 29', 1, 2, 1, 3, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'GHANI YAZID KHAIRY', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 3, 2, 100, 'not_achieved', '-'),
  (3, 'B', 'Imadi Iltidzam', 'iqra', 'Iqro 6', 'Iqro 6', 22, 32, 10, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'M Boy virendra Lubis', 'iqra', 'Iqro 5', 'Iqro 5', 22, 28, 6, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'M. Alif Alamsyah', 'iqra', 'Iqro 5', 'Iqro 6', 32, 10, 8, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'M. Uwais Al Husain', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'MAHDI AL BARAA', 'iqra', 'Iqro 5', 'Iqro 6', 32, 8, 6, 15, 'not_achieved', '-'),
  (3, 'B', 'Muhammad Ahsan', 'iqra', 'Iqro 4', 'Iqro 4', 17, 23, 6, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'MUHAMMAD AL FARIS', 'iqra', 'Iqro 5', 'Iqro 5', 8, 13, 5, 15, 'not_achieved', '-'),
  (3, 'B', 'Muhammad Faathir Sain', 'iqra', 'Iqro 3', 'Iqro 4', 29, 5, 6, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'MUHAMMAD KUN ARFA', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 20, 10, 100, 'not_achieved', '-'),
  (3, 'B', 'MUHAMMAD TSAQIEB AL-THA', 'iqra', 'Iqro 5', 'Iqro 6', 25, 9, 14, 15, 'not_achieved', '-'),
  (3, 'B', 'RAYHAN AULIA', 'iqra', 'Iqro 6', 'Iqro 6', 21, 28, 7, 15, 'not_achieved', '-'),
  (3, 'B', 'Salman Alfarisi', 'iqra', 'Iqro 6', 'Iqro 6', 16, 23, 7, 15, 'not_achieved', 'Maulina Sitorus -'),
  (3, 'B', 'UTSMAN KHALIF MUSYRAFAI', 'iqra', 'Iqro 6', 'Iqro 6', 6, 14, 8, 15, 'not_achieved', '-'),
  (3, 'C', 'Aisyah Ayudhia Inara', 'iqra', 'Iqro 6', 'Iqro 6', 17, 21, 4, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah lancar.. Untuk makhrojnya sering latihan di rumah ya nak"'),
  (3, 'C', 'AISYAH AYUDIA RAHMAH', 'iqra', 'Iqro 6', 'Iqro 6', 8, 18, 10, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'Azkadina Naila', 'iqra', 'Iqro 4', 'Iqro 5', 28, 4, 6, 15, 'not_achieved', '"Alhamdulillah bacaan anada sudah bagus, tetapi harus lebih teliti lagi membedakan mana yang harus dibaca panjang dan mana yang pendek ya."'),
  (3, 'C', 'BALQIS NURI ALMEERA', 'iqra', 'Iqro 6', 'Iqro 6', 17, 22, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' (perlu penekanan huruf ghunnah yaitu 2 harakat) dan hafalan di rumah'),
  (3, 'C', 'Dzakirah Zahrah', 'iqra', 'Iqro 3', 'Iqro 3', 30, 31, 1, 15, 'not_achieved', '"Lebih semangat lagi belajar nya ya nak.. Madnya diperhatikan lagi, Bacaannya jangan dijeda ya nak"'),
  (3, 'C', 'DZAKIYYA AFTANI ARIFIN', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', 'bacaan Iqro'' 6 bulan ini dari halaman 26-32'),
  (3, 'C', 'HASHIFAH AMIRA NASUTION', 'iqra', 'Iqro 5', 'Iqro 5', 14, 21, 7, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'KHADIJAH', 'iqra', 'Iqro 5', 'Iqro 6', 28, 6, 8, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'KHALSA SABILAH SIHOTANG', 'iqra', 'Iqro 6', 'Iqro 6', 24, 30, 6, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'Khoiro Ulin Nuha', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 8, 5, 15, 'not_achieved', '"Semangat ya nak! Bacaannya sudah mulai lancar, hanya perlu lebih teliti lagi pada tanda waqaf (berhenti) dan wasal (lanjut). Sering-sering diulang di rumah agar semakin mengalir bacaannya"'),
  (3, 'C', 'KINAYA LUTHFIA ALFATIH', 'iqra', 'Iqro 3', 'Iqro 3', 19, 21, 2, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda banyak mengulang membaca pr iqro'' di rumah'),
  (3, 'C', 'Malika Aulia', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 14, 18, 4, 15, 'not_achieved', '"Semangat ya nak! Bacaannya sudah mulai lancar, hanya perlu lebih teliti lagi pada tanda waqaf (berhenti) dan wasal (lanjut). Sering-sering diulang di rumah agar semakin mengalir bacaannya"'),
  (3, 'C', 'MARYAM MUMTAZAH', 'iqra', 'Iqro 3', 'Iqro 4', 30, 5, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda banyak mengulang membaca pr iqro'' di rumah'),
  (3, 'C', 'MARYAM QINARAH BATUBARA', 'iqra', 'Iqro 5', 'Iqro 5', 13, 18, 5, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'Meyhila Tasyfa', 'iqra', 'Iqro 5', 'Iqro 5', 20, 24, 4, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah lancar akan tetapi lebih diperhatikan lagi mad dan tempo bacanya ya nak"'),
  (3, 'C', 'Nayla Adzkia Br Surbakti', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 4, 6, 2, 15, 'not_achieved', '"Semangat ya nak! Bacaannya sudah mulai lancar, hanya perlu lebih teliti lagi pada tanda waqaf (berhenti) dan wasal (lanjut). Sering-sering diulang di rumah agar semakin mengalir bacaannya"'),
  (3, 'C', 'Quin Hafizah Mahdayan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 16, 19, 3, 15, 'not_achieved', '"Semangat ya nak! Bacaannya sudah mulai lancar, hanya perlu lebih teliti lagi pada tanda waqaf (berhenti) dan wasal (lanjut). Sering-sering diulang di rumah agar semakin mengalir bacaannya"'),
  (3, 'C', 'Risya Radhatuljannah', 'iqra', 'Iqro 3', 'Iqro 4', 18, 4, 16, 15, 'achieved', '"Alhamdulillah bacaan ananda sudah mulai lancar, akantetapi untuk tempo bacaannya jangan dijeda" Ya nak"'),
  (3, 'C', 'Shaqueen Salsabila', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 15, 20, 5, 15, 'not_achieved', '"Semangat ya nak! Bacaannya sudah mulai lancar, hanya perlu lebih teliti lagi pada tanda waqaf (berhenti) dan wasal (lanjut). Sering-sering diulang di rumah agar semakin mengalir bacaannya"'),
  (3, 'C', 'Shezan Alisha Arasely', 'iqra', 'Iqro 6', 'Iqro 6', 29, 31, 2, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah bagus, akantetapi untuk tempo bacaannya jangan dijeda" Ya nak serta lebih diperhatikan lagi mad jaiz dan wajib nya"'),
  (3, 'C', 'YUMNA CANTIKA ABIDIN', 'iqra', 'Iqro 6', 'Iqro 6', 21, 32, 11, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (3, 'C', 'KAIA AFIA', 'iqra', 'Iqro 6', 'Iqro 6', 11, 15, 4, 15, 'not_achieved', 'Shaili Ayu abi dan ummi mohon bantuan untuk ananda (Iqra) Syahputri Sitorus membaca pr iqro'' (terutama bacaan panjang-pendeknya) di rumah'),
  (3, 'D', 'Aisyah Putri Alvia', 'tahfizh', 'Juz 29', 'Juz 29', 1, 5, 4, 3, 'achieved', 'Barakallahufiik.... hafalan kk Aisyah sdh bagus dan lancar,dan Tajwidnya baik semoga kk lebih semangat lagi menghafal dan memuraja''ah di rumah.'),
  (3, 'D', 'Alya Amanda', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 12, 6, 15, 'not_achieved', 'Alhamdulillah... bacaan kk lancar, tapi masih perlu di tingkatkan belajar Makhraj dan Tajwid. tetap semangat y kk..'),
  (3, 'D', 'Arafah Zakiya Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', 'Perlu memperbaiki hukum tajwid dan waqaf'),
  (3, 'D', 'Audrey Dinda Faisal', 'iqra', 'Iqro 5', 'Iqro 6', 21, 6, 15, 15, 'achieved', 'Perlu belajar penggunaan waqaf'),
  (3, 'D', 'Aysha Qatrunnada Fitri', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 10, 4, 15, 'not_achieved', 'Alhamdulillah... bacaan kk lancar, namun kurang tepat masih perlu banyak belajar, perbaikan Makhraj dan Tajwid. tetap semangat y kk..'),
  (3, 'D', 'Azkia Hanin Dinayah', 'iqra', 'Iqro 5', 'Iqro 5', 5, 22, 17, 15, 'achieved', '-'),
  (3, 'D', 'Fitri Humaira', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 13, 19, 6, 15, 'not_achieved', 'Bacaan kk kurang lancar,masih perlu banyak belajar perbaikan Makhraj dan Tajwidnya. tetap semangat y kk..'),
  (3, 'D', 'Humaira Ukasya F', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 32, 37, 5, 15, 'not_achieved', 'Alhamdulillah... bacaan sdh lancar,namun perlu di perbaiki Makhraj dan Tajwid. tetap semangat y kk...'),
  (3, 'D', 'Inayah Arfiandi', 'iqra', 'Iqro 4', 'Iqro 5', 31, 12, 11, 15, 'not_achieved', '-'),
  (3, 'D', 'Khadijah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 7, 1, 15, 'not_achieved', '-'),
  (3, 'D', 'Nabila Syahfiri NST', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 11, 6, 15, 'not_achieved', 'Alhamdulillah... bacaan sdh bagus dan lancar,Tajwid sdh baik. semoga kk Nabila lebih semangat lagi menghafal Al-Qur''an dan memuraja''ah.'),
  (3, 'D', 'Nadhira Qiana Senja', 'iqra', 'Iqro 6', 'Iqro 6', 11, 25, 14, 15, 'not_achieved', 'Perlu mempelajari waqaf'),
  (3, 'D', 'Nafisah Nazih', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 15, 5, 15, 'not_achieved', 'Alhamdulillah... bacaan kk lancar ,namun masih perlu banyak perbaikan Makhraj dan Tajwid,dan jangan terburu buru bacanya. tetap semangat y kk....'),
  (3, 'D', 'Naura Alfatunnisa Akbar', 'iqra', 'Iqro 4', 'Iqro 5', 28, 13, 15, 15, 'achieved', '-'),
  (3, 'D', 'Nayra Alyssa', 'tahfizh', 'Juz 30', 'Juz 30', 1, 6, 5, 3, 'achieved', 'Perbaikan huruf þÅ dan þ¯'),
  (3, 'D', 'Raisah Nadhira', 'iqra', 'Iqro 4', 'Iqro 5', 24, 6, 12, 15, 'not_achieved', '-'),
  (3, 'D', 'Rania Azzahra Wahyudi', 'iqra', 'Iqro 5', 'Iqro 5', 8, 20, 12, 15, 'not_achieved', 'Perlu memperbaiki keluar huruf þÉ dan þƒ'),
  (3, 'D', 'Sabrina Najihah', 'iqra', 'Iqro 3', 'Iqro 4', 29, 12, 13, 15, 'not_achieved', '-'),
  (3, 'D', 'Safanah Humairoh', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 14, 7, 15, 'not_achieved', 'Alhamdulillah.. bacaan lancar,namun masih perlu perbaikan Makhraj dan Tajwidnya. tetap semangat y kk...'),
  (3, 'D', 'Wafiq Azizah Sakinah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 13, 19, 6, 15, 'not_achieved', 'Alhamdulillah.. bacaan kk lancar,namun lebih ditingkatkan lagi kualitas Makhraj dan Tajwid. semoga kk lebih semangat lagi....'),
  (3, 'D', 'Yasmin Ziya Lathifah', 'iqra', 'Iqro 6', 'Iqro 6', 8, 31, 23, 15, 'achieved', '.........þÚþôþÓ ýò þÙþ­þŽþ‘ Alhamdulillah.... Bacaan sdh bagus, dan lancar yg perlu diingat cara membedakan Idzhar dan Ikhfa. lebih semangat lagi y kk Yasmin!!!!!'),
  (3, 'D', 'Zaynab Asysyaima', 'iqra', 'Iqro 6', 'Iqro 6', 11, 27, 16, 15, 'achieved', 'Perlu memperbaiki hukum tajwid Izhar'),
  (4, 'A', 'Abdullah zaid', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 9, 8, 15, 'not_achieved', '-'),
  (4, 'A', 'Ahmad Fachri Rafasha Chaniago', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 12, 7, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Dalam Surat Al-Baqarah'),
  (4, 'A', 'Arzanka Razaq Hamdan', 'iqra', 'Iqro 4', 'Iqro 4', 19, 29, 10, 15, 'not_achieved', '-'),
  (4, 'A', 'Aufa Saqhil', 'iqra', 'Iqro 3', 'Iqro 3', 24, 30, 6, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H -'),
  (4, 'A', 'Azizan Shaqil', 'iqra', 'Iqro 5', 'Iqro 5', 17, 24, 7, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Terus tingkatkan semangat belajarnya, perbanyak membaca dan murojaah sebelum tasmi bersama ustadz agar peningkatan bacaannya semakin pesat, serta kurangi bermain agar lebih fokus dalam belajar, Barakallah Fiik'),
  (4, 'A', 'Azmi Ar rasyid Lubis', 'iqra', 'Iqro 5', 'Iqro 6', 20, 4, 14, 15, 'not_achieved', '-'),
  (4, 'A', 'Dafa Rafif Alfathan', 'iqra', 'Iqro 5', 'Iqro 5', 16, 32, 16, 15, 'achieved', '-'),
  (4, 'A', 'Dzikri Ikhwan', 'iqra', 'Iqro 6', 'Iqro 6', 25, 29, 4, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Lebih serius lagi dalam membaca Iqra’ dan perbanyak latihan setiap hari agar kemampuan membaca semakin baik serta segera naik ke Tahsin Lanjutan'),
  (4, 'A', 'Faiz Pranaja', 'iqra', 'Iqro 5', 'Iqro 5', 14, 29, 15, 15, 'achieved', '-'),
  (4, 'A', 'Fajar alifio', 'iqra', 'Iqro 5', 'Iqro 6', 19, 4, 15, 15, 'achieved', '-'),
  (4, 'A', 'Fathan Ahmad', 'iqra', 'Iqro 5', 'Iqro 6', 28, 11, 13, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H -'),
  (4, 'A', 'Luthfie Sakrie Zaidan', 'iqra', 'Iqro 4', 'Iqro 4', 19, 25, 6, 15, 'not_achieved', 'Miftahul Arsyad Gunakan waktu sebaik mungkin, manfaatkan waktu Saragih (Iqra) Asri, S.H membaca dengan maksimal dan isi waktu luang dengan hal-hal yang bermanfaat. Tingkatkan fokus dalam shalat, insyaAllah Allah akan memperbaiki akhlak dan perangainya, Barakallah fiikum.'),
  (4, 'A', 'Mirza Habib Ukail', 'iqra', 'Iqro 6', 'Iqro 6', 9, 32, 23, 15, 'achieved', '-'),
  (4, 'A', 'Muhammad Alfiandah', 'iqra', 'Iqro 4', 'Iqro 4', 17, 29, 12, 15, 'not_achieved', '-'),
  (4, 'A', 'Muhammad Atha Erlangga', 'iqra', 'Iqro 5', 'Iqro 5', 4, 21, 17, 15, 'achieved', '-'),
  (4, 'A', 'Muhammad Faris khan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 2, 13, 11, 15, 'not_achieved', '-'),
  (4, 'A', 'Muhammad Farrel Al faiz Waskita', 'iqra', 'Iqro 4', 'Iqro 4', 9, 12, 3, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Tingkatkan semangat belajar Iqra’-nya, perbanyak latihan membaca setiap hari agar kemampuan membaca semakin baik dan terus berkembang. Barakallah fiikum.'),
  (4, 'A', 'Muhammad Hanif Al Hafiz', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 19, 13, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Jangan mudah terpengaruh oleh tingkah laku yang kurang baik dari teman. Pilihlah pergaulan yang membawa kepada kebaikan, tetap hormat kepada guru dan orang tua, serta isi waktu dengan belajar dan kegiatan yang bermanfaat agar menjadi anak yang berakhlak baik dan membanggakan. Barakallah fiikum'),
  (4, 'A', 'Omar Al Faruq', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 19, 18, 15, 'achieved', 'Miftahul Arsyad Asri, S.H -'),
  (4, 'A', 'Rafardan Al farizky', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 32, 45, 13, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Tetap semangat berlatih memanjangkan bacaan mad sesuai kaidah tajwid, karena dengan latihan yang rutin insyaAllah bacaan Al-Qur’annya akan semakin baik, tartil, dan lancar. Barakallah fiik'),
  (4, 'A', 'Rayyan Affan Ar rafif', 'iqra', 'Iqro 5', 'Iqro 6', 18, 4, 16, 15, 'achieved', '-'),
  (4, 'A', 'Revano aditya', 'iqra', 'Iqro 5', 'Iqro 6', 19, 4, 15, 15, 'achieved', '-'),
  (4, 'A', 'Safaraz Wiratama', 'iqra', 'Iqro 4', 'Iqro 4', 16, 22, 6, 15, 'not_achieved', 'Miftahul Arsyad Asri, S.H Tingkatkan lagi semangat membaca Iqra’-nya ya nak, rajin berlatih setiap hari agar bacaan semakin lancar dan cepat berkembang, insyaAllah akan segera naik ke tingkat berikutnya.'),
  (4, 'A', 'Satria Ramadhan Purba', 'iqra', 'Iqro 4', 'Iqro 4', 18, 24, 6, 15, 'not_achieved', 'Miftahul Arsyad Terus latihan di rumah juga ya, karena latihan yang (Iqra) Asri, S.H rutin sangat membantu meningkatkan persentase keberhasilan dalam membaca Al-Qur’an dengan baik dan lancar. Barakallahu fiik'),
  (4, 'A', 'Zain Malik ibrahim', 'iqra', 'Iqro 5', 'Iqro 6', 26, 13, 17, 15, 'achieved', '-'),
  (4, 'A', 'Zaki Khairil Azam Lubis', 'iqra', 'Iqro 5', 'Iqro 6', 21, 15, 24, 15, 'achieved', 'Miftahul Arsyad Asri, S.H Ananda sudah memiliki kemampuan membaca yang baik, Tetap semangat ya nak, sedikit lagi insyaAllah akan naik tingkat. Terus rajin belajar dan berlatih agar bacaan semakin lancar dan baik.'),
  (4, 'A', 'Zidane akido Yuan surbakti', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', '-'),
  (4, 'B', 'Abdullah Farhan', 'iqra', 'Iqro 6', 'Iqro 6', 4, 14, 10, 15, 'not_achieved', '-'),
  (4, 'B', 'Abid Abqori', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 14, 21, 7, 15, 'not_achieved', '-'),
  (4, 'B', 'Affan Amarul Zaki', 'iqra', 'Iqro 1', 'Iqro 1', 19, 20, 1, 15, 'not_achieved', 'Sampai sekarang masih belum bisa membedakan huruf þÆ þÃ þ¿ þ»'),
  (4, 'B', 'Affan Muhammad Habibi', 'iqra', 'Iqro 6', 'Iqro 6', 26, 32, 6, 15, 'not_achieved', '-'),
  (4, 'B', 'Arkhan Pradipta Irawan', 'iqra', 'Iqro 5', 'Iqro 5', 12, 13, 1, 15, 'not_achieved', 'Masih perlu banyak bimbingan di rumah, untuk membantu dalam membaca iqro'''),
  (4, 'B', 'Arsyil Pradipta Rahman', 'iqra', 'Iqro 3', 'Iqro 3', 7, 15, 8, 15, 'not_achieved', 'Perhatikan panjang pendek, dan huruf'),
  (4, 'B', 'Aufar Dean Alfatih', 'iqra', 'Iqro 6', 'Iqro 6', 8, 16, 8, 15, 'not_achieved', 'Cukup Bagus'),
  (4, 'B', 'Azka Ar Rasyid Lubis', 'iqra', 'Iqro 5', 'Iqro 5', 14, 23, 9, 15, 'not_achieved', '-'),
  (4, 'B', 'Azzam Askhari Hasibuan', 'iqra', 'Iqro 6', 'Iqro 6', 15, 22, 7, 15, 'not_achieved', 'Sering keliru dengung'),
  (4, 'B', 'Bagas Pradipta', 'iqra', 'Iqro 4', 'Iqro 5', 32, 7, 5, 15, 'not_achieved', 'Masih sering keliru huruf dan panjang pendek'),
  (4, 'B', 'Farid Athallah Alfatih', 'iqra', 'Iqro 6', 'Iqro 6', 7, 14, 7, 15, 'not_achieved', '-'),
  (4, 'B', 'Gibran Maulana', 'iqra', 'Iqro 5', 'Iqro 6', 27, 5, 8, 15, 'not_achieved', '-'),
  (4, 'B', 'Hafiz Atilla', 'iqra', 'Iqro 4', 'Iqro 4', 9, 13, 4, 15, 'not_achieved', 'Abi dan Umi tolong bantu ananda membaca PR Iqro''nya karena agar membantu kelancaran Ananda ketika membaca Iqro''.'),
  (4, 'B', 'Izzuddin Yusuf Abdurrahman', 'iqra', 'Iqro 5', 'Iqro 6', 28, 7, 9, 15, 'not_achieved', 'Perhatian Dengung, dan panjang pendek'),
  (4, 'B', 'Kenzie Syah Alaquila', 'iqra', 'Iqro 6', 'Iqro 6', 16, 24, 8, 15, 'not_achieved', '-'),
  (4, 'B', 'M Alif Akbar Nasution', 'iqra', 'Iqro 5', 'Iqro 6', 21, 1, 12, 15, 'not_achieved', 'Cukup bagus'),
  (4, 'B', 'M. Fabyansyah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', 'Ananda naik level tahsin lanjutan, tahsin dasar dari Iqro'' 6 halaman 30-32.'),
  (4, 'B', 'M. Kenzo Raffasya', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Ananda naik level tahsin lanjutan, tahsin dasar dari Iqro'' 6 halaman 30-32.'),
  (4, 'B', 'Muhad Zazib Roif', 'iqra', 'Iqro 6', 'Iqro 6', 1, 10, 7, 15, 'not_achieved', 'Cukup bagus'),
  (4, 'B', 'Muhammad Alif Al Mahdi', 'iqra', 'Iqro 5', 'Iqro 5', 23, 29, 6, 15, 'not_achieved', '-'),
  (4, 'B', 'Muhammad Azka Syandana', 'iqra', 'Iqro 5', 'Iqro 5', 16, 23, 7, 15, 'not_achieved', 'Cukup bagus'),
  (4, 'B', 'Muhammad Maheer Al''Asyi', 'iqra', 'Iqro 5', 'Iqro 5', 20, 23, 3, 15, 'not_achieved', 'Masih perlu banyak bimbingan d rumah, biar bacaan iqro''nya lancar'),
  (4, 'B', 'Muhammad Muawiyah', 'iqra', 'Iqro 6', 'Iqro 6', 27, 32, 5, 15, 'not_achieved', '-'),
  (4, 'B', 'Rashya Al Kawakibi', 'iqra', 'Iqro 4', 'Iqro 4', 4, 14, 10, 15, 'not_achieved', 'Shaila Ayu - Wiyandha (Iqra) Syahputri Sitorus'),
  (4, 'B', 'Rawi Putra Pratama', 'iqra', 'Iqro 5', 'Iqro 5', 15, 20, 5, 15, 'not_achieved', '-'),
  (4, 'B', 'Sa''ad Abdullah', 'iqra', 'Iqro 6', 'Iqro 6', 21, 27, 6, 15, 'not_achieved', 'Masih sering keliru dengung, dan waqof'),
  (4, 'B', 'Syahir Zain Abdullah', 'iqra', 'Iqro 3', 'Iqro 3', 25, 30, 5, 15, 'not_achieved', 'Masih perlu banyak bimbingan di rumah'),
  (4, 'B', 'Syamil Muhimbullah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 4, 3, 15, 'not_achieved', 'Ananda naik level tahsin lanjutan dan tahsin dasarnya dari Iqro'' 6 halaman 26-32.'),
  (4, 'B', 'Zaki Zaydan', 'iqra', 'Iqro 6', 'Iqro 6', 10, 18, 8, 15, 'not_achieved', '-'),
  (4, 'C', 'Adzkia Hamdani', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 4, 19, 15, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (4, 'C', 'Afrilia Fazila Br Sembiring', 'iqra', 'Iqro 5', 'Iqro 6', 29, 9, 10, 15, 'not_achieved', 'Cukup baik'),
  (4, 'C', 'Aisyah Nuha Zahira', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 23, 28, 5, 15, 'not_achieved', 'Cukup'),
  (4, 'C', 'Aliya Ratu Salsabila Lumban Batu', 'iqra', 'Iqro 6', 'Iqro 6', 18, 24, 6, 15, 'not_achieved', 'Kurang lancar'),
  (4, 'C', 'Aluna Fathya Setiawan', 'iqra', 'Iqro 5', 'Iqro 5', 13, 15, 2, 15, 'not_achieved', 'Pr iqra-nya dibaca dirumah ya kak Baarakallahu Fiik'),
  (4, 'C', 'Anisah Ufairah Iswandi', 'iqra', 'Iqro 5', 'Iqro 5', 20, 30, 10, 15, 'not_achieved', 'Pr iqra-nya dirumah tetap dibaca ya kak Baarakallahu Fiik'),
  (4, 'C', 'Aqila Nayla Putri', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 11, 4, 15, 'not_achieved', 'Cukup'),
  (4, 'C', 'Aqilla Qurrata Aini', 'tahfizh', 'Tahfizh', 'Tahfizh', 1, 33, 32, 100, 'not_achieved', 'kak, biar tambah lancar Baarakallahu Fiik'),
  (4, 'C', 'Arsyila Ramadani', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Cukup'),
  (4, 'C', 'Azzura Al Zemirah Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 4, 3, 15, 'not_achieved', 'Cukup'),
  (4, 'C', 'Deriyana Rahma Siregar', 'iqra', 'Iqro 6', 'Iqro 6', 25, 32, 7, 15, 'not_achieved', 'Pemutqinan iqro 6'),
  (4, 'C', 'Fadhilah Izzatun Jannah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 9, 8, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (4, 'C', 'Faizia Azkia Kamil Nasution', 'iqra', 'Iqro 5', 'Iqro 6', 23, 9, 16, 15, 'achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (4, 'C', 'Habibah Varisha Sholeha', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 22, 26, 4, 15, 'not_achieved', 'Panjang pendek masih kurang tepat'),
  (4, 'C', 'Haniifah Abidah Naziihah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 50, 58, 8, 15, 'not_achieved', 'Baik'),
  (4, 'C', 'Hanina Sahla Hamdani', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 25, 15, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (4, 'C', 'Humairah Saba Purba', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 4, 3, 15, 'not_achieved', 'Cukup'),
  (4, 'C', 'Khanza Aqila Inara', 'iqra', 'Iqro 6', 'Iqro 6', 7, 15, 8, 15, 'not_achieved', 'Masih bingung meng ikhfakan bacaan'),
  (4, 'C', 'Nafisa Nur Alfattya', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 11, 25, 14, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (4, 'C', 'Nazwa Aulia Octaviani', 'iqra', 'Iqro 6', 'Iqro 6', 19, 30, 11, 15, 'not_achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (4, 'C', 'Nurwahida Siamaharani', 'iqra', 'Iqro 5', 'Iqro 5', 4, 10, 6, 15, 'not_achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (4, 'C', 'Qheyra Syafitri Dzahin', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 47, 52, 5, 15, 'not_achieved', 'Cukup lancar'),
  (4, 'C', 'Rafiqa Raisa', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 9, 22, 13, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nyaDicetak: 7 Mei 2026 Halaman 25 dari 44 Baarakallahu Fiik'),
  (4, 'C', 'Rana Fitya Andara', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 28, 35, 7, 15, 'not_achieved', 'Cukup lancar, terkadang kurang tepat pada makhorijul huruf þ¥'),
  (4, 'C', 'Salsabila Mumtazah', 'tahfizh', 'Tahfizh', 'Tahfizh', 1, 18, 17, 100, 'not_achieved', 'Tetap di murajaah hafalan yang sudah di dapat, biar tambah lancar Baarakallahu Fiik'),
  (4, 'D', 'Adiba Azrin Nindita', 'iqra', 'Iqro 5', 'Iqro 5', 21, 24, 3, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Ailsa Huwaidah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 22, 24, 2, 100, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Aisyah Ayudia Inara', 'iqra', 'Iqro 6', 'Iqro 6', 15, 23, 8, 15, 'not_achieved', 'Perbaikan bacaan panjang pendek'),
  (4, 'D', 'Alfiyyah Naysa Kamila', 'iqra', 'Iqro 4', 'Iqro 4', 23, 28, 5, 15, 'not_achieved', 'Perbaikan bacaan panjang pendek'),
  (4, 'D', 'Alifa Azzahra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 22, 24, 2, 100, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Annisa Febry Yanti', 'iqra', 'Iqro 6', 'Iqro 6', 21, 32, 11, 15, 'not_achieved', 'Perbaikan bacaan persiapan ujian naik tingkat tahsin lanjutan'),
  (4, 'D', 'Annisa Zhafira', 'iqra', 'Iqro 5', 'Iqro 5', 1, 5, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Assyifa Humaira Ahmad', 'iqra', 'Iqro 6', 'Iqro 6', 14, 23, 9, 15, 'not_achieved', 'Melancarkan Bacaan dan waqaf ketika membaca'),
  (4, 'D', 'Dwi Azka Talita Zahra', 'iqra', 'Iqro 5', 'Iqro 6', 26, 4, 8, 15, 'not_achieved', 'Penguatan Mad Wajib dan Mad Ashly'),
  (4, 'D', 'Indira Azzahra Jasmine', 'iqra', 'Iqro 6', 'Iqro 6', 25, 32, 7, 15, 'not_achieved', 'Persiapan Ujian naik tingkat (Tahsin Lanjutan)'),
  (4, 'D', 'Kanisya Azwa', 'iqra', 'Iqro 5', 'Iqro 6', 24, 4, 10, 15, 'not_achieved', 'Melatih bacaan bersambung pada Iqro'' 5 dan penguatan Mad'),
  (4, 'D', 'Khadijah Nufaisah', 'iqra', 'Iqro 4', 'Iqro 4', 15, 18, 3, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Khairin Rahmadani', 'iqra', 'Iqro 6', 'Iqro 6', 27, 32, 5, 15, 'not_achieved', 'Persiapan ujian naik tingkat (Tahsin Lanjutan)'),
  (4, 'D', 'Maleeka Khairriyah Maulana', 'iqra', 'Iqro 4', 'Iqro 4', 22, 24, 2, 15, 'not_achieved', 'Fashiha Billa Fokus dan banyak baca iqro dirumah untuk melatih bacaan, dan perhatikan mad, huruf dan harakatnya'),
  (4, 'D', 'Nabila Atha Dzakira', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 8, 7, 15, 'not_achieved', 'Penguatan Waqaf dan Mad Wajib'),
  (4, 'D', 'Nadine Safa Elysia', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 22, 24, 2, 100, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Nagiva Humairah', 'iqra', 'Iqro 6', 'Iqro 6', 26, 32, 6, 15, 'not_achieved', 'Persiapan ujian naik tingkat (Tahsin Lanjutan)'),
  (4, 'D', 'Naira Azzahra', 'iqra', 'Iqro 6', 'Iqro 6', 14, 17, 3, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Natasha Ilmira Butar Butar', 'iqra', 'Iqro 6', 'Iqro 6', 24, 28, 4, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Naysa Luna Maharani', 'tahfizh', 'Juz 25', 'Juz 27', 1, 1, 40, 3, 'achieved', 'Muraja''ah 7 Juz (5 halaman/hari)'),
  (4, 'D', 'Salma Adliyah', 'iqra', 'Iqro 5', 'Iqro 5', 10, 15, 5, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Samhana Rafidah Biqis', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 9, 10, 1, 15, 'not_achieved', 'Fashiha Billa -'),
  (4, 'D', 'Syaqila Azzahra', 'iqra', 'Iqro 6', 'Iqro 6', 23, 30, 7, 15, 'not_achieved', 'Penguatan mad dan waqaf'),
  (4, 'D', 'Syaqila Zahrani Hamzan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 6, 3, 100, 'not_achieved', 'Fashiha Billa -'),
  (5, 'A', 'Abdullah Habibi Al Ghifari', 'iqra', 'Iqro 5', 'Iqro 5', 12, 15, 3, 15, 'not_achieved', 'abi dan ummi, ananda diturunkan dari iqro'' 5 hal.30 ke iqro'' 5 hal.12 karena ada bacaan yang belum pas(seperti gunnah dan qalqalah)'),
  (5, 'A', 'Abdurahman', 'iqra', 'Iqro 6', 'Iqro 6', 17, 27, 10, 15, 'not_achieved', 'Sering keliru panjang pendek, dan dengung'),
  (5, 'A', 'Adnan Syafi Amzari', 'iqra', 'Iqro 5', 'Iqro 5', 19, 22, 3, 15, 'not_achieved', 'Shaili Ayu Syahputri abi dan ummi mohon bantuan untuk ananda banyak mengulang membaca pr iqro'' di rumah Sitorus'),
  (5, 'A', 'Adzkan Dzar Alghifari Hasibuan', 'iqra', 'Iqro 5', 'Iqro 5', 17, 20, 3, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah dan tolong untuk melengkapi buku batas bacaan iqro'''),
  (5, 'A', 'Al Hatim', 'iqra', 'Iqro 5', 'Iqro 5', 7, 11, 4, 15, 'not_achieved', 'Harus banyak latihan membaca di rumah'),
  (5, 'A', 'Azka Fairuz', 'iqra', 'Iqro 6', 'Iqro 6', 4, 13, 9, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda membaca pr iqro'' di rumah'),
  (5, 'A', 'Badrussalam', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 40, 48, 8, 15, 'not_achieved', 'Perhatikan waqof'),
  (5, 'A', 'Dafa Azhar', 'iqra', 'Iqro 5', 'Iqro 5', 14, 16, 2, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda banyak banyak mengulang membaca pr iqro'' di rumah'),
  (5, 'A', 'Dika Fahrezi', 'iqra', 'Iqro 3', 'Iqro 3', 8, 10, 2, 15, 'not_achieved', 'Abi dan ummi, ananda sangat memerlukan perhatian untuk mengulang bacaan pr iqro'' nya di rumah'),
  (5, 'A', 'Faiz Habibi', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 29, 39, 10, 15, 'not_achieved', 'Perhatikan panjang pendek, dan dengung'),
  (5, 'A', 'Faiz Muzacky Wahyudi', 'iqra', 'Iqro 4', 'Iqro 4', 26, 30, 4, 15, 'not_achieved', 'Banyak latihan membaca di rumah'),
  (5, 'A', 'Faris Bahauddin Basyir Pohan', 'iqra', 'Iqro 3', 'Iqro 3', 20, 21, 1, 15, 'not_achieved', 'abi dan ummi bacaan ananda diturunkan dari iqro''4 hal.31 ke iqro''3 hal.20 supaya bacaan lebih baik lagi dan mohon untuk melengkapi buku batas bacaan(LTQ)'),
  (5, 'A', 'Fawwaz Abu Abdillah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 8, 16, 8, 15, 'not_achieved', 'abi dan ummi mohon bantuan untuk ananda mengingat bacaan tajwid(terutama mad), makharijul huruf(terutama huruf þ«,þ™) di rumah'),
  (5, 'A', 'GALANG HARDIANSYAH HASIBUAN', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 29, 33, 4, 15, 'not_achieved', 'alhamdulillah ananda sudah cukup baik bacaannya, tapi tetap harus ditingkatkan lagi ya'),
  (5, 'A', 'Haikal Arkana Ali Masyrafah', 'iqra', 'Iqro 6', 'Iqro 6', 17, 21, 4, 15, 'not_achieved', 'Sering keliru huruf, panjang pendek dan dengung'),
  (5, 'A', 'Hasbi Irsyad', 'iqra', 'Iqro 5', 'Iqro 5', 19, 25, 6, 15, 'not_achieved', 'Perhatikan panjang pendek, huruf dan waqof'),
  (5, 'A', 'Ihsan Al Fatih', 'iqra', 'Iqro 4', 'Iqro 4', 24, 24, 0, 15, 'not_achieved', 'Shaili Ayu abi dan ummi, ananda diturunkan dari iqro''5 hal.17 (Iqra) Syahputri Sitorus ke iqro''4 hal.24 supaya bacaan nya lebih baik lagi dan mohon perhatikan lagi absensi kehadiran'),
  (5, 'A', 'M. Digha Setia Muazzam', 'iqra', 'Iqro 4', 'Iqro 5', 30, 1, 3, 15, 'not_achieved', 'abi dan ummi mohon bantuan ananda supaya rajin mengulang membaca pr iqro'' di rumah dan perhatikan huruf þ« dan þ™'),
  (5, 'A', 'M. Fahri Akbar', 'iqra', 'Iqro 6', 'Iqro 6', 19, 32, 13, 15, 'not_achieved', '-'),
  (5, 'A', 'Mhd Daffa Alfarizi', 'iqra', 'Iqro 6', 'Iqro 6', 14, 20, 6, 15, 'not_achieved', 'Perhatikan panjang pendek, dengung dan waqof'),
  (5, 'A', 'Muhammad al baihaqi', 'iqra', 'Iqro 5', 'Iqro 6', 20, 11, 21, 15, 'achieved', '-'),
  (5, 'A', 'Muhammad Al-Baihaqi Ramadhan', 'iqra', 'Iqro 6', 'Iqro 6', 1, 1, 0, 15, 'not_achieved', '-'),
  (5, 'A', 'Muhammad Alif Fatul', 'iqra', 'Iqro 6', 'Iqro 6', 18, 22, 4, 15, 'not_achieved', 'Perhatikan panjang pendek'),
  (5, 'A', 'Muhammad Erza Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 31, 44, 13, 15, 'not_achieved', '-'),
  (5, 'A', 'Muhammad Hadyan Rasyidin Siregar', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 17, 7, 15, 'not_achieved', 'alhamdulillah bacaan ananda sudah cukup baik, tapi tetap ditingkatkan lagi yaa'),
  (5, 'A', 'Muhammad Hajim As Tsaqib', 'iqra', 'Iqro 5', 'Iqro 5', 9, 16, 7, 15, 'not_achieved', 'Perhatikan waqof dan huruf'),
  (5, 'A', 'Muhammad Naufal Hamizan Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 10, 5, 15, 'not_achieved', 'tingkat kan lagi bacaan tajwid nya terutama mad dan ghunnahnya'),
  (5, 'A', 'Mukhlis', 'iqra', 'Iqro 5', 'Iqro 6', 31, 7, 6, 15, 'not_achieved', 'Perhatikan panjang pendek dan waqof'),
  (5, 'A', 'Naufal Afkar Novianto', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'ditingkatkan lagi bacaannya ya'),
  (5, 'A', 'Raffizan Prasetya', 'iqra', 'Iqro 6', 'Iqro 6', 27, 31, 4, 15, 'not_achieved', 'Perhatikan huruf, panjang pendek, dengung, dan waqof'),
  (5, 'A', 'Rasya Arsakha', 'iqra', 'Iqro 5', 'Iqro 6', 30, 4, 4, 15, 'not_achieved', 'Banyak latihan di rumah'),
  (5, 'A', 'Rivana Al Haqqy', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 19, 7, 15, 'not_achieved', 'Shaili Ayu perhatikan huruf þµ dengan þ™ itu berbeda yaa Lanjutan Syahputri Sitorus'),
  (5, 'B', 'Aditya Kanada', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 28, 35, 7, 15, 'not_achieved', 'Bacaan sudah cukup baik, hanya saja sering terburu buru membacanya'),
  (5, 'B', 'Aditya Naufal Kasada', 'iqra', 'Iqro 4', 'Iqro 4', 10, 20, 10, 15, 'not_achieved', '-'),
  (5, 'B', 'Ahmad Satria Rama', 'iqra', 'Iqro 6', 'Iqro 6', 16, 19, 3, 15, 'not_achieved', 'Ananda, semangatlah selalu ketika membaca Iqro'' ya.'),
  (5, 'B', 'Ahsan Abdur Rozzaq', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 15, 3, 15, 'not_achieved', 'Sering sering latihan panjang pendek dan juga ghunnah'),
  (5, 'B', 'Ar Sakha Ransi Azhari', 'iqra', 'Iqro 3', 'Iqro 3', 17, 24, 7, 15, 'not_achieved', 'Abi dan Umi mohon bantuan agar Ananda banyak banyak membaca PR Iqro'' yang diberikan.'),
  (5, 'B', 'Arsa Pradana Siregar', 'iqra', 'Iqro 6', 'Iqro 6', 23, 30, 7, 15, 'not_achieved', 'Cukup lancar, perhatikan lagi cara membaca ikhfa'),
  (5, 'B', 'Daffaa Pranata Ketaren', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 23, 26, 3, 15, 'not_achieved', 'Harus sering latihan tadarus di rumah'),
  (5, 'B', 'Dirga Panca Dahana', 'iqra', 'Iqro 5', 'Iqro 5', 1, 1, 0, 15, 'not_achieved', '-'),
  (5, 'B', 'Elza Altori', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 12, 9, 15, 'not_achieved', '-'),
  (5, 'B', 'Farid Husain', 'iqra', 'Iqro 6', 'Iqro 6', 26, 32, 6, 15, 'not_achieved', 'Pemutqinan iqro'' 6, sering sering dilatih bacaannya di rumah'),
  (5, 'B', 'Fatih Ahmad', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 17, 5, 15, 'not_achieved', 'Perbaiki cara membaca ikhfa dan ghunnah'),
  (5, 'B', 'Fauzan Athallah Putra', 'iqra', 'Iqro 6', 'Iqro 6', 11, 18, 7, 15, 'not_achieved', 'Ananda, semangatlah selalu ketika membaca Iqro'' yaa.'),
  (5, 'B', 'Hanan Attaqy', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 4, 3, 15, 'not_achieved', 'Dita Wardania Sering sering latihan tadarus di rumah agar Lanjutan Br Panjaitan bacaannya semakin baik'),
  (5, 'B', 'Irhabi Sani Harahap', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 29, 35, 6, 15, 'not_achieved', 'Latihan membaca ikhfa, dan panjang pendek terkadang masih keliru'),
  (5, 'B', 'Kenzi Alvaro', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 34, 44, 10, 15, 'not_achieved', 'Masih harus sering sering latihan tadarus di rumah'),
  (5, 'B', 'M. Abinaya Pratama Ramadhan', 'iqra', 'Iqro 6', 'Iqro 6', 24, 30, 6, 15, 'not_achieved', '-'),
  (5, 'B', 'Mhd Farhan', 'iqra', 'Iqro 6', 'Iqro 6', 4, 14, 10, 15, 'not_achieved', 'Masih harus sering berlatih panjang lendek bacaan dan juga ghunnah'),
  (5, 'B', 'Muhammad Fajri Ramadhan', 'iqra', 'Iqro 6', 'Iqro 6', 17, 32, 15, 15, 'achieved', 'Alhamdulillah tercapai, latihan terus untuk pemutqinan iqro 6'),
  (5, 'B', 'Muhammad Habib Kurniawan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 11, 5, 15, 'not_achieved', 'Serung sering latihan tadarus di rumah, perbaiki ikhfa dan ghunnah'),
  (5, 'B', 'Muhammad Hanan Faiz', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Ananda naik level tahsin lanjutan dan tahsin dasar dari Iqro'' 6 hal 30-32.'),
  (5, 'B', 'Muhammad Ibrahim Athallah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 2, 1, 15, 'not_achieved', 'Ananda naik level tahsin lanjutan dari tahsin dasar di Iqro''6 halaman 21-32.'),
  (5, 'B', 'Muhammad Najeeb Hossain Sipayung', 'iqra', 'Iqro 6', 'Iqro 6', 18, 24, 6, 15, 'not_achieved', '-'),
  (5, 'B', 'Muhammad Najib Baihaqi', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 18, 23, 5, 15, 'not_achieved', 'Latihan terus di rumah panjang pendek'),
  (5, 'B', 'Muhammad Syafiq Syahputra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', 'Cukup baik, sering sering tadarus di rumah agar semakin lancar'),
  (5, 'B', 'Pandi Tri Utomo', 'iqra', 'Iqro 4', 'Iqro 4', 4, 5, 1, 15, 'not_achieved', 'Abi dan Umi, Ananda diturunnkan di Iqro''4 halaman 4 karena banyak tidak lancar jika dinaikkan ke halaman selanjutnya dan mohon bantuannya Abi dan Umi untuk selalu banyak banyak mengulang PR Iqro''nya.'),
  (5, 'B', 'Rafa Azhmi Fadhilah', 'iqra', 'Iqro 5', 'Iqro 5', 6, 10, 4, 15, 'not_achieved', 'Harus lebih sering lagi latihan membaca iqro di rumah, masih banyak kesalahan bacaan'),
  (5, 'B', 'Rifqy Syafiq Tarigan', 'iqra', 'Iqro 6', 'Iqro 6', 9, 16, 7, 15, 'not_achieved', 'Masih harus memperbaiki bacaan ikhfa, dan ghunnah, jugapanjangvpendek terkadang mauDicetak: 7 Mei 2026 Halaman 31 dari 44 keliru'),
  (5, 'B', 'Risdanald Aghna Siregar', 'iqra', 'Iqro 4', 'Iqro 5', 28, 7, 9, 15, 'not_achieved', '-'),
  (5, 'B', 'Umar', 'iqra', 'Iqro 5', 'Iqro 5', 20, 32, 12, 15, 'not_achieved', '-'),
  (5, 'B', 'Yahya Khairul Anam', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 15, 20, 5, 15, 'not_achieved', '-'),
  (5, 'B', 'Zein Al-Fatih Sitepu', 'iqra', 'Iqro 6', 'Iqro 6', 1, 4, 1, 15, 'not_achieved', 'Abi dan Umi, Ananda diturunkan Iqro'' dari Iqro''6 halaman 29 ke Iqro'' 6 halaman 3 karena jika dilanjutkan bacaan Iqro''nya banyak yanng tidak lancar dan mohon bantuan Abi dan Umi untuk membaca PR Iqro'' nya.'),
  (5, 'C', 'Adzkia Samha Saufa', 'tahfizh', 'Juz 30', 'Juz 29', 1, 1, 20, 3, 'achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Aisyah Aqilah Yanglera', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 8, 7, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Alesha Inara', 'iqra', 'Iqro 6', 'Iqro 6', 27, 32, 5, 15, 'not_achieved', 'Persiapan ujian naik tingkat (Tahsin Lanjutan)'),
  (5, 'C', 'Assyifa Rifana Fitri', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 12, 11, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Audi Anisa', 'iqra', 'Iqro 5', 'Iqro 5', 16, 25, 9, 15, 'not_achieved', 'Pelancaran bacaan dan penguatan mad (panjang pendek)'),
  (5, 'C', 'Azzahra Nanda Wibowo', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 14, 11, 15, 'not_achieved', 'Penguatan mad wajib dan ghunnah'),
  (5, 'C', 'Bilqis Raysah', 'iqra', 'Iqro 5', 'Iqro 5', 9, 10, 1, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Carissa Aqila Putri', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 15, 10, 15, 'not_achieved', 'Perbaikan waqaf dan penguatan mad'),
  (5, 'C', 'Devia Hafizah', 'tahfizh', 'Juz 30', 'Juz 29', 1, 1, 20, 3, 'achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Dyandra Putri Santoso', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Fatihah Muflihah Al Husein', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 8, 18, 10, 15, 'not_achieved', 'Penguatan mad wajib dan ghunnah'),
  (5, 'C', 'Fusailah Sihombing', 'iqra', 'Iqro 6', 'Iqro 6', 28, 32, 4, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Gadis Humairah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 13, 8, 15, 'not_achieved', 'Penguatan mad dan ghunnah'),
  (5, 'C', 'Hafidzah Az-Zahra', 'iqra', 'Iqro 6', 'Iqro 6', 23, 32, 9, 15, 'not_achieved', 'Persiapan ujian naik tingkat (tahsin lanjutan)'),
  (5, 'C', 'Hana Fakhirah Hamdan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Hania Syakira', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Haura Aqilatunnisa', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 15, 9, 15, 'not_achieved', 'Penguatan waqaf dan lebih men jahr kan suara lagi'),
  (5, 'C', 'Hilwa Shanum', 'iqra', 'Iqro 6', 'Iqro 6', 23, 32, 9, 15, 'not_achieved', 'Persiapan ujian naik tingkat (Tahsin Lanjutan)'),
  (5, 'C', 'Izza Hilyah Nafisah', 'iqra', 'Iqro 6', 'Iqro 6', 17, 27, 10, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Jihan Alifa', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 23, 13, 15, 'not_achieved', 'Penguatan makhraj þ¡ dan þé'),
  (5, 'C', 'Najla Aqila Zahra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 12, 11, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Naura Jasmine', 'iqra', 'Iqro 5', 'Iqro 5', 21, 29, 8, 15, 'not_achieved', 'Melancarkan bacaan dan penguatan mad'),
  (5, 'C', 'Raisa Azzahra', 'iqra', 'Iqro 4', 'Iqro 5', 31, 12, 11, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Raisha Shanika Azka', 'iqra', 'Iqro 5', 'Iqro 5', 25, 32, 7, 15, 'not_achieved', 'Penurunan Iqro'' 5 hal 10 (masih perlu pengutan dan latihan membaca setiap hari agar lisan lancar)'),
  (5, 'C', 'Shakira Afifah Haiqi', 'iqra', 'Iqro 6', 'Iqro 6', 13, 20, 7, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Syahidah Almahira Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 15, 10, 15, 'not_achieved', 'Penguatan bacaan mad dan Al Jauf (membuka mulut dengan sempurna agar huruf terdengar jelas)Dicetak: 7 Mei 2026 Halaman 33 dari 44'),
  (5, 'C', 'Syakura Haura ''Ainin', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 18, 11, 15, 'not_achieved', 'Penguatan Ghunnah dan waqaf'),
  (5, 'C', 'Talitha Azzahra Bancin', 'iqra', 'Iqro 6', 'Iqro 6', 30, 32, 2, 15, 'not_achieved', 'Maulina Sitorus -'),
  (5, 'C', 'Tita Andika', 'tahfizh', 'Juz 30', 'Juz 30', 1, 20, 19, 3, 'achieved', 'Maulina Sitorus -'),
  (5, 'D', 'Adisty Hanifah Kurniawan', 'iqra', 'Iqro 6', 'Iqro 6', 24, 27, 3, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah lancar untuk mad jaiz dan wajib serta tempo bacaannya lebih diperhatikan lagi ya nak"'),
  (5, 'D', 'Akira Shofiyah Hanim', 'iqra', 'Iqro 5', 'Iqro 5', 13, 19, 6, 15, 'not_achieved', NULL),
  (5, 'D', 'Annisa Putri Habibi', 'tahfizh', 'Juz 30', 'Juz 30', 1, 20, 19, 3, 'achieved', '-'),
  (5, 'D', 'Askana Sakhi', 'iqra', 'Iqro 6', 'Iqro 6', 16, 20, 4, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah bagus hanya saja untuk mad wajib dan jaiz serta tempo bacaannya lebih diperhatikan lagi ya nak"'),
  (5, 'D', 'Auliya queen Jenius Husna Simanjuntak', 'iqra', 'Iqro 2', 'Iqro 2', 23, 24, 1, 15, 'not_achieved', '"Samangat terus belajar nya ya nak, jangan sering libur "'),
  (5, 'D', 'Azizah Sofhia Ramadhani', 'iqra', 'Iqro 4', 'Iqro 4', 22, 26, 4, 15, 'not_achieved', NULL),
  (5, 'D', 'Calissa Rania', 'iqra', 'Iqro 3', 'Iqro 3', 20, 23, 3, 15, 'not_achieved', NULL),
  (5, 'D', 'Fadhillah Azzahrah Siregar', 'iqra', 'Iqro 6', 'Iqro 6', 23, 27, 4, 15, 'not_achieved', NULL),
  (5, 'D', 'Halimah Tusyahdiyah', 'iqra', 'Iqro 5', 'Iqro 5', 20, 22, 2, 15, 'not_achieved', '"Semangat terus belajar nya ya nak.. lebih teliti lagi membedakan mana yang harus dibaca panjang dan mana yang pendek ya."'),
  (5, 'D', 'Hasanah Qurrota Aini', 'iqra', 'Iqro 5', 'Iqro 5', 9, 12, 3, 15, 'not_achieved', NULL),
  (5, 'D', 'Keisha Almira Dewi', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 10, 3, 15, 'not_achieved', NULL),
  (5, 'D', 'Keisha Kirana', 'iqra', 'Iqro 6', 'Iqro 6', 25, 31, 6, 15, 'not_achieved', 'saja untuk mad wajib dan jaiz serta tempo bacaannya lebih diperhatikan lagi ya nak"'),
  (5, 'D', 'Mahira Amini', 'tahfizh', 'Juz 30', 'Juz 29', 20, 10, 30, 3, 'achieved', NULL),
  (5, 'D', 'Nada Muslimah Sidik', 'iqra', 'Iqro 6', 'Iqro 6', 11, 16, 5, 15, 'not_achieved', '"Semangat terus belajar nya ya nak.. Lebih teliti lagi membedakan panjang pendek serta tempo dalam bacaan"'),
  (5, 'D', 'Nafisah Hanin Jayadi', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 11, 4, 15, 'not_achieved', NULL),
  (5, 'D', 'Nazhira Syauqi Yatul Munawir', 'iqra', 'Iqro 6', 'Iqro 6', 9, 12, 3, 15, 'not_achieved', NULL),
  (5, 'D', 'Nur Hafizah Rizqi', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', '-'),
  (5, 'D', 'Nur Indah Ailani Harahap', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 15, 22, 7, 15, 'not_achieved', '-'),
  (5, 'D', 'Qyara Anaia Shaliha', 'tahfizh', 'Juz 30', 'Juz 29', 20, 10, 30, 3, 'achieved', NULL),
  (5, 'D', 'Raisya Azzahra Hakim', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 7, 2, 15, 'not_achieved', NULL),
  (5, 'D', 'Rasyuqa Kinatya Praja', 'tahfizh', 'Juz 28', 'Juz 28', 7, 8, 1, 3, 'not_achieved', '-'),
  (5, 'D', 'Rumaisha Amaturrahman Surbakti', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 7, 6, 15, 'not_achieved', '-'),
  (5, 'D', 'Salimah Khoir', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 14, 4, 15, 'not_achieved', NULL),
  (5, 'D', 'Salsabila Jannah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 8, 3, 15, 'not_achieved', NULL),
  (5, 'D', 'Salvina Varisha', 'iqra', 'Iqro 5', 'Iqro 5', 6, 13, 7, 15, 'not_achieved', '"Alhamdulillah bacaan ananda sudah semakin lancar, akan tetapi lebih berlatih lagi untuk pengucapan huruf þµ þ™ þ« þ¯ þ­"'),
  (5, 'D', 'Salwa Nabila', 'iqra', 'Iqro 4', 'Iqro 4', 22, 24, 2, 15, 'not_achieved', NULL),
  (5, 'D', 'Shakyla Aulia', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 9, 8, 15, 'not_achieved', '-'),
  (5, 'D', 'Shasha Shabillah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 6, 5, 15, 'not_achieved', '-'),
  (5, 'D', 'Syifa Az Zahra', 'iqra', 'Iqro 6', 'Iqro 6', 9, 12, 3, 15, 'not_achieved', NULL),
  (6, 'A', 'Abdullah Aziz syahreza sinurat', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 12, 2, 15, 'not_achieved', '-'),
  (6, 'A', 'Abdurrahman arrayyan fadhillah', 'iqra', 'Iqro 4', 'Iqro 5', 25, 13, 18, 15, 'achieved', '-'),
  (6, 'A', 'Abdurrahman Umar alfaruq', 'tahfizh', 'Juz 30', 'Juz 28', 1, 1, 40, 3, 'achieved', '-'),
  (6, 'A', 'Abrizam Rajanangin Batubara', 'iqra', 'Iqro 6', 'Iqro 6', 9, 9, 0, 15, 'not_achieved', '-'),
  (6, 'A', 'Arjuna Siddiq Al-baihaqi', 'iqra', 'Iqro 4', 'Iqro 5', 26, 4, 8, 15, 'not_achieved', '-'),
  (6, 'A', 'Aufa Ar-Razzaq', 'iqra', 'Iqro 4', 'Iqro 5', 25, 1, 8, 15, 'not_achieved', '-'),
  (6, 'A', 'Azam Khalil Ar ramsyi', 'iqra', 'Iqro 5', 'Iqro 5', 4, 25, 21, 15, 'achieved', '-'),
  (6, 'A', 'Azka ramadhan', 'iqra', 'Iqro 4', 'Iqro 4', 9, 23, 14, 15, 'not_achieved', '-'),
  (6, 'A', 'Azwar Zaidan ibram', 'iqra', 'Iqro 4', 'Iqro 4', 15, 31, 16, 15, 'achieved', '-'),
  (6, 'A', 'Bayu alfahrizi', 'iqra', 'Iqro 4', 'Iqro 5', 21, 4, 13, 15, 'not_achieved', '-'),
  (6, 'A', 'Daffa Ramadhan Diarja', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 9, 12, 3, 15, 'not_achieved', '-'),
  (6, 'A', 'Danish Arfa Rizqiansyah', 'iqra', 'Iqro 6', 'Iqro 6', 23, 29, 6, 15, 'not_achieved', '-'),
  (6, 'A', 'Dzacky fayyadh pratama', 'iqra', 'Iqro 4', 'Iqro 5', 29, 8, 9, 15, 'not_achieved', '-'),
  (6, 'A', 'Fathirrahman Azka alfonso', 'iqra', 'Iqro 6', 'Iqro 6', 9, 32, 23, 15, 'achieved', '-'),
  (6, 'A', 'Kenzie Aditya Pratama Siswanto', 'tahfizh', 'Juz 30', 'Juz 27', 1, 1, 60, 3, 'achieved', '-'),
  (6, 'A', 'Luay Dwi Irawan', 'iqra', 'Iqro 6', 'Iqro 6', 17, 28, 11, 15, 'not_achieved', '-'),
  (6, 'A', 'Muhammad Adham Ginting', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 0, 2, 2, 15, 'not_achieved', 'baru ujian iqra'' Semoga makhraj nya lebih baik lagi'),
  (6, 'A', 'Muhammad Adiyat Harahap', 'iqra', 'Iqro 6', 'Iqro 6', 17, 24, 7, 15, 'not_achieved', '-'),
  (6, 'A', 'Muhammad Affan alwi', 'iqra', 'Iqro 4', 'Iqro 5', 31, 18, 17, 15, 'achieved', '-'),
  (6, 'A', 'Muhammad arifin ilham', 'iqra', 'Iqro 4', 'Iqro 4', 13, 22, 9, 15, 'not_achieved', '-'),
  (6, 'A', 'Muhammad Fadhil yaqdan gultom', 'iqra', 'Iqro 4', 'Iqro 5', 25, 9, 14, 15, 'not_achieved', '-'),
  (6, 'A', 'Muhammad Thalahah Al-Ukhasyah', 'iqra', 'Iqro 4', 'Iqro 4', 17, 19, 2, 15, 'not_achieved', 'Serinh tidak hadir ke sekolah'),
  (6, 'A', 'Muhammad Zahwan Firdaus', 'iqra', 'Iqro 6', 'Iqro 6', 22, 30, 8, 15, 'not_achieved', '-'),
  (6, 'A', 'Musa Ibnu hafidz', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 15, 3, 15, 'not_achieved', '-'),
  (6, 'A', 'Syarif Abdullah Razzaq', 'iqra', 'Iqro 6', 'Iqro 6', 1, 10, 7, 15, 'not_achieved', '-'),
  (6, 'A', 'Ubay', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 9, 11, 2, 15, 'not_achieved', '-'),
  (6, 'A', 'Yusuf Abdillah tarigan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 17, 27, 10, 15, 'not_achieved', '-'),
  (6, 'A', 'Zaheer Ansharie Permana', 'iqra', 'Iqro 6', 'Iqro 6', 22, 32, 10, 15, 'not_achieved', 'Ujian iqra'' dan belum lulus, diperhatikan lagi bacaan maad nya'),
  (6, 'B', 'Aldian Praditya', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 77, 84, 7, 15, 'not_achieved', '-'),
  (6, 'B', 'ARKAN ASHARI MAULANA', 'iqra', 'Iqro 5', 'Iqro 5', 8, 10, 2, 15, 'not_achieved', '-'),
  (6, 'B', 'Ayyub Fadhlullah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 11, 19, 8, 15, 'not_achieved', 'Surah Al-Baqarah'),
  (6, 'B', 'Dzakir Khafadi Nasution', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 118, 122, 4, 15, 'not_achieved', '-'),
  (6, 'B', 'DZENKA MUHAMMAD AVICENNA', 'iqra', 'Iqro 5', 'Iqro 5', 6, 9, 3, 15, 'not_achieved', '-'),
  (6, 'B', 'Faad Alzahabi', 'iqra', 'Iqro 4', 'Iqro 5', 27, 10, 13, 15, 'not_achieved', '-'),
  (6, 'B', 'FAEYZA ABRISAM FATHANAH', 'iqra', 'Iqro 6', 'Iqro 6', 1, 6, 3, 15, 'not_achieved', '-'),
  (6, 'B', 'FAHMI RAMADHAN', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 5, 4, 100, 'not_achieved', '-'),
  (6, 'B', 'GIBRAN AHMAD SYAHPUTRA', 'iqra', 'Iqro 6', 'Iqro 6', 25, 28, 3, 15, 'not_achieved', '-'),
  (6, 'B', 'Habil Mumfarid', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 57, 65, 8, 15, 'not_achieved', '-'),
  (6, 'B', 'HAFIDZ RAFFI RABBANI', 'iqra', 'Iqro 4', 'Iqro 4', 17, 20, 3, 15, 'not_achieved', '-'),
  (6, 'B', 'HAFIDZ RAMADHAN NAPITULU', 'iqra', 'Iqro 6', 'Iqro 6', 12, 14, 2, 15, 'not_achieved', '-'),
  (6, 'B', 'Khairi Azzam', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 17, 5, 15, 'not_achieved', '-'),
  (6, 'B', 'Lathef Nohan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 9, 6, 15, 'not_achieved', '-'),
  (6, 'B', 'Muchtar Hariansyah Simamora', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 55, 59, 4, 15, 'not_achieved', '-'),
  (6, 'B', 'Muhammad Aidil Ginting', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 4, 13, 9, 15, 'not_achieved', '-'),
  (6, 'B', 'Muhammad Gibran Habibi', 'iqra', 'Iqro 6', 'Iqro 6', 5, 11, 6, 15, 'not_achieved', '-'),
  (6, 'B', 'Muhammad Hafiz Ardian', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 98, 102, 4, 15, 'not_achieved', '-'),
  (6, 'B', 'MUHAMMAD HANIF KHAN', 'iqra', 'Iqro 6', 'Iqro 6', 27, 29, 2, 15, 'not_achieved', '-'),
  (6, 'B', 'MUHAMMAD ROBI', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 4, 1, 100, 'not_achieved', '-'),
  (6, 'B', 'NURHAN AFKAR FADHIL', 'iqra', 'Iqro 5', 'Iqro 5', 4, 6, 2, 15, 'not_achieved', '-'),
  (6, 'B', 'RAZIQ HANAN NOVIANTO', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 11, 13, 2, 100, 'not_achieved', '-'),
  (6, 'B', 'Said khoir', 'tahfizh', 'Juz 27', 'Juz 26', 13, 5, 28, 3, 'achieved', '-'),
  (6, 'B', 'SULTAN NADIF', 'iqra', 'Iqro 2', 'Iqro 2', 22, 24, 2, 15, 'not_achieved', '-'),
  (6, 'B', 'SYABIL RIZKI ( V-A)', 'iqra', 'Iqro 6', 'Iqro 6', 8, 16, 8, 15, 'not_achieved', '-'),
  (6, 'B', 'SYAFIQ FAUZAN', 'tahfizh', 'Tahfizh', 'Tahfizh', 1, 3, 2, 100, 'not_achieved', '-'),
  (6, 'B', 'Syakir Al-Baihaqi', 'iqra', 'Iqro 6', 'Iqro 6', 17, 23, 6, 15, 'not_achieved', '-'),
  (6, 'B', 'Zaid', 'tahfizh', 'Juz 28', 'Juz 27', 11, 6, 25, 3, 'achieved', '-'),
  (6, 'B', 'ZIKRI ALHAFIS ZULKARNAIN', 'iqra', 'Iqro 6', 'Iqro 6', 6, 9, 3, 15, 'not_achieved', '-'),
  (6, 'C', 'Adzkia Samha Saufa', 'tahfizh', 'Tahfizh', 'Tahfizh', 582, 597, 15, 100, 'not_achieved', 'Alhamdul;illah bacaan sudah bagus dan lancar serta tajwid baik Tetap semangat ya kak'),
  (6, 'C', 'Afifah Zhahirah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 28, 31, 3, 100, 'not_achieved', 'Alhamdulillah bacaan sudah bagus dan lancar perlu ditingkatkan lagi tajwidnya Tetap semangat ya kak'),
  (6, 'C', 'Aisyah Lubis', 'tahfizh', 'Tahfizh', 'Tahfizh', 518, 521, 3, 100, 'not_achieved', 'Alhamdulillah bacaan sudah bagus dan lancar dan tajwidnya baik Tetap semangat ya kak.'),
  (6, 'C', 'Akifa Dwila Putri', 'iqra', 'Iqro 6', 'Iqro 6', 4, 31, 27, 15, 'achieved', 'Alhamdulillah... Bacaan lancar,tapi masih banyak yg harus diperbaiki, terutama Makhraj dan Tajwidnya. tetap semangat y kk Akifa !!!!!!'),
  (6, 'C', 'Alifa Azkana Shadiqah', 'tahfizh', 'Tahfizh', 'Tahfizh', 28, 30, 2, 100, 'not_achieved', 'Bacaan kurang lancar, perlu banyak perbaikan Makhraj dan Tajwid tetap semangat y kk !!!'),
  (6, 'C', 'Alnisa Putri Hamzah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 14, 17, 3, 100, 'not_achieved', 'Alhamdulillah... bacaannya sdh lancar hanya perlu di tingkatkan lagi Makhraj dan Tajwidnya tetap semangat y kk!!'),
  (6, 'C', 'Assyfa Aqilla Jasmine', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 13, 17, 4, 100, 'not_achieved', 'Alhamdulillah.. bacaan kk sdh lancar, namun masih perlu perbaikan Makhraj dan Tajwidnya . lebih semangat lagi menghafal dan memuraja''ahnya y kk !!'),
  (6, 'C', 'Aziqra Valeeqa Siregar', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 4, 8, 4, 100, 'not_achieved', 'Bacaan kurang lancar, masih perlu banyak perbaikan Makhraj dan Tajwid. tetap semangat y kk Aziqra !!!'),
  (6, 'C', 'Azzahra Asyila Rahma', 'iqra', 'Iqro 6', 'Iqro 6', 4, 25, 21, 15, 'achieved', 'Alhamdulillah....... Bacaan lancar,Tapi masih perlu banyak belajar untuk memperbaiki bacaan, Makhraj dan Tajwidnya. Tetap semangat kk Asyila !!!!!!!'),
  (6, 'C', 'Caroline Yumnaa Syahnant', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 20, 32, 12, 100, 'not_achieved', 'Alhamdulillah... bacaan kk lancar ,tapi masih perlu perbaikan Makhraj dan Tajwid'),
  (6, 'C', 'Delia Kirani Lubis', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 28, 32, 4, 100, 'not_achieved', 'Alhamdulillah.. bacaan kk sdh lancar, namun masih perlu perbaikan Makhraj dan Tajwid tetap semangat y kk !!!!'),
  (6, 'C', 'Fadiyah Khayla Azzahra Ketaren', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 13, 1, 100, 'not_achieved', 'Bacaan kurang lancar , semoga kk lebih semangat lagi belajar, agar bacaan kk lebih baik lagi.'),
  (6, 'C', 'Fazila Hafiza', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 13, 17, 4, 100, 'not_achieved', 'Alhamdulillah... bacaan kk lancar, tapi masih perlu perbaikan Makhraj dan Tajwid . tetap semangat y kk !!!'),
  (6, 'C', 'Fitra Alfatin Nisa', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 24, 26, 2, 100, 'not_achieved', 'Bacaan kk kurang lancar, masih banyak yg harus di perhatikan Makhraj dan Tajwid. tetap semangat y kk !!!'),
  (6, 'C', 'Gusti Ayu Kailani', 'iqra', 'Iqro 6', 'Iqro 6', 30, 31, 1, 15, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Hafiza Khaira Lubna', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 27, 29, 2, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Hilya Nasikah Markhan', 'iqra', 'Iqro 4', 'Iqro 4', 29, 31, 2, 15, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Husna Fhataniah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 10, 0, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Khanza Raisya Putri', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 21, 21, 0, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Luthfia Thalita Salim', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 28, 30, 2, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Nadhifatul Shifwa Lubis', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 6, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Nadien Shafiya Azka', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 25, 26, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Najifah Fildza', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 22, 23, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Natasya', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 33, 34, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Naura Dapita Br Surbakti', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 21, 22, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Nurhasanah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 2, 3, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Raihana Inayasya Pasaribu', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 30, 31, 1, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'C', 'Thalita Zahra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 17, 17, 0, 100, 'not_achieved', 'Fashiha Billa -'),
  (6, 'D', 'Anzu Ghaisani Bilqis', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 30, 35, 5, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Ashilah Aprilia Syah Br Tarigan', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 19, 18, 15, 'achieved', 'Tanda waqaf,penerapan panjang pendek mad dan ketepatan harakat, makharijul huruf masih sering tertukar serta tidak diulangi ketika salah, huruf hamzah penyebutan seperti `ain'),
  (6, 'D', 'Attahira Zalfa Ahmad', 'iqra', 'Iqro 6', 'Iqro 6', 14, 24, 10, 15, 'not_achieved', 'Tajwid dan makharijul hueuf dzal masih perlu perbaikan'),
  (6, 'D', 'Azizah Dinata', 'iqra', 'Iqro 5', 'Iqro 5', 23, 28, 5, 15, 'not_achieved', 'Makharijul huruf tsa, dzal dan dzho belum tepat,mad beserta tajwid'),
  (6, 'D', 'Dzakira Azzahra', 'tahfizh', 'Juz 30', 'Juz 28', 1, 11, 30, 3, 'achieved', 'Makharijul huruf masih perlu perbaikan selalu tsa'),
  (6, 'D', 'Fadilla Fauzianya Siregar', 'iqra', 'Iqro 4', 'Iqro 4', 24, 31, 7, 15, 'not_achieved', 'Makharijul huruf belum tepat, panjang pendek serta tajwid perlu perbaikan'),
  (6, 'D', 'Fahira Khanza Azzahra', 'iqra', 'Iqro 5', 'Iqro 5', 9, 24, 15, 15, 'achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (6, 'D', 'Hafiza Khaira Lubna', 'iqra', 'Iqro 5', 'Iqro 6', 15, 5, 20, 15, 'achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Agar tambah lancar Baarakallahu Fiik'),
  (6, 'D', 'Hilyatun Qanita', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 20, 27, 7, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Kayla Zahirah Humairah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 6, 10, 4, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Keysha Khalifa Shaki Fonna T', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 7, 14, 7, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Khansa Adiba Shakila', 'iqra', 'Iqro 5', 'Iqro 5', 17, 28, 11, 15, 'not_achieved', 'Makharijul huruf masih perlu perbaiakan serta tajwidnya'),
  (6, 'D', 'Kinara Az Zahra', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 4, 9, 5, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Marsya Hamizah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 9, 8, 15, 'not_achieved', 'Bacaan masih tergesa-gesa,penerapan hukum nun mati dan tasydid belum cukup baik, pengetahuan tanda waqaf jim belum tepat'),
  (6, 'D', 'Mumin Aisha Liyagati', 'iqra', 'Iqro 6', 'Iqro 6', 6, 23, 17, 15, 'achieved', 'Tajwid perlu perbaiakan'),
  (6, 'D', 'Nadhifa Sheena Fakhira Pulungan', 'iqra', 'Iqro 5', 'Iqro 5', 14, 20, 6, 15, 'not_achieved', 'Makaharijul huruf, tajwid, bacaaan masih terputus-putus'),
  (6, 'D', 'Naura Nadhifa', 'iqra', 'Iqro 5', 'Iqro 5', 13, 20, 7, 15, 'not_achieved', 'Makharijul huruf belum tepat, tajwid,perlu perbaikan'),
  (6, 'D', 'Putri Ramadani', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 5, 9, 4, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Raisa Amanda', 'iqra', 'Iqro 6', 'Iqro 6', 4, 10, 6, 15, 'not_achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (6, 'D', 'Salwa Azmi Salsabila', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 21, 20, 15, 'achieved', 'membaca tenang,perlu membiasakan membedakan tafkhim dan tarqiq pada lafaz jalalah sesuai harakat sebelumnya, tanda waqaf mim.'),
  (6, 'D', 'Syaira Al Basit', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 3, 11, 8, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Syakira Anindya Maheswari', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 1, 20, 19, 15, 'achieved', 'Penerapan mad aridh lissukun serta hukum nun mati belum tepat, pelafalan huruf dzho cenderung terdengar seperti zai yang ditebalkan, serta tanda waqaf jim belum tepat'),
  (6, 'D', 'Tia Rizki', 'iqra', 'Iqro 4', 'Iqro 4', 5, 12, 7, 15, 'not_achieved', 'Pr iqra-nya tetap dibaca dirumah ya kak Baarakallahu Fiik'),
  (6, 'D', 'Wafa Gumaisha', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 10, 18, 8, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Zahidah Qanita Annajiyah', 'tahsin', 'Tahsin Lanjutan', 'Tahsin Lanjutan', 12, 20, 8, 100, 'not_achieved', 'Perbanyak tadarus dirumah ya kak, agar makin lancar membaca Alquran-nya Baarakallahu Fiik'),
  (6, 'D', 'Zahra Aqila Queenzah Sipayung', 'iqra', 'Iqro 5', 'Iqro 5', 6, 10, 4, 15, 'not_achieved', 'bacaan terlalu tergesa-gesa, Makharijul huruf masih belum tepat, tajwid perlu bimbingan'),
  (6, 'D', 'Zahra Mentari', 'iqra', 'Iqro 5', 'Iqro 5', 15, 20, 5, 15, 'not_achieved', 'Makharijul huruf masih perlu perbaiakan,bacaan masih terputus-putus');

SELECT 'rows_from_pdf' AS check_name, count(*) AS total FROM _restore_april_2026_reports;

SELECT 'matched_students' AS check_name, count(*) AS total
FROM _restore_april_2026_reports r
JOIN public.students s
  ON s.kelas = r.kelas
 AND s.rombel = r.rombel
 AND lower(regexp_replace(trim(s.nama), '\s+', ' ', 'g')) = lower(regexp_replace(trim(r.nama), '\s+', ' ', 'g'));

SELECT 'existing_april_reports_before_restore' AS check_name, count(*) AS total
FROM public.monthly_reports
WHERE month = 4 AND year = 2026;

SELECT r.kelas, r.rombel, r.nama
FROM _restore_april_2026_reports r
LEFT JOIN public.students s
  ON s.kelas = r.kelas
 AND s.rombel = r.rombel
 AND lower(regexp_replace(trim(s.nama), '\s+', ' ', 'g')) = lower(regexp_replace(trim(r.nama), '\s+', ' ', 'g'))
WHERE s.id IS NULL
ORDER BY r.kelas, r.rombel, r.nama;

WITH inserted AS (
  INSERT INTO public.monthly_reports (
    student_id, month, year, program_type, iqra_level, end_iqra_level,
    start_page, end_page, pages_read, target_pages, achievement_status, notes, created_by
  )
  SELECT
    s.id, 4, 2026, r.program_type, r.iqra_level, r.end_iqra_level,
    r.start_page, r.end_page, r.pages_read, r.target_pages, r.achievement_status, r.notes, NULL
  FROM _restore_april_2026_reports r
  JOIN public.students s
    ON s.kelas = r.kelas
   AND s.rombel = r.rombel
   AND lower(regexp_replace(trim(s.nama), '\s+', ' ', 'g')) = lower(regexp_replace(trim(r.nama), '\s+', ' ', 'g'))
  ON CONFLICT (student_id, month, year) DO NOTHING
  RETURNING student_id
)
SELECT 'inserted_missing_april_reports' AS check_name, count(*) AS total FROM inserted;

SELECT 'existing_april_reports_after_restore' AS check_name, count(*) AS total
FROM public.monthly_reports
WHERE month = 4 AND year = 2026;

COMMIT;
