// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in Tahsin user calling the MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list_students.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool2({
  name: "list_students",
  title: "List students",
  description: "List students visible to the signed-in user (filtered by Supabase RLS). Optional filter by grade (kelas) and rombel.",
  inputSchema: {
    kelas: z.number().int().min(1).max(6).optional().describe("Grade level (1-6)"),
    rombel: z.string().optional().describe("Class section, e.g. A, B, C, or D"),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kelas, rombel, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("students").select("id, nama, nis, nisn, kelas, rombel, level, status_bacaan, halaman_terakhir, perlu_perhatian").order("kelas").order("rombel").order("nama").limit(limit ?? 50);
    if (typeof kelas === "number") query = query.eq("kelas", kelas);
    if (rombel) query = query.eq("rombel", rombel);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_student_progress.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_student_progress_default = defineTool3({
  name: "get_student_progress",
  title: "Get student progress",
  description: "Fetch a student's basic profile and their most recent Al-Qur'an reading progress entries. Access is filtered by RLS.",
  inputSchema: {
    student_id: z2.string().uuid().describe("Student UUID (students.id)"),
    limit: z2.number().int().min(1).max(50).optional().describe("Max progress entries (default 10)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const [studentRes, progressRes] = await Promise.all([
      supabase.from("students").select("id, nama, kelas, rombel, level, status_bacaan, halaman_terakhir, perlu_perhatian, catatan_perhatian").eq("id", student_id).maybeSingle(),
      supabase.from("progress_entries").select("*").eq("student_id", student_id).order("created_at", { ascending: false }).limit(limit ?? 10)
    ]);
    if (studentRes.error) {
      return { content: [{ type: "text", text: studentRes.error.message }], isError: true };
    }
    if (progressRes.error) {
      return { content: [{ type: "text", text: progressRes.error.message }], isError: true };
    }
    const payload = {
      student: studentRes.data,
      progress: progressRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jmvfudupywneitjiwccy";
var mcp_default = defineMcp({
  name: "tahsin-sdit-mcp",
  title: "Tahsin SDIT Luqmanul Hakim",
  version: "0.1.0",
  instructions: "Tools for the Tahsin SDIT Luqmanul Hakim portal. Use `whoami` to verify the signed-in user, `list_students` to browse students visible to that user (filtered by role via RLS), and `get_student_progress` to inspect a student's recent Al-Qur'an reading progress.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_students_default, get_student_progress_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
